### ISSUE TITLE
[FEATURE] Convert lancer-data into Compendiums

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#1]
Create Compendiums from the parts of `lancer-data` which are needed to assemble pilots and mechs:
- [x] Skill Triggers
- [x] Talents
- [x] Core Bonuses
- [x] Pilot Equipment
- [x] Mech Frames
- [x] Mech Systems
- [x] Mech Weapons
- [x] Licenses (derived from Mech data, doesn't exist directly in `lancer-data`)

**Comment by BoltsJ** [comment]
Creating a Journal compendium for statuses would a useful addition. Just commenting here so I don't forget again.

**Comment by Eranziel** [comment]
Already complete in `dev-1.0`.
