### ISSUE TITLE
[FEATURE] Overcharge Counter for PCs/NPCs

### ISSUE THREAD

**Issue by yyyop6** [Eranziel/foundryvtt-lancer#101]
I want my players to have some molten milk because they're epic but they can't because they can't track how much heat they've lost due to nuking their cores into the depths of the planet.

**Comment by Grygon** [comment]
Wanted to sneak some mildly spicy milk in for you before the next version, but I'm leaving this open so I can remember to get some real molten milk served up for you with a macro
