### ISSUE TITLE
[BUG] Editing or opening a "Charges" system causes it to blank out on the mech sheet

### ISSUE THREAD

**Issue by HiddenWings25** [Eranziel/foundryvtt-lancer#116]
**Describe the bug**
When you close a grenade system, or edit anything in the system and leave the box, the dropdowns for range and area reset to NONE, the damage type boxes reset to KINETIC, and the effects no longer display on the mech sheet. Attempting to change anything further just resets things back to this state.

This was discovered when I tried to set limited uses on the GMS Smoke charges and hex charges, but it does also occur for the other mine systems I checked (Blink charges, Grounding Charges, Spike Charges) It can also be observed if you set a custom system to "charges".

**To Reproduce**
1. Add Hex Charges or similar system to a mech via drag and drop
2. Click on the icon on the top left to open the full description.
3. Close the description
4. Observe that the description is no longer on the mech sheet

**Expected behavior**
The System should reflect any edits and not lose all of its data.

**Screenshots**
Mech Sheet:
![Mech sheet after bug](https://i.imgur.com/HIHdWNU.png)

System:
![System after bug](https://i.imgur.com/S1H5wE2.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Edge, Firefox
 - Foundry version: 0.7.7
 - Lancer system version 0.1.15

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.

Ashgar#0216

**Comment by Grygon** [comment]
Re-opening, I guess this didn't fix it and I just didn't test as thoroughly as I thought I did...

**Comment by Grygon** [comment]
Fixed in v0.9.1
