### ISSUE TITLE
[FEATURE] Provide default images for actors

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#120]
**Describe the solution you'd like**
To make actor (Pilot & NPC) creation easier, we should be able to set the default image for a Mech, which would automatically set that mech's image instead of the generic actor icon. Ideally we also could do this for NPC classes, although that isn't included in LCP/CC data.

Part 1: 

- Take the URL from LCP ~> Frame -> image_url and associate it with the frame. If a token image isn't manually set in the prototype, use this image for any PC.
- Add a field on the mech to maintain this

Part 2: 

- Set up the ability to manually set the image on NPC classes just like the mech option
- Find some default images for all base NPC classes that 1. don't have licensing issues and 2. look cool & would be accepted by most people, then set those images to default for those classes.

**Describe alternatives you've considered**
Manual workflows are fine but this would be very cool

**Additional context**
Totally fine to do this myself but wanted to put this here to make sure it stays on our radar when I inevitably forget

**Discord contact info**
Grygon#9138

**Comment by Grygon** [comment]
Note: This seems to run into CORS issues when trying to access the standard images in Long Rim. We'd need to re-host, which is a whole bag of worms. Putting this project off for a while.

**Comment by ScyllPoesis** [comment]
Big fan of retrograde. Would be nice to put a little link to their stuff in the welcome page and maybe a credits link under the mech avatar on the sheet if we get permission to include their free tier assets.

**Comment by Grygon** [comment]
Addressing in #312
