### ISSUE TITLE
[BUG]Cannot delete Features from NPC Character sheets

### ISSUE THREAD

**Issue by Z3nner** [Eranziel/foundryvtt-lancer#123]
**Describe the bug**
Pressing the Delete Icon on an NPC sheet does not delete the feature, but it does open the item information window.

**To Reproduce**
1. Open an NPC character sheet
2. Scroll down to any of the NPC's features.
3. Press the Trashcan Icon on any feature

**Expected behavior**
The feature is removed from the character sheet.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, also from Foundry
 - Foundry version 0.7.8
 - Lancer system version 0.1.18

**Additional context**

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
e.g. Eranziel#1234

**Comment by Grygon** [comment]
Fixed in next release, my bad!
