### ISSUE TITLE
[BUG] Can't Drag Mech Weapons to Hotbar

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#124]
**Describe the bug**
Dragging mech weapons to hotbar does not create a macro, results in an error.

**To Reproduce**
1. Open a pilot sheet.
2. Drag a mech weapon to hotbar.
3. No macro is created.

**Expected behavior**
A new macro should be created which will roll an attack for that weapon.

**Screenshots**
![image](https://user-images.githubusercontent.com/49248157/102443884-6c32ce00-3fed-11eb-8994-4d3fdf99ddc4.png)

**Comment by Grygon** [comment]
Cannot reproduce on dev branch, Foundry v0.7.8, Chrome/FF

**Comment by Eranziel** [comment]
I'll do some more testing. I noticed it on dev branch, but on 0.7.7 in the Electron version.

**Comment by Eranziel** [comment]
It appears the actor I was testing with has some old items on it. Testing with a new actor, or by adding new items to the original actor (drag from Compendium) results in drag-to-hotbar working correctly.
