### ISSUE TITLE
[FEATURE] Add tech attack roll to NPCs

### ISSUE THREAD

**Issue by fluke** [Eranziel/foundryvtt-lancer#129]
**Is your feature request related to a problem? Please describe.**
I want to be able to roll normal tech attacks from NPCs

**Describe the solution you'd like**
I want there to the be a tech attack roll button for NPCs as all NPCs can make tech attacks.

**Describe alternatives you've considered**
Can roll the Systems save because that appears to be the same as rolling a tech attack, but this would make it easier for people to understand

**Comment by perijove** [comment]
Duplicate of #62

**Comment by fluke** [comment]
Closing as it's a duplicate.
