### ISSUE TITLE
[FEATURE] automated Structure and Stress sub-rolls

### ISSUE THREAD

**Issue by perijove** [Eranziel/foundryvtt-lancer#132]
**Is your feature request related to a problem? Please describe.**
The stress and structure macros have results that require you to roll again. Automating that roll 

**Describe the solution you'd like**
When you get a result of 2-4 on a structure check, the macro should automatically roll a d6 to tell you whether you lose a weapon or a system. Additionally, when you roll a 1 with 2 stress/structure the macro should roll your Hull/Engineering check.

**Describe alternatives you've considered**
It's definitely possible to roll it separately, but I don't see a reason the rolls shouldn't be combined.

**Additional context**
I dislike automation on my VTTs when it modifies anything on the sheet (automatically removing HP, for example), but I like it when I can hit one button and have all the useful information available (like combining attack and damage rolls on one card, or the 6d6 rolls from the Roll20 sheet).

**Discord contact info**
Perijove#5043

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
