### ISSUE TITLE
[BUG] mdi-label icon is missing from source

### ISSUE THREAD

**Issue by Lrizika** [Eranziel/foundryvtt-lancer#134]
**Describe the bug**
If you compile the system from source, the mdi-label icon (which shows up on item tags) is missing. In the release version, it's provided by materialdesignicons.css, which doesn't seem to be included in the source.

**To Reproduce**
1. Clone the repo
2. Build it
3. Launch Foundry, use the system you built
4. Look at any items with tags, the icon is missing

**Expected behavior**
The mdi-label icon should be on the left hand sides of the tags

**Screenshots**
Expected Behavior
![Screenshot_from_2021-03-09_20-24-48](https://user-images.githubusercontent.com/8592308/110576425-ac22d080-8158-11eb-9e01-835c2fa852df.png)
Actual Behavior
![Screenshot_from_2021-03-09_20-11-29](https://user-images.githubusercontent.com/8592308/110575548-eee3a900-8156-11eb-9fdc-34b78ed3dff0.png)

**Platform (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Foundry version 0.7.9
 - Lancer system version 0.1.20

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
Larkeith#6665

**Comment by Lrizika** [comment]
More concerningly, this also means that the mdi-message label is missing from items. Which is what you normally click to put the item info in chat.

**Comment by ScyllPoesis** [comment]
This should be resolved by #142.

**Comment by Grygon** [comment]
Fixed in v0.9.1
