### ISSUE TITLE
[BUG] Systems Incorrectly Report Max Uses as 0 on First Load

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#147]
**Describe the bug**
The first time a system is loaded after being added to a mech, it marks its max uses as "0"

**To Reproduce**
1. Add a limited system to a mech
2. Navigate to the system preview on the mech
3. Observe it has a max of 0

Pilot code: `78d3c986d75b174f7a6627af63d6b24e`

**Expected behavior**
Max should be correctly represented

**Screenshots**
![image](https://user-images.githubusercontent.com/647846/115945807-f3ec8580-a482-11eb-86e2-915134406b73.png)

**Platform (please complete the following information):**
Any

**Additional context**
WHITESPINE pls

**Comment by ScyllPoesis** [comment]
It's a race condition and Foundry seems to jump the queue. Everyone pressure @whitespine to use a 10ms timeout to fix this since Foundry doesn't have the proper subscription hook.

**Comment by Grygon** [comment]
@whitespine pls no

**Comment by Grygon** [comment]
Fixed in v0.9.1
