### ISSUE TITLE
[FEATURE] Better License Sheets

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#148]
**Is your feature request related to a problem? Please describe.**
Currently, the License item doesn't work very well--it has a little bit of editing, but not much. And it doesn't do a great job of describing what it's adding.

**Describe the solution you'd like**
Rework the License sheet to do two things:
1. Better view of what it's supplying in a condensed format
2. Make it view-only, except for a button that recalculates contents based on all items that reference it--to prevent the possibility of dangling references

**Describe alternatives you've considered**
Keep using it as-is--which is fine but sucks.

**Additional context**
Using the standard refview for a few things on it still which should be fixed for v1.0, but I'm going to track this as v1.1 for now.

**Comment by whitespine** [comment]
Licenses now dynamically populate themselves when viewed. However, there is still work to be done in the display component. Closing this in favor of the issue #208 .
