### ISSUE TITLE
[BUG] Failed to find actor for macro when clicking text bubble icon

### ISSUE THREAD

**Issue by Flintwyrm** [Eranziel/foundryvtt-lancer#149]
Getting a warning "failed to find actor for macro"

**To Reproduce**
1. Go to 'mech actor sheet'
2. Click on 'text bubble icon'
3. See error

**Expected behavior**
I am guessing it is supposed to print the text to chat when you press it.

**Screenshots**
![Screenshot_1763](https://user-images.githubusercontent.com/60701064/115953251-5613ad80-a4b8-11eb-9b72-aa0351c09c12.png)

**Platform (please complete the following information):**
 - Foundry version [e.g. 0.7.9]
 - Lancer system version [beta]

**Additional context**

**Discord contact info**
Flintwyrm

**Comment by ScyllPoesis** [comment]
Have tracked down and resolved the reference issue, but there's another one with the chat macro not populating with effect text that needs to be resolved as well.

**Comment by Grygon** [comment]
Fixed in v0.9.1
