### ISSUE TITLE
[BUG] Mech Speed no longer accessible from a token

### ISSUE THREAD

**Issue by The-E** [Eranziel/foundryvtt-lancer#150]
The Drag Ruler Module uses the path `actor.data.data.mech.speed` to retrieve a token's speed attribute. This no longer leads anywhere.

**To Reproduce**
1. Activate the Drag Ruler module
2. Drag a token around.

**Expected behavior**
Drag Ruler colors the path your mech takes according to its speed attribute

**Observed behavior**
Coloring fails, and the console is spammed with error messages like this:
`speed_provider.js:129 Drag Ruler (Generic Speed Provider) | The configured token speed attribute "actor.data.data.mech.speed" didn't return a speed value. To use colors based on drag distance set the setting to the correct value (or clear the box to disable this feature).`

Inspecting the _token object in the console shows that `_token.actor.data.data.mech` no longer exists, and there is no field that holds equivalent data.

**Screenshots**
![image](https://user-images.githubusercontent.com/280879/115953872-5333af80-a4ee-11eb-8c1b-cee5ef487e79.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Foundry version 0.7.9
 - Lancer system version 0.9.0

**Discord contact info**
The_E#1047

**Comment by The-E** [comment]
Per Whitespine in discord:
The Speed attribute can be read from `_token.actor.data.data.derived.mmec.ent.Speed`, this can be changed in the Drag Ruler settings.

**Comment by ScyllPoesis** [comment]
Note that the actual setting needs to be set to `actor.data.data.derived.mmec.ent.Speed`, as Drag Ruler is retrieving on the token object.
