### ISSUE TITLE
[Bug] Counters

### ISSUE THREAD

**Issue by DopingFish** [Eranziel/foundryvtt-lancer#152]
I'm unable to delete added counters

**Comment by Eranziel** [comment]
In the future please use the bug report template so that the issue gets set up correctly.

**Comment by Grygon** [comment]
I'm assuming it's specifically counters at a pilot level? I'm pretty sure I know what's going on there.

If it's counters that you try to add on an item itself, let me know as that's more unexpected.

**Comment by Grygon** [comment]
Fixed in v0.9.1
