### ISSUE TITLE
[BUG] Incorrect weapon listing

### ISSUE THREAD

**Issue by KingCarnival** [Eranziel/foundryvtt-lancer#154]
The weapon listing is incorrect on the Caliban licenses

![image](https://user-images.githubusercontent.com/12023995/115974128-29937c00-a520-11eb-99e4-aeee8defc611.png)

![image](https://user-images.githubusercontent.com/12023995/115974114-18e30600-a520-11eb-916b-262056e72d4a.png)

**Comment by Eranziel** [comment]
Can you provide some more details on what is incorrect? What do you expect to see?

**Comment by KingCarnival** [comment]
Sorry had to step away and posted so it wouldn't get lost.

Flayer and Cannibal are listed as Rifles and not CQB

**Comment by Grygon** [comment]
Can confirm the issue, probably related to profiles?
![image](https://user-images.githubusercontent.com/647846/115982594-17d2c880-a562-11eb-8672-317aa94e8735.png)

![image](https://user-images.githubusercontent.com/647846/115982603-25884e00-a562-11eb-97ea-0bf5166ec7d8.png)

**Comment by whitespine** [comment]
Fixed in MM .93

**Comment by Grygon** [comment]
Fixed in v0.9.1
