### ISSUE TITLE
[BUG] NPCs Can't Roll

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#157]
**Describe the bug**
NPCs can't roll attacks

**To Reproduce**
1. Roll an attack with an NPC 

**Expected behavior**
Attack to fire

**Screenshots**
![image](https://user-images.githubusercontent.com/647846/115982481-2076cf00-a561-11eb-91ee-e575f479e083.png)

**Platform (please complete the following information):**
N/A

**Comment by ScyllPoesis** [comment]
Was a bad path in the weapon macro looking for `tier_num`, which is now `tier`. Fixed in #158 .

**Comment by Grygon** [comment]
Fixed in v0.9.1
