### ISSUE TITLE
Show deployable owner on token.

### ISSUE THREAD

**Issue by Darkcloth** [Eranziel/foundryvtt-lancer#160]
To make it easier to get the scope of a battlefield and who controls what at a glance.

It'd be nice if you could show a small image of the token of whoever is controlling the deployable on the token, such as the status effect icons.

Alternatively I'm not sure. I doubt token tooltip alt could tap into that since that seems to only be numerical stuff but maybe that's an alternative there.

Darkcloth#1984

**Comment by ScyllPoesis** [comment]
I feel like using the icon of the deployer mech would be so small as to be unusable. Even if you were to use a quarter of the token's space, given how zoomed out a token img is (and usually padded, look at the actor directory icon for a taste), I feel it would require you to really zoom in to tell who it belongs to unless all your mechs have extremely distinctive colors or art.

To me the solution is to just have the deployable include the owner in the token name (something I believe WM already included with his latest commit), and then if you hit Alt to view the field it'll be clear that this is "Veteran Assault's Turret Drone" or "Rampaging Girth's Deployable Cover".

**Comment by msprijatelj** [comment]
Is this feature still worth keeping? The automation that ScyllPoesis mentioned is already part of the Lancer system.
