### ISSUE TITLE
[BUG] Macros don't respect roll privacy

### ISSUE THREAD

**Issue by ScyllPoesis** [Eranziel/foundryvtt-lancer#161]
**Describe the bug**
Automated chat messages such as our macros are always public and visible to all players. They should follow the chat dropdown (Public, Private GM, etc.) like standard rolls.
**To Reproduce**
1. Set roll privacy to Private GM.
2. Use an attack macro.
3. Login as a player and see the roll unobscured.

**Expected behavior**
Message to be hidden from player view according to chat mode selection.

**Additional context**
Should be simply setting a whisper to the GM in the chat message options, but I don't know what the appropriate method is. Can peek at MidiQOL and other smart rollers for a cheat.

**Comment by Eranziel** [comment]
We used to have this issue, was fixed in #66. The chat message type should be `CONST.CHAT_MESSAGE_TYPES.ROLL` to make Foundry obscure it when necessary. I don't see at a glance where we're missing that, will need to trace it through.

**Comment by ScyllPoesis** [comment]
Yeah, I looked into it a bit more and shouldn't be a hard task I'll take a look at this tomorrow during some downtime.

**Comment by ScyllPoesis** [comment]
Fixed and included in #159.

**Comment by Grygon** [comment]
Fixed in v0.9.1
