### ISSUE TITLE
[BUG] NPC Tech Actions Don't Roll

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#166]
**Describe the bug**
![image](https://user-images.githubusercontent.com/647846/116716205-1576d100-a99d-11eb-973f-a140d56d0467.png)

**Discord contact info**
Flint

**Comment by ScyllPoesis** [comment]
Fixed in #167, as well as added proper automation and structure. I also added some more improvements to collapses and refactored the player mech sheet Tech Attack over to use the same macro handler.

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
