### ISSUE TITLE
JS issue on attack effect text on chat. display

### ISSUE THREAD

**Issue by Berky115** [Eranziel/foundryvtt-lancer#169]
**Describe the bug**
While rolling an attack, the chat display for effect returned [Object object]. 

**To Reproduce**
Unsure was a bit of a one-off.

**Platform (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser: Chrome
 - Foundry version 0.7.9
 - Lancer system version .0.1.20
 
![Screen Shot 2021-05-03 at 9 22 01 PM](https://user-images.githubusercontent.com/2816819/116960850-7aa91b80-ac56-11eb-9439-47878f12157f.png)

![Screen Shot 2021-05-03 at 9 23 05 PM](https://user-images.githubusercontent.com/2816819/116960852-7b41b200-ac56-11eb-8944-1adb8ce97792.png)

**Comment by Grygon** [comment]
This is fixed in the v1.0 release, but I'll leave this issue until then for tracking purposes

**Comment by Grygon** [comment]
Nvm, closing - Fixed in 0.9.3
