### ISSUE TITLE
[BUG] Automation seems to be broken in 0.9.1

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#172]
**Describe the bug**
Automation of things like Overkill heat, critical damage keep-highest rolling and application of Accuracy/Difficulty for Accurate/Inaccurate weapons does not seem to be working in the 0.9.1 beta.

**To Reproduce**
1. Equip a weapon to a mech that is Inaccurate, Accurate or has Overkill.
2. Roll with this weapon (note whether the standard Accuracy/Difficulty from Inaccurate/Accurate is automatically applied in the Accuracy/Difficulty interface)
3. Repeat rolls until Overkill would be triggered (i.e. the damage dice rolls a 1) or a critical hit would be triggered (i.e. 20+ on the final attack result) and observe whether Overkill and critical hit keep-highest rolling occur

**Expected behavior**
In 0.1.20, if the correct automation options are enabled, and Overkill is triggered or a Critical Hit is achieved, Lancer VTT will automatically reroll dice as appropriate. Inaccurate weapons will automatically have 1 Difficulty applied in the Accuracy/Difficulty interface, and Accurate weapons will automatically have 1 Accuracy applied.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
