### ISSUE TITLE
[FEATURE] [0.9.1] Add a Grit roll option to mech sheets

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#173]
**Is your feature request related to a problem? Please describe.**
Previously, with integration of both mech and pilot into one sheet, there was a Grit roll option for when a mech needed to make an attack roll for something not based on a weapon like Improvised Melee, Grapple or Ram. With mech sheets now split from pilot sheets, it is no longer possible to make such a roll from a mech's sheet itself. Although this option still exists on the pilot sheet, it's more cumbersome to do things that way.

**Describe the solution you'd like**
Given that mech sheets still import data from a pilot sheet, add a Grit roll option to the mech sheet.

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
I'll toss this in here later
![image](https://user-images.githubusercontent.com/647846/117362300-b1fb1080-ae80-11eb-86cc-64651689b865.png)

**Comment by VexWerewolf** [comment]
If I might also request that NPCs have a similar button to make a Tier roll, that would be helpful, as NPCs sometimes make such a roll.

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
