### ISSUE TITLE
[BUG] [0.9.1] NPC class/template features not removed when removing associated class/template, allows duplication

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#174]
**Describe the bug**
Removing an NPC's class does not remove the features associated with that class as it previously did in 0.1.20. This causes a lot of overhead if you accidentally put the wrong class or template on the character. Additionally, because these features are not removed, re-applying the class or template will duplicate any features that have not been removed. This is particularly noticeable in relation to features that modify HP, structure or stress.

**To Reproduce**
1. Create an NPC.
2. Add a class (for this example, Goliath). Note whether the class features have populated into the Features section.
3. Remove the class. Note whether the class features have been removed.
4. Add the class again. Note whether the class features have been duplicated.
5. Add a template that affects stress, structure and/or HP. Note whether the NPC's stress, structure and/or HP have changed.
6. Remove the template. Note whether the template features have been removed, and whether the NPC's stress, structure and/or HP have returned to default.
7. Add the same template again.

**Expected behavior**
Removing a class or template should remove features associated with that class or template.

**Screenshots**
![NPC class features 1](https://user-images.githubusercontent.com/83786280/117370326-243e1600-aebe-11eb-8100-c66340405789.jpg)
![NPC class features 2](https://user-images.githubusercontent.com/83786280/117370329-24d6ac80-aebe-11eb-8475-b62ed1348dd3.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking

**Comment by VexWerewolf** [comment]
> 
> 
> Fixed on 0.9.4, closing for better tracking

Still seems to be present in 0.9.4?

**Comment by whitespine** [comment]
I'm investigating. But prior to re-resolving: Should optional features be likewise removed? I assume yes.

**Comment by VexWerewolf** [comment]
> 
> 
> I'm investigating. But prior to re-resolving: Should optional features be likewise removed? I assume yes.

That would probably be preferable, yes.

**Comment by Grygon** [comment]
Fixed in beta release for real this time, closing for better tracking
