### ISSUE TITLE
[BUG] [0.9.1] NPC features cannot be rearranged

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#176]
**Describe the bug**
Once NPC features have been placed into an NPC's sheet, they cannot be rearranged.

**To Reproduce**
1. Create a test NPC.
2. Add a class.
3. Attempt to drag the features around in the features section.

**Expected behavior**
In Lancer 0.1.20, NPC features could be rearranged.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Confirmed fixed in v1.0.0, closing
