### ISSUE TITLE
[BUG] [0.9.1] Systems that provide quick or full actions that are not distinctly named default to "New Action"

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#177]
**Describe the bug**
Under the new system you have for allowing quick, full and protocol actions to be taken directly from mech systems, systems that provide quick or full actions that do not have names distinct from the system that provide them usually have the action listed as "New Action."

I have made an attempt to list all the systems that have this issue, but please note that this _may_ not be exhaustive:
Accelerate
Aceso Stabilizer
Active Camouflage
Antilinear Time
Argonaut Shield
Auto-Cooler
Blinkshield
Blinkspace Tunneler
Cable Winch System
Caltrop Launcher
Charged Stake
Core Siphon
EMP Pulse
Enclave-Pattern Support Shield
External Ammo Feed
Eye of Horus
Fade Cloak
Ferrous Lash
Field-Approved, Brass-Ignorant Modifications
Final Secret
Flak Launcher
Forge Clamps
Hardlight Defense System
Hunter Lock
Hyperdense Armor
Interdiction Field
Javelin Rockets
LB/OC Cloaking Field
Lightning Generator
Magnetic Shield
Markerlight
Metahook
Monitor Module
Oasis Wall
PEBCAC
Plasma Gauntlet
RAMJET
Realspace Breach
Redundant Systems Upgrade
Repulser Field
Retractable PRofile
Seismic Ripper
Siege Stabilizers
Spaceborn EVA
Stasis Generator
Stay of Execution
Stuncrown
Swarm Body
Total Strength Suite I
Total Strength Suite II
Total Strength Suite III
Tracking Bug
Whitewash Sealant Spray

**To Reproduce**
1. Install one of the above listed systems
2. Note the name of the action that it allows you to take

**Expected behavior**
Honestly I'm not quite sure, but I would presume that in lieu of any other option, the name of the action should default to the name of the system?

**Screenshots**
![New Action](https://user-images.githubusercontent.com/83786280/117382992-ab4bb800-aed7-11eb-8ae2-201c825d1d8e.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.1.20

**Discord contact info**
Vex#1075

**Comment by whitespine** [comment]
What are peoples thoughts on simple "Activate <SYSTEM NAME>" as the default?

**Comment by Eranziel** [comment]
That sounds really good to me.

**Comment by VexWerewolf** [comment]
> 
> 
> What are peoples thoughts on simple "Activate " as the default?

I would prefer if it defaulted to the name of the system, actually. While I'm sure that it would usually be obvious by context, currently there is no information conveyed in the text box that pops up in the chat about what system is being activated.

![New Action 2](https://user-images.githubusercontent.com/83786280/123282727-ad5aec00-d502-11eb-859c-886383c0b6fa.jpg)

**Comment by Grygon** [comment]
Oddly, I see this fixed on the _compendium_ items but not on the items for the imported actor:
![image](https://user-images.githubusercontent.com/647846/125309378-55d8c080-e2f7-11eb-9e35-b82f457069bc.png)
![image](https://user-images.githubusercontent.com/647846/125309464-69842700-e2f7-11eb-9c33-621649385bef.png)

**Comment by whitespine** [comment]
@Grygon this is probably just a zombie item in the actors inventory getting re-equipped

**Comment by Grygon** [comment]
Yup you're right.

Issue fixed, closing.
