### ISSUE TITLE
[BUG] [0.9.1] Heatfall Coolant System does not prevent Overcharge heat cost from hitting 1d6+4

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#178]
**Describe the bug**
Heatfall Coolant System does not prevent Overcharge heat cost from hitting 1d6+4.

**To Reproduce**
1. Give a pilot the Heatfall Coolant System Core Bonus.
2. Assign a mech to this pilot.
3. Mash the Overcharge button at least four times.

**Expected behavior**
For the Overcharge to remain at 1d6 in perpetuity, no matter how many times I mash the Overcharge button.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Additional context**
Grygon told me that you're aware of this and that it is at least partially by design at the moment due to integration issues, but that I should lodge this as a bug report anyway.

**Discord contact info**
Vex#1075

**Comment by Eranziel** [comment]
Not currently in scope, adding to 1.1 milestone.
