### ISSUE TITLE
[BUG] [0.9.1] No local way to alter licence level of pilot

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#179]
**Describe the bug**
Once a licence level in a mech has been dragged and dropped into a pilot character sheet from the Compendium, there is no way to change its level. Adding the same licence level from the Compendium again will simply add another instance of the licence at level 1.

**To Reproduce**
1. Create a new pilot.
2. Drag and drop a licence from the Compendium.

**Expected behavior**
There should be some way of changing the level of a licence without importing from Comp/Con.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

**Comment by ScyllPoesis** [comment]
Went ahead and sniped this one as I was doing some work on the sheets to tinker around with things. I just added the same handler as the talents and triggers use, but all three sheets could use some cleaning up alongside the styling passes to come for the main actor sheets.

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
