### ISSUE TITLE
[BUG] [0.9.1] Mount type selection dropdown gets occluded 

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#180]
**Describe the bug**
In a mech sheet, there seems to be a layering issue with the weapon mount type dropdown menu. If it's at the bottom-most row, it will be occluded by the Mounted Systems bar as demonstrated in the screenshots, although sometimes it will open upwards and be occluded by the Mounted Weapons bar instead.

**To Reproduce**
1. Create a mech sheet
2. Add several weapon mounts.
2. Do not fill any of the weapon mounts.
3. Right click on the bottom-most weapon mount.

**Expected behavior**
The drop-down should be layered on top of other interface elements, such that if it overlaps with them, it is visible over top of them, rather than being hidden underneath.

**Screenshots**
![Setting Mount Type](https://user-images.githubusercontent.com/83786280/117457629-4fb61480-af41-11eb-8845-74ba44283143.jpg)
![setting mount type 2](https://user-images.githubusercontent.com/83786280/117457754-72e0c400-af41-11eb-8ff9-00d554469949.jpg)
![setting mount type 3](https://user-images.githubusercontent.com/83786280/117458124-d79c1e80-af41-11eb-8482-6c92aff81694.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1
 - 
**Discord contact info**
Vex#1075

**Comment by ScyllPoesis** [comment]
Issue wasn't a matter of layering, but rather a conflict with some CSS regarding the collapse system.

**Comment by whitespine** [comment]
If I had to guess its specifically either `overflow` or `clip` causing issues. New tooltip libraries should let us sidestep this (and make it look better to boot)

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
