### ISSUE TITLE
[FEATURE] [0.9.1] Put rank toggles on the character sheet itself

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#181]
**Is your feature request related to a problem? Please describe.**
![Skill Ranks etc](https://user-images.githubusercontent.com/83786280/117459536-6a898880-af43-11eb-9bf6-174bf0325142.jpg)

As the pilot sheet exists right now there is no way to alter the rank of a skill trigger or talent without diving into a separate window, which adds overhead for people working on sheets from within Foundry itself. This is a general usability concern which also comes up in #179.

**Describe the solution you'd like**
For ease of use, it would be good to place a rank toggle on the title bar of an Ability or Skill Trigger, such that it can be quickly edited without switching to another window.

**Describe alternatives you've considered**
I would assume that a lot of people will just import their characters straight from Comp/Con where the work has already been done, but it should be straightforward and easy to build a character sheet solely in Foundry without using Comp/Con as well.

**Discord contact info**
Vex#1075

**Comment by ScyllPoesis** [comment]
Jank coloring/styling of the edit sheet aside, is this really an issue? Ranks should not be changed frequently enough to need input fields on the sheet itself, and a single window open to edit during a level-up does not seem like a massive deal to me. We do have the real estate for it but the abilities tab to me seemed designed to be void of editing and purely an action table.

**Comment by Eranziel** [comment]
I think I agree with Scyll. Editing ranks on pilots should only happen every couple of sessions, so opening that item's sheet to edit shouldn't be a big deal. Real estate is at a premium already I feel.

Alternate idea: Foundry does support having an "edit mode" for sheets, so we could maybe use that for a sort of level up view. Thoughts? If that's something we want, I think it should wait til 1.1 or later.

**Comment by whitespine** [comment]
> Alternate idea: Foundry does support having an "edit mode" for sheets, so we could maybe use that for a sort of level up view. Thoughts? If that's something we want, I think it should wait til 1.1 or later.

It supports it insofar as sheets can have logic to show/hide editing controls, not via any specific edit mode mechanism afaik. Not saying its impossible, I just think its kind of a pain for little benefit.
