### ISSUE TITLE
[BUG] [0.9.1] Importing a pilot from Comp/Con dumps all associated mechs/deployables into the root actors folder

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#182]
**Describe the bug**
When using a comp/con code to import a pilot, regardless of what folder the pilot actor itself is in, their associated mechs and deployables will be placed in the root folder of the Actors Directory.

**To Reproduce**
1. Create a pilot in comp/con, preferably one with several mechs that have associated deployables
2. Create a pilot actor in Foundry, and place them in a folder
3. Use the pilot cloud code from comp/con to import the pilot
4. Observe where mechs and deployables associated with that pilot are generated

**Expected behavior**
Mechs and deployables associated with a pilot should be placed in the same folder as the pilot's actor.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
