### ISSUE TITLE
[BUG] [0.9.1] NPC current structure/stress always falls to 0 when closing a sheet

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#183]
**Describe the bug**
The editable value of current structure/stress on an NPC sheet does not seem to save, and will reset to 0 every time the sheet is closed and reopened. This issue also affects spawned token instances of NPC sheets.

**To Reproduce**
1. Create at least for test NPC. For completeness, create a couple, and make sure one has a template that affects its maximum structure/stress.
2. In the NPC sheet, change the current structure and/or stress values from 0 to something else.
3. Close the sheet.
4. Re-open the sheet.

**Expected behavior**
Ideally, NPC current structure/stress values should default to their current maximum, and when the value is altered by a player, that value should be saved and still present next time the sheet is opened.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

**Comment by ScyllPoesis** [comment]
Fixed in 0.9.2. This was still working correctly in the actor data, it's was just a path issue with the sheet that wasn't showing it correctly.
