### ISSUE TITLE
[BUG] [0.9.1] Superheavy weapons produce "weapon too large" error even in heavy mount

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#184]
**Describe the bug**
When a Superheavy weapon is placed in a Heavy mount, even if there is an unoccupied main mount available on the mech, the mech will display an error stating "WEAPON TOO LARGE TO FIT."

**To Reproduce**
1. Create a mech with the weapon mounts necessary to correctly equip a Superheavy Weapon (e.g. Everest, Tortuga, etc.)
2. Mount a superheavy weapon to the Heavy Mount, while leaving the Main mount free.

**Expected behavior**
I realise there probably isn't an automated function yet to make Superheavy weapons automatically occupy a Main Mount, or at least check if there's an unoccupied Main Mount, but this should be addressed at some point.

**Screenshots**
![Superheavy Weapons](https://user-images.githubusercontent.com/83786280/117472174-85aec500-af50-11eb-9fe0-ff6dc5ccd7ff.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

**Comment by ScyllPoesis** [comment]
Seeing new issue here with superheavies on current dev. @whitespine if you can take a look, when dragging a SH onto a slot it seems to successfully go through the loadout workflow and adds the item to the actor, but not to the loadout itself. I think the equip_weapon function may be looking for a SUPERHEAVY slot or something, dunno as can't see into the mind: `new_live_this.Loadout.equip_weapon(new_live_item);`

Notably this means that if there are issues in the equip part of that `mech-sheet` block, the actor could get flooded with a bunch of ghost items. Let us know if this is resolved in newer MM versions as I was testing this with `.94`.

**Comment by whitespine** [comment]
As of my most recent PR mechs shouldn't really be owning items anyways. After my next PR I'm going to take a hard look at our onDrop procedures as a whole - I think most of the logic there is outdated and volatile. (I'll also fix the superheavy thing, not to worry)

**Comment by Grygon** [comment]
Fixed with v0.9.5
