### ISSUE TITLE
[FEATURE] [0.9.1] Limited weapons have no box to track charges

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#185]
**Is your feature request related to a problem? Please describe.**
![Charges](https://user-images.githubusercontent.com/83786280/117512813-3f755800-af88-11eb-8746-5c9bae4408cb.jpg)

Systems with the Limited tag now come with a handy box to track remaining charges, but weapons with the Limited tag do not.

**Describe the solution you'd like**
I would like for weapons that have the Limited tag to have a handy box to track remaining charges.

**Discord contact info**
Vex#1075

**Comment by ScyllPoesis** [comment]
Limited and charged weapons are in 0.9.2.

**Comment by VexxMyst** [comment]
Weapons seem to be unaffected. Also, would like to suggest that the Solidcore be possibly handled by giving it a 4 charge counter and having its range/damage multiplied by the value?
![lanceractionthing](https://user-images.githubusercontent.com/74265604/117523895-c1fe1780-af88-11eb-915b-048f1faed6e6.PNG)

**Comment by ScyllPoesis** [comment]
Sorry, was the wrong terminology. By the above I meant support for LOADING, LIMITED and RECHARGE tags was implemented.

Weapons that have special states like the above will have to be handled on a case by case basis, which we're currently not working on as all our item data is currently generated from C/C dump. Once we have all the major features and workflow in expect to start adding annotation and metadata above stuff like this. That's when the complex interactions will get nice and smoothed out.

**Comment by whitespine** [comment]
Yeah, it should definitely be possible - counters are named, and we have full control over bonus formula. But it's a ways off - probably more sensible to just handle it like apoc-rail profiles

**Comment by ScyllPoesis** [comment]
Am unfamiliar with the way apoc-rail is handled but if we've got pre-existing example that's even better.

**Comment by Eranziel** [comment]
I agree that giving the Solidcore 4 profiles like the apocalypse rail is probably the best solution. Easy to do with a PR to lancer-data, and probably makes it easier to use in Comp/Con active mode too.

**Comment by VexxMyst** [comment]
I never looked at the Apoc Rail so I didn't know it had that implemented in both C/C and the system. Yeah, I'm all for that.

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
