### ISSUE TITLE
[FEATURE] [0.9.1] Quick reference for NPC features

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#186]
**Is your feature request related to a problem? Please describe.**
![NPC Class Features Quick Reference 2](https://user-images.githubusercontent.com/83786280/117514899-dd6b2180-af8c-11eb-8c1d-6fd641068294.jpg)
![NPC Class Features Quick Reference 1](https://user-images.githubusercontent.com/83786280/117514900-de9c4e80-af8c-11eb-99ac-fd21d85e6af9.jpg)

As things currently stand in the 0.9.1 NPC class compendium entry, you have to click on a class feature and pop out a new window to see what it does. This increases overhead for people making NPCs for their encounters.

**Describe the solution you'd like**
![NPC Class Features Quick Reference 3](https://user-images.githubusercontent.com/83786280/117515913-874bad80-af8f-11eb-9e36-0afec4e9cb5d.jpg)

If the features list in the NPC class compendium entry looked like it does for the class features once an NPC actually has them in their sheet (in a two-column arrangement) it would both improve usability and maintain interface consistency.

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Fixed, but going to leave it open for a bit longer to track a different issue I found: 
Importing an NPC Class wipes all associated Features

**Comment by whitespine** [comment]
> 
> 
> Fixed, but going to leave it open for a bit longer to track a different issue I found:
> Importing an NPC Class wipes all associated Features

It actually wipes any data from any item type, if you try other items. Will be fixed in my next MR

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
