### ISSUE TITLE
[FEATURE] [0.1.9] Add a way of designating a system as broken

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#187]
**Is your feature request related to a problem? Please describe.**
There is currently no way of marking a system as broken, e.g. due to structure damage or some other effect

**Describe the solution you'd like**
A way of marking a system as broken.

**Discord contact info**
Vex#1075

**Comment by ScyllPoesis** [comment]
Don't know if this was in 0.9.1 or stuck in our upcoming build, but right clicking the weapon icon currently toggles destroyed state. This should be added to a context menu for items in the next version or so for much better UX.

**Comment by VexWerewolf** [comment]
You're correct, although this doesn't work for systems.

**Comment by ScyllPoesis** [comment]
Fixed, now includes tooltips to let users know they can right click, and expanded to include both mech systems and NPC features.

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
