### ISSUE TITLE
[BUG] [Feature?] [0.9.2] AOE weapons don't place patterns; Pattern macros don't target characters

### ISSUE THREAD

**Issue by VexxMyst** [Eranziel/foundryvtt-lancer#190]
**Describe the bug**
There is no option to place a FVTT template when using a weapon with a pattern
Pattern macros have no function other than placing a template down.
These two in conjunction mean that the process for an AOE attack is to place a pattern, manually target characters in the template, then roll.

**To Reproduce**
1. Use a weapon that has an attack pattern.

1. Select an AOE pattern macro.
2. Place it so it covers a token.

**Expected behavior**
When the accuracy/difficulty popup appears, an checkbox appears that if selected, readies the appropriate template.
Placing a pattern macro targets any tokens in the template field.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.2

**Additional context**
Targeting may have an issue when it comes to friendly fire, possibly tie into Hostile/Friendly token designations?

**Discord contact info**
Vexxmyst#6669

**Comment by BoltsJ** [comment]
This is at least mostly fixed in #295. As for friendly fire, while the weapons that don't hit allies aren't configured, there is a way to have targeting skip tokens.

**Comment by Eranziel** [comment]
There are very few weapons that don't inflict friendly fire (veil rifle and Emperor bow?), and that property isn't encoded in the data structure currently. I think manual targetting tweaks are sufficient for those cases fir now.
