### ISSUE TITLE
[BUG] [0.9.2] Action Tracker persists between scenes

### ISSUE THREAD

**Issue by VexxMyst** [Eranziel/foundryvtt-lancer#195]
**Describe the bug**
When switching scenes while a token is selected, the action tracker isn't culled and remains on screen regardless of the same token being selected or even present in the scene.
In addition, selecting a token in the new scene changes the name in the tracker, but deselecting returns the name to the token that was active in the previous scene.

**To Reproduce**
1. Click on a token
2. Switch scenes
3. See the action tracker remaining on screen.

**Expected behavior**
When changing scenes, action trackers are culled.

**Screenshots**
![novenom](https://user-images.githubusercontent.com/74265604/117717320-a8d3b180-b1a8-11eb-8d49-58a48bd63834.PNG)

**Platform (please complete the following information):**
 - OS: wimdows 10
 - Foundry version 0.7.9
 - Lancer system version it's in the title

**Discord contact info**
VexxMyst#6669

**Comment by ScyllPoesis** [comment]
Fixed, was an error where the manager was indeed hiding correctly, but was attached to the wrong hook and seemed to have been generating extra copies (which were not hiding correctly). 

Also apparently hidden is not hidden thanks to some Application rendering weirdness, so fixed the bug where the manager would render on first load blank until you selected something.

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
