### ISSUE TITLE
[BUG] Compendium builder can be extremely slow 

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#196]
Only experienced this in a real environment, so still need to get a dev env set up to look into this.

It looks like in certain scenarios, the Compendium Manager may take forever (~3 items/s)

Assigning to myself, but wanted to make sure an issue was made

**Comment by whitespine** [comment]
I think this is the OpCtx + cache somehow thrashing

**Comment by Grygon** [comment]
Oddly, haven't been able to reproduce even in a real world.

I think the cache improvements might be a part of that? Just going to close this
