### ISSUE TITLE
[BUG] NPC(?) Weapons that do not deal damage cannot be rolled

### ISSUE THREAD

**Issue by The-E** [Eranziel/foundryvtt-lancer#197]
**Describe the bug**
Certain weapons, like the Scout NPC's Marker Rifle, do not open the roll dialog when clicked.

**To Reproduce**
1. Create a Scout NPC and place it on the map
2. Open the character sheet and make an attack roll with the Marker Rifle
4. The roll dialog does not open, and an error message is logged:
![image](https://user-images.githubusercontent.com/280879/118241577-9acdab80-b49c-11eb-9565-22ccc75bf97a.png)

**Expected behavior**
Scouts can use their paintball guns again

**Platform (please complete the following information):**
 - OS: Heroku host
 - Browser Edge
 - Foundry version 0.7.9
 - Lancer system version 0.9.2

**Discord contact info**
The_E#1047

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
