### ISSUE TITLE
[BUG] [0.9.2] Window Sizing Issues

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#199]
**Describe the bug**
There are some arrangement, sizing and column issues with weapons at certain window widths of an NPC character sheet.

**To Reproduce**
1. Create an NPC (I used Ace)
2. Add several systems, preferably weapons
3. Resize the window horizontally

**Expected behavior**

**Screenshots**
![Window Sizing Issues](https://user-images.githubusercontent.com/83786280/118339368-9347ea00-b510-11eb-88cf-5f779a6c7478.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.2

**Discord contact info**
Vex#1075

**Comment by VexWerewolf** [comment]
For some additional context, I'm using a 1920x1080 monitor and this issue occurs on the default size at which NPC windows are the first time you open them.

**Comment by Grygon** [comment]
Closing - Fixed in 0.9.3
