### ISSUE TITLE
[FEATURE] Hex Size >1 Built-in Support

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#20]
Investigate the possibility and feasibility of building support for hex token footprints for sizes above 1.

The API in general seems extensible enough that it should be possible. The larger question is how much work it would be.

**Comment by stbz** [comment]
Thought might be useful info:
Foundry dev commented on reddit some days ago that the issue exists but hasn't been prioritized.

Support polygonal borders for tokens in hex-grid scenes which are larger than size 1
https://gitlab.com/foundrynet/foundryvtt/-/issues/187

**Comment by Eranziel** [comment]
Thanks, that is useful. I'm hoping by the time this issue can be addressed in this system it's already done in Foundry stock. 

Alternatively, this functionality would probably be better as a system-agnostic module than as a built-in part of a system.

**Comment by Eranziel** [comment]
Handled by Ourobor's Hex Size Support module. A module is a better place to implement this functionality anyway.
