### ISSUE TITLE
[BUG][9.2] Improved Armament is not factored into the character sheet.

### ISSUE THREAD

**Issue by WakefieldLancer** [Eranziel/foundryvtt-lancer#201]
**Describe the bug**
Character has IMPROVED ARMAMENT core bonus but Comp/Con does not import that mount/weapons over to the character sheet.

**To Reproduce**
1: Create a pilot with Improved Armament Core Bonus
2: Add a weapon mount to the Improved Armament mount in C/C.
3: Sync pilot.

**Expected behavior**
Improved Armament would show up on the character sheet for the mech.

**Screenshots**
You may utilize 80a2bc45d3374ff8d63b9e77fe0831b8 share code to check on 9.2

**Platform (please complete the following information):**
 - Current Foundry build 0.7.9
 - Windows 10, latest updates.
 - 9.2

**Additional context**
It can be built manually using the sheet, so it's not outright required, unsure if it's a bug or just not supported, but seems like a bug.

**Discord contact info**
Wakefield#2890

**Comment by Grygon** [comment]
I don't think this is actually addressed in the item data anywhere, so we'll probably need to hard-code in logic for this in v1.1

**Comment by whitespine** [comment]
It's in the data, I just ignored it in MM because it was weird/a pain in the ass. Will get to it eventually.

**Comment by BoltsJ** [comment]
This is fixed for importing, so we want to wait until it also auto adds for manually built stuff to close this?
