### ISSUE TITLE
[BUG] [0.9.2] License preview does not open license when clicked

### ISSUE THREAD

**Issue by whitespine** [Eranziel/foundryvtt-lancer#207]
**Describe the bug**
Cannot open licenses via the license preview on licensed items

**To Reproduce**
1. Open any Frame
2. Click on the license (double, right, whatever)

**Expected behavior**
It should open

**Screenshots**
![image](https://user-images.githubusercontent.com/16845226/120120429-24eb6480-c16b-11eb-904a-6e8d5c4cc502.png)

**Platform (please complete the following information):**
 - OS: Win
 - Browser Firefox
 - Foundry version 0.8.5
 - Lancer system version Dev

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
