### ISSUE TITLE
[FEATURE] Consolidate License sheet logic to re-use existing previews, including weapon preview

### ISSUE THREAD

**Issue by whitespine** [Eranziel/foundryvtt-lancer#208]
**Is your feature request related to a problem? Please describe.**
Currently, it implements systems, but not frames and weapons. The systems view seems to just be a copy pasted variant of the system preview for the Mech sheet.

**Describe the solution you'd like**
Refactor the license sheet helpers to utilize existing code (DRY), and to accomodate weapons + frames, which are present in all frames.

**Describe alternatives you've considered**
No

**Additional context**
![image](https://user-images.githubusercontent.com/16845226/120120483-9c20f880-c16b-11eb-8e0f-658680e69d4f.png)
This looks pretty bad atm. Should do all or nothing.

**Comment by Grygon** [comment]
Closing--created a master issue to track all generic refview type requests in #228 to keep it simple
