### ISSUE TITLE
[BUG] Can't edit HP on tokens

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#210]
**Describe the bug**
Token resources use the derived HP values, which means we can't edit them from the token directly

**To Reproduce**
![image](https://user-images.githubusercontent.com/647846/120835505-051cbd80-c52a-11eb-82aa-8fc4720592a4.png)

**Platform (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Comment by VexWerewolf** [comment]
I was about to write a bug report about this - the values in the boxes you see when a token is selected are frozen and I can't change them. Is that the same issue?

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
