### ISSUE TITLE
The critical hits also double the flat damage

### ISSUE THREAD

**Issue by Ytilee** [Eranziel/foundryvtt-lancer#211]
![image](https://user-images.githubusercontent.com/1778770/120916949-dd099780-c6ac-11eb-8aba-0cc8d0b75014.png)
When using the macro of a weapon dealing flat damage (here the Andromeda Pattern Heavy Laser Rifle) if it crits the flat damage (here fire damage) is incorrectly doubled.
Damage dealt via dices is correctly handled.

**Comment by Eranziel** [comment]
Fixed on dev.

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
