### ISSUE TITLE
[BUG] [0.9.3] Overkill heat not automatically applied

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#212]
**Describe the bug**
When rolling a weapon with Overkill, it rolls the heat but does not apply it.

**To Reproduce**
1. Create a mech with an Overkill weapon
2. Roll attacks with it until you roll a 1
3. Observe that the mech's heat has not incremented.

**Expected behavior**
The mech's heat should increment due to Overkill.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
