### ISSUE TITLE
[BUG] [0.9.3] Adding status effects to a token sets its HP box to zero

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#213]
**Describe the bug**
When adding status effects to a token, the value in the HP box drops to zero.

**To Reproduce**
1. Create a token.
2. Click on it.
3. Add a status effect using the pop-up interface.

**Expected behavior**
Adding status effects should not affect the value in the HP box.

**Screenshots**
![Status effects 1](https://user-images.githubusercontent.com/83786280/120928648-6638c280-c6dd-11eb-9a00-81074d4113f3.jpg)
![Status effects 2](https://user-images.githubusercontent.com/83786280/120928649-6769ef80-c6dd-11eb-8894-17ed818f9f55.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
Vex#1075

**Comment by whitespine** [comment]
love toooo race condition

**Comment by VexWerewolf** [comment]
> 
> 
> love toooo race condition

Come again?

**Comment by Eranziel** [comment]
It's probably a race condition - two (or more) tasks running in parallel, but not coordinating which one finishes first. So sometimes the wrong one finishes first and causes problems. ;)

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
