### ISSUE TITLE
[BUG] [0.9.3] Overcharge throws an error

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#214]
**Describe the bug**
When pressing the overcharge roll button, Foundry throws an error stating "documentData is not iterable"

**To Reproduce**
1. Create a player mech
2. Roll Overcharge

**Expected behavior**
Overcharge heat should be rolled and applied to the mech's heat gauge.

**Screenshots**
![Overcharge](https://user-images.githubusercontent.com/83786280/120931279-c5500480-c6e8-11eb-88d1-d4e662eeced5.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
