### ISSUE TITLE
[FEATURE] Rename counters

### ISSUE THREAD

**Issue by whitespine** [Eranziel/foundryvtt-lancer#215]
**Is your feature request related to a problem? Please describe.**
You can't rename counters

**Describe the solution you'd like**
You should be able to rename counters

**Describe alternatives you've considered**
At least don't show the "New Counter"

**Additional context**
![image](https://user-images.githubusercontent.com/16845226/120940345-d0a42f80-c6ea-11eb-85cc-efc3dd01e845.png)
There's plenty of UI space here

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking

**Comment by sigfriedmcwild** [comment]
I'm still seeing this issue on 0.9.6

**Comment by Grygon** [comment]
Reopening, can confirm...

**Comment by Grygon** [comment]
Threw in a temporary patch at least to make the name point correctly, but could be worth re-visiting
