### ISSUE TITLE
[BUG] [0.9.3] The mech image import from Comp/Con no longer works

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#216]
**Describe the bug**
Importing from Comp/Con no longer pulls custom mech images and sets them as the mech's token image.

**To Reproduce**
1. Create a mech in COMP/CON with a custom mech image
2. Import this character via the import function

**Expected behavior**
The imported mech should have its associated image set as its token image.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.6.8
 - Lancer system version 0.9.3

**Discord contact info**
Vex#1075

**Comment by VexWerewolf** [comment]
Pilots also no longer get custom images imported.

**Comment by Grygon** [comment]
Fixed in 0.9.6
