### ISSUE TITLE
[BUG] [0.9.3] Can't add additional systems to NPCs

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#217]
**Describe the bug**
Dragging and dropping optional systems onto NPCs no longer seems to work. This seems to affect both the master character sheet of an NPC and its unlinked token duplicates.

**To Reproduce**
1. Create a new NPC.
2. Drag a class onto the NPC's character sheet (for this test, I used a Bombard).
3. Attempt to drag and drop optional systems from the same class onto the NPC's character sheet.
4. Attempt to drag and drop optional or core systems from a different class onto the NPC's character sheet.

**Expected behavior**
You should be able to add optional systems to NPCs.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
Vex#1075

**Comment by Eranziel** [comment]
Note that dragging NPC features from the compendium onto an NPC sheet does still add them correctly.

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
