### ISSUE TITLE
[BUG] Importing Item from Compendium wipes string data

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#219]
**Describe the bug**
After import:
![image](https://user-images.githubusercontent.com/647846/121129723-fddc0500-c7f2-11eb-9417-100330457e8d.png)

**To Reproduce**
Import an item

**Platform (please complete the following information):**
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Comment by whitespine** [comment]
This is, I think, the same bug as npc classes nuking all of their owned templates. Which I thought I fixed on master, but in any case have fixed on my upcoming branch.

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
