### ISSUE TITLE
[BUG] Non-Veteran Templates don't add Structure or Stress

### ISSUE THREAD

**Issue by VexxMyst** [Eranziel/foundryvtt-lancer#221]
**Describe the bug**
Adding the Elite or Ultra templates doesn't add extra Struct/Stress to an NPC. Veteran does, so it's not a problem across the board.

**To Reproduce**
1. Create NPC
2. Add Elite or Ultra Template
3. Observe Structure remaining at 1/1.

**Expected behavior**
Automatic increment of Structure.

**Platform (please complete the following information):**
 - OS: Win10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
It's Vexx. No, not that one.

**Comment by whitespine** [comment]
Believe I have this fixed in my branch. Was a race condition

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking

**Comment by VexxMyst** [comment]
![templateunfixed](https://user-images.githubusercontent.com/74265604/122317276-437f8880-ceeb-11eb-84c1-47cc9bd90176.gif)

**Comment by Grygon** [comment]
![image](https://user-images.githubusercontent.com/647846/122319473-49269f80-cee6-11eb-90a2-5204dd8c772f.png)

**Comment by VexxMyst** [comment]
a true rollercoaster and proof that issues may be plain user error.
