### ISSUE TITLE
[FEATURE] Allow users to edit/view/manage not-currently-equipped items on mechs (and pilots)

### ISSUE THREAD

**Issue by whitespine** [Eranziel/foundryvtt-lancer#223]
**Is your feature request related to a problem? Please describe.**
As it stands, items that are unequipped from a loadout are banished to the shadow realm. There is no way to view them, and they just sit around being weird and causing problems. Forces players to add new copies from compendium, which isn't ideal.

**Describe the solution you'd like**
An inventory popup which shows the content of the `OwnedMechWeapons` and similar arrays on the Mech character

**Describe alternatives you've considered**
We could also just permanently delete items when they're completely unequipped, but thats meh

**Additional context**

**Discord contact info**
If you are willing to answer questions regarding this feature request on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
e.g. Eranziel#1234

**Comment by Eranziel** [comment]
Inventory window was added some time ago. Closing.
