### ISSUE TITLE
[BUG] Calling destroy_entry on item embedded in token doesn't work well

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#224]
**Describe the bug**
Things that trigger destroy_entry on a token actor result in an error and inconsistent behavior.

**To Reproduce**
1. Create NPC with class
2. Create token from NPC
3. Attempt to delete class
4. Observe that the class didn't fully delete

**Expected behavior**
Should be handled seamlessly

**Screenshots**
![image](https://user-images.githubusercontent.com/647846/121838347-3d946800-cc9d-11eb-9995-8beb880dbbeb.png)
![image](https://user-images.githubusercontent.com/647846/121838367-47b66680-cc9d-11eb-935c-a387c038b409.png)

**Platform (please complete the following information):**
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Comment by whitespine** [comment]
Fixed in my branch

**Comment by Grygon** [comment]
Fixed on 0.9.4, closing for better tracking
