### ISSUE TITLE
[BUG] [0.9.4] NPC templates do not use the same drag/drop display as NPC classes

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#227]
**Describe the bug**
The NPC template reference still displays template features as links rather than the full text of the feature.

**To Reproduce**
1. Open an NPC class
2. Open an NPC template

**Expected behavior**
The NPC template reference should display what each feature does, as the NPC class reference now does.

**Screenshots**
![Template Features](https://user-images.githubusercontent.com/83786280/122327024-1fd93400-cf25-11eb-9730-fe05965a3754.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.7
 - Lancer system version 0.9.4

**Discord contact info**
Vex#1075

**Comment by Grygon** [comment]
Closing--created a master issue to track all generic refview (AKA "this still has a simple preview) type issues in #228
