### ISSUE TITLE
Heat-Dealing weapons Adding Heat to Token[FEATURE]

### ISSUE THREAD

**Issue by DMRaven** [Eranziel/foundryvtt-lancer#229]
**Is your feature request related to a problem? Please describe.**
No, this is an optional quality of life aspect that isn't a big deal.

**Describe the solution you'd like**
There are some mech weapons that add heat to the user when used. For example, the Pyro's Flamethrower or the PC Metalmark's Shock Knife. I would like for a roll of one of those weapons to apply the applicable heat to the token that used it.

**Describe alternatives you've considered**
There are already easy ways of adding heat to a token, so this is more of a mild improvement case.

**Additional context**
I have no additional notes to add.

**Discord contact info**
Demi_dad#4073

**Comment by DMRaven** [comment]
As a comment, some people have stated that this should already work in the Discord. However, I could not get it to show up when using the Pyro's Flamethrower or the Metalmark License's Shock Knife.

**Comment by Grygon** [comment]
I don't think it should be working right now, although you _could_ put together macros for it pretty quickly.

@whitespine thoughts on a MM helper function to do this?

**Comment by whitespine** [comment]
A get_heat function equivalent to current get_limited would probably make this trivial. I'll try to add it sometime soon, have guests over thru Monday at the very least

**Comment by Grygon** [comment]
No rush, meant to put this on v1.1

**Comment by Eranziel** [comment]
Fixed by #323.

**Comment by Grygon** [comment]
Fixed in 1.0.3, closing
