### ISSUE TITLE
[BUG] Weapons with the Loading Trait throw an error when being rolled

### ISSUE THREAD

**Issue by yoshisman8** [Eranziel/foundryvtt-lancer#230]
**Describe the bug**
Any weapon with the loading trait throws the following error on the console when you attempt to make an attack roll with them:
![image](https://user-images.githubusercontent.com/4214215/122677599-ffbda500-d1b0-11eb-8316-d9b6d4c37b59.png)
 

**Platform (please complete the following information):**
 - OS: Linux 
 - Browser Chrome
 - Foundry version 0.8.7
 - Lancer system version 0.9.4
 - 
**Discord contact info**
Vyklade#0001

**Comment by Grygon** [comment]
Fixed in beta release, closing for better tracking
