### ISSUE TITLE
[BUG] Default token Configuration does not work for NPCs.

### ISSUE THREAD

**Issue by Darkcloth** [Eranziel/foundryvtt-lancer#233]
In core settings, go to default core configuration and change display name for example, to always for everyone. When creating an NPC mech or deployable it remains on the default of "hovered by owner"

1. Go to core settings
2. Click on default token configuration
3. Set display name to always for everyone
4. Create a new NPC or deployable actor and place it onto the field
5. See error

Expected behavior
It should properly change the default token configuration

Specs
Foundry 0.8.7
Lancer 0.9.4

Darkcloth#1984

**Comment by whitespine** [comment]
Hmm. Prior to this point we did special options for different entity types (deployables would hide bars, etc).
Those options are overriding the foundry builtins, now. It would be trivial to fix, but do we want to get rid of everything? Or just certain bits?

**Comment by Darkcloth** [comment]
Well this is a personal opinion, and sorry for the late response but by lancer rules all NPC names/classes should be visible to everyone so you could make that the default. Alternatively just leave it so people can just override it how they like with the settings menu.

**Comment by whitespine** [comment]
It was more about hp bars, really. But I guess it is not a huge burden for the players to manually fix their tokens. The vast majority of tokens will be hostile npcs anyways.

**Comment by BoltsJ** [comment]
Imo, the system should only manage disposition, and actor linking settings.

**Comment by whitespine** [comment]
Ideally eventually token default settings will be configurable by actor type. Somewhat surprised that foundry's implementation doesn't do that already.

**Comment by Eranziel** [comment]
Fix implemented on `dev-1.0`, will be in next release. I kept our override for actor linking and disposition, everything else uses Foundry's defaults.
