### ISSUE TITLE
[BUG] NPC Notes not saving edits

### ISSUE THREAD

**Issue by Alkyama** [Eranziel/foundryvtt-lancer#234]
**Describe the bug**
Whenever I try to add a note to a NPC character sheet, it won't save to the sheet. 

**To Reproduce**
1. Create a NPC actor sheet.
2. Scroll down to the 'Notes' Section
3. Click on the 'edit' button
4. Write anything on the edit field.
5. Click on either 'save' buttons
4. See error on the character sheet.

**Expected behavior**
When I edit the note on the NPC character sheet, I expect it to reflect on the sheet, and be editable afterwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304929/123516284-ae5e5b80-d671-11eb-9ac9-b9243d83ef1e.png)
![image](https://user-images.githubusercontent.com/25304929/123516298-be763b00-d671-11eb-9e1f-2ead04663d40.png)
![image](https://user-images.githubusercontent.com/25304929/123516302-c6ce7600-d671-11eb-87a7-71e76d1b110a.png)

**Platform (please complete the following information):**
 - OS: MacOS X 11.4 (Big Sur)
 - Browser: Chrome 91.0.4472.114
 - Foundry version: v0.8.6 (tested on v0.8.7)
 - Lancer system version: v0.9.4

**Additional context**
Disabled all the mods and the behavior was the same. Running server on the Forge server hosting.
The Notes Section of the player actor sheet is working propperly, though.

**Discord contact info**
alkyama#2737

**Comment by whitespine** [comment]
Re-assigned to me since I fixed it without checking assignees whoops

**Comment by Grygon** [comment]
Fixed in beta release, closing for better tracking
