### ISSUE TITLE
[BUG] Empty Status and Conditions Compendium

### ISSUE THREAD

**Issue by Alkyama** [Eranziel/foundryvtt-lancer#235]
**Describe the bug**
_Status/Conditions_ Compendium has empty entries.

**To Reproduce**
1. Open 'Status/Conditions' Compendium
2. Click on any Compendium Entry
3. See the Error

**Expected behavior**
When I open the condition/status entry, I expect to see a description of the condition, like on Comp/Con.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304929/123523218-b1207700-d698-11eb-93c4-f86d51538a48.png)

**Platform (please complete the following information):**
 - OS: MacOS 11.4 (Big Sur)
 - Browser: Chrome 91.0.4472.114 
 - Foundry version: v0.8.7
 - Lancer system version v0.9.4

**Additional context**
N/A

**Discord contact info**
alkyama#2737

**Comment by Grygon** [comment]
Fixed in beta release, closing for better tracking
