### ISSUE TITLE
[BUG] Can't open Talent Compendium Entries

### ISSUE THREAD

**Issue by Alkyama** [Eranziel/foundryvtt-lancer#236]
**Describe the bug**
Whenever I try to open Talent Compendium entries, they won't open any modals, with the console reporting the error recorded on the screenshot below.

**To Reproduce**
1. Go to 'Compendiums' Section
2. Open the 'Talent' Compendium List
3. Click on 'Ace' Compendium Entry

**Expected behavior**
When I click on the talent compendium entry, I want it to open so I can read it.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304929/123523428-d2ce2e00-d699-11eb-84af-750a1718a1b4.png)

**Platform (please complete the following information):**
- OS: MacOS 11.4 (Big Sur)
- Browser: Chrome 91.0.4472.114
- Foundry version: v0.8.7
- Lancer system version v0.9.4

**Additional context**
Because of this, I cannot create the sheets with talents beyond the first tier of the talent without the aid of Comp/Con. The talents pulled directly from the compendium list will always create the first tier, even duplicating the existing entry.

**Discord contact info**
alkyama#2737

**Comment by Grygon** [comment]
Fixed in beta release, closing for better tracking
