### ISSUE TITLE
[FEATURE] Next release should have special migration step to delete defunct `derived` template data

### ISSUE THREAD

**Issue by whitespine** [Eranziel/foundryvtt-lancer#238]
**Is your feature request related to a problem? Please describe.**
Its in `_source`. It shouldn't be!

**Describe the solution you'd like**
Run `game.actors.contents.forEach(x => x.update({"data.-=derived": null}))`. It won't get active tokens, but that barely matters

**Describe alternatives you've considered**
no

**Discord contact info**
you know who i am

**Comment by Eranziel** [comment]
Handled in the 0.9 -> 1.0 migration code.
