### ISSUE TITLE
[FEATURE] Status/Condition Icons

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#24]
Bring status/condition icons into the system itself. Three sets to include: Hayley's and Cancermantis' from the lancer-conditions module, and the Comp/Con icons should be added as a third set of options.

**Comment by Miaradz** [comment]
Have you seen this one? https://www.reddit.com/r/LancerRPG/comments/hlfuwz/i_made_lancer_token_markers_for_roll20vtt_files/

**Comment by Eranziel** [comment]
I did, but thanks anyway!

**Comment by Eranziel** [comment]
Modifying the scope of this issue. The Comp/Con icons will be set as the default in the system. They additional sets from Discord will remain in Lancer Conditions for the time being.
