### ISSUE TITLE
[BUG] [0.9.4] Cannot open token configuration

### ISSUE THREAD

**Issue by VexxMyst** [Eranziel/foundryvtt-lancer#240]
**Describe the bug**
Neither the token Gear or (Prototype) Token buttons function.

**To Reproduce**
1. Open an existing or new world
2. Create an actor
3. Open sheet, click Prototype Token

**Expected behavior**
The standard config should open.

**Screenshots**
![token error](https://user-images.githubusercontent.com/74265604/124008254-3b731e80-d9aa-11eb-8e6f-3c3d04f9aff0.PNG)

**Platform (please complete the following information):**
 - OS: Win11
 - Foundry version 0.8.8
 - Lancer system version 0.9.4

**Additional context**
This error resulted both with and without modules, and a DND5e world had no issues opening the config, pointing to the system being the issue.

**Comment by Eranziel** [comment]
We released a hotfix for this bug a few hours after the initial release of 0.9.4. Can you re-download the beta via manifest and check whether you still experience the issue?

**Comment by VexxMyst** [comment]
Issue is fixed, was on the old version.
