### ISSUE TITLE
[BUG] Homebrew LCP Doesn't Import

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#242]
**Describe the bug**
This LCP doesn't import: [Waffenfabrik_Zalewski-1.0.2.zip](https://github.com/Eranziel/foundryvtt-lancer/files/6751476/Waffenfabrik_Zalewski-1.0.2.zip)

Errors in out MM: 
![image](https://user-images.githubusercontent.com/647846/124205821-a7877c80-daa7-11eb-82d7-6ed70bad0685.png)

Uploads just fine in C/C

**To Reproduce**
Try to import it

**Platform (please complete the following information):**
 - OS: Windows
 - Browser FF
 - Foundry version v0.8.8
 - Lancer system version dev-1.0

**Additional context**
Ping Duvalasur#2540 when this is fixed

@whitespine pls

**Comment by whitespine** [comment]
There are two format errors in this lcp, line 191 and 300 of the LCP systems.json.
`counters` should be an array.
Dunno why it works in compcon - have you tried actually deploying the WURTZITE SEEDING SYSTEM? I feel like that would probably manifest this bug then, as well.

**Comment by Grygon** [comment]
In that case, closing
