### ISSUE TITLE
[FEATURE] [0.9.4] Remove weapons/profiles wobbling text

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#243]
**Is your feature request related to a problem? Please describe.**
When you have weapons with charges, toggling between "1 charge" and "X charges" causes the text to spill onto two lines, which slightly raises or lowers text in the rest of the box.

![Charged Weapons 1](https://user-images.githubusercontent.com/83786280/124406778-285da700-dd3a-11eb-895a-5225bce48b01.jpg)
![Charged Weapons 2](https://user-images.githubusercontent.com/83786280/124406781-28f63d80-dd3a-11eb-8041-1a7efd4a244c.jpg)

**Describe the solution you'd like**
Text sizes or arrangement should be adjusted so the UI remains consistent.

**Describe alternatives you've considered**
I guess I could ignore it but this stuff just kinda bugs me.

**Discord contact info**
Vex#1075

**Comment by whitespine** [comment]
Solveable by simply removing `font-weight: bold` from css class `.weapon-profile.selected-profile`. However, that does remove the boldness... I think it should be fine as a temporary solution but obviously if we could find a way to make boldness not change wrapping behaviour that would be ideal.

**Comment by whitespine** [comment]
I think this is fixed? Re-open if I;m wrong
