### ISSUE TITLE
[BUG] Can't add mods to the GMS Shotgun

### ISSUE THREAD

**Issue by SohumB** [Eranziel/foundryvtt-lancer#247]
![image](https://user-images.githubusercontent.com/66472/125335066-a70aa380-e33b-11eb-94bc-b04b4e4075ed.png)

Clicking the + button next to Range on a GMS shotgun results in the following error:
![image](https://user-images.githubusercontent.com/66472/125335175-c86b8f80-e33b-11eb-903e-d6a27bb6edf9.png)

**Comment by whitespine** [comment]
Seems related to gen-controls "insert" parameter being bugged, shouldn't append [-1]

**Comment by Grygon** [comment]
Confirmed fixed in v1.0.0, closing
