### ISSUE TITLE
[BUG] Multiple instances of a weapon are linked on imported mech sheets

### ISSUE THREAD

**Issue by Azmahel** [Eranziel/foundryvtt-lancer#249]
**Describe the bug**
When a mech is created by importing form comp/con duplicate weapons seem to be linked, so if both are loading shooting one will unload all similar guns

**To Reproduce**
1. Import a character that has multiple of the same loading weapon equiped (69625479b00caa4217a423f9bcb265d6 for a 4 handcannon Raleigh)
2.  shoot one of the Hancannons
3.  all 4 of them are marked as "unloaded"

**Expected behavior**
only the gun used should be unloaded

**Platform (please complete the following information):**
 - OS:  windows
 - Browser: chrome
 - Foundry version: 0.8.6
 - Lancer system version: 0.9.5

**Comment by msprijatelj** [comment]
Coming in to confirm that this is still an issue; I imported a Raleigh today with 5 equipped Hand Cannons, and the resultant mech sheet had only 1 Hand Cannon in the inventory that was equipped to 5 different mounts.  All of them shared the same "Loaded" and "Destroyed" state.

**Comment by mason-bially** [comment]
This was fixed as of #409 (and for systems too)
