### ISSUE TITLE
[BUG] Importing actor onto a different actor duplicates items

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#251]
**Describe the bug**
Duplicating a pilot onto an existing pilot doesn't clear out their items to replace with their own, but instead appends,

**To Reproduce**
1. Import a pilot with skills
2. Import a 2nd pilot with skills
3. Observe that the resulting pilot has both sets of skills combined 
Note: applies to other things too, but that's the easiest example

**Expected behavior**
To match C/C loadout

**Screenshots**
![image](https://user-images.githubusercontent.com/647846/125723432-5eb03d38-2581-4968-932f-aee7e3731d73.png)

**Additional context**
@whitespine pls

**Comment by whitespine** [comment]
Was done this way to not delete custom made items - all importing is non-destructive currently.
I think this behavior might be fine, WITH A CHECKMARK TO ENABLE IT.

(just don't import to same pilot twice ;)

**Comment by Grygon** [comment]
Hmmmmmmmmmmm

![image](https://user-images.githubusercontent.com/647846/125724147-8a90d1f3-41d3-4eb8-b8e5-d8c323f8f29e.png)

**Comment by Eranziel** [comment]
To clarify the label dance, I labeled the wrong issue. I haven't done anything with this one.

**Comment by Eranziel** [comment]
That said, I can't duplicate on current `dev-1.0`. Skills added Foundry-side aren't removed when re-syncing, and re-syncing doesn't duplicate any skills.

Closing; if I'm in error please re-open.
