### ISSUE TITLE
[BUG] Reaction triggers aren't displayed.

### ISSUE THREAD

**Issue by BoltsJ** [Eranziel/foundryvtt-lancer#255]
**Describe the bug**
Reaction action don't show their trigger conditions.

**To Reproduce**
1. Add a system that provides a reaction to a mech
2. The effect of the reaction is shown, but not the triggering conditions

**Expected behavior**
Display the trigger conditions as well as the effects

**Screenshots**
![image](https://user-images.githubusercontent.com/182554/125884724-8dd425a5-5ae8-4298-8ab8-d9763bebe806.png)
![image](https://user-images.githubusercontent.com/182554/125884772-eb346962-eef5-4780-a953-322cc1581a81.png)

**Platform (please complete the following information):**
 - OS: Pop_OS 21.04
 - Browser firefox
 - Foundry version 0.8.8
 - Lancer system version 0.9.5

**Additional context**
It may be worth making the descriptions hidden or collapsible on the sheet as well.

**Discord contact info**
Bolts#9418

**Comment by Grygon** [comment]
Adding to PR #246

**Comment by Grygon** [comment]
Fixed in 0.9.6
