### ISSUE TITLE
[BUG] HP and heat constrained when changing from the token HUD

### ISSUE THREAD

**Issue by BoltsJ** [Eranziel/foundryvtt-lancer#256]
**Describe the bug**
When changing HP and heat values from the token hud, the value is constrained by the defined min and max. This is a regression from 0.1.20 where HP could go into the negative.

**To Reproduce**
1. Create a mech and assign a frame.
2. Deploy the token
3. Set the HP to 0 from the HUD
4. Subtract 1 HP from the HUD by typing `-1` in the box
5. Observe that the value goes to 0.

**Expected behavior**
HP should be able to go below 0 and heat should be able to go above the cap.

**Screenshots**
![image](https://user-images.githubusercontent.com/182554/125886530-d1cfeb7c-ba70-4312-b7a7-ac1669c22cbd.png)

**Platform (please complete the following information):**
 - OS: Pop_OS 21.04
 - Browser firefox
 - Foundry version 0.8.8
 - Lancer system version 0.9.5

**Additional context**
This issue happens with the Bar Braw Module enabled and the bar limits turned off there as well, so I beleive that the value is being reset somewhere else.

**Discord contact info**
Bolts#9418

**Comment by Grygon** [comment]
Fixed in 0.9.6
