### ISSUE TITLE
[BUG] Players lose control of templates placed via WeaponRangeTemplate

### ISSUE THREAD

**Issue by tskaiser** [Eranziel/foundryvtt-lancer#264]
**Describe the bug**
After placing a template using game.lancer.canvas.WeaponRangeTemplate.drawPreview the player loses control of that template.

This bug affects all the predefined AoE macros. The GM can still interact with and delete the templates after the fact.

**To Reproduce**
1. Give players permission to access one of the predefined AoE macros eg. Line 10
2. Have a player execute said macro
3. Have that player place the preview template (origin, angle)
4. After placement that player can no longer interact with the template (origin, angle, delete, etc)

**Expected behavior**
The one executing the macro should keep control of the template after placing it as if they had placed it using a measurement control.

For general usage in creating macros it would be ideal if this was an optional argument (eg. when calling fromRange, or as a setting on the created WeaponRangeTemplate object), defaulting to the above behaviour, such that control can be explicitly given to a specific user.

**Platform:**
 - OS: Windows 10
 - Browser: Desktop application + Chrome
 - Foundry version 0.8.8
 - Lancer system version 0.9.5

**Discord contact info**
TSKaiser#0096

**Comment by tskaiser** [comment]
### Workaround
After creating the WeaponRangeTemplate via eg. fromRange you can do
`template.data.update({ user: game.user.id });`
and the subsequent template will be assigned to the user executing the macro.

This has to be done before drawPreview() is called on the template.

I recommend this as the default behaviour, instead of having to use this workaround, but at least now it can be worked around 🙂

**Comment by Eranziel** [comment]
Looks like Bolts' recent additions have solved this.
