### ISSUE TITLE
[BUG] LCP not importing data into Compendium

### ISSUE THREAD

**Issue by dingbat91** [Eranziel/foundryvtt-lancer#266]
**Describe the bug**
I was testing a relatively simple LCP file, this simply adds a pilot weapon titled the "HHS-074 "Fixer" Shotgun" with Range 3, 5 Kinetic damage and the loading tag. It imports to Comp-con perfectly fine, however it does not import into the system. No errors are reported on the console log (That I could see)

**To Reproduce**
Create a new world with the lancer system.
Import Core data
Import [Trident.zip](https://github.com/Eranziel/foundryvtt-lancer/files/6908518/Trident.zip) as a LCP file (I've renamed it here for upload purposes)
See a successful upload, check pilot weapons compendium. See no equivalent weapon.

**Expected behavior**
The weapon to be added as a new item in the pilot weapon's section of the compendium. Matching the data in the LCP

**Screenshots**
**Comp Con Input:**
![image](https://user-images.githubusercontent.com/6049287/127675999-07de70e2-a076-4d0e-8fc3-6dd4a40d9c29.png)

**My Console log output:**
![image](https://user-images.githubusercontent.com/6049287/127676026-8881a32b-5997-45d0-bbc8-84ab52def65c.png)

**Platform (please complete the following information):**
Importing browser: Chrome 92.0.4515.107
Foundry Server: 0.8.8 on Docker Container
Lancer System: 0.9.5

**Additional context**
I tried removing the loading tag of the weapon to see if that tag caused issues. No luck with change.

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
e.g. Ding#5626

**Comment by dingbat91** [comment]
Problem found on my end:
In pilot_gear, line 5: Type was set to "weapon" and not "Weapon" 

Comp-con had no issue with case sensitivity, but Lancer did. Correcting it fixed the issue. 

Not closing this issue myself however, in case this case-sensitivity issue is something you want to manage.

**Comment by whitespine** [comment]
Seems like a fairly harmless/trivial correction for us to implement. I'll do it when I get the chance.

**Comment by whitespine** [comment]
Oh and by the way thank you for figuring out the issue yourself, haha. Much appreciated.

**Comment by whitespine** [comment]
(fixed in next MM release)

**Comment by whitespine** [comment]
Tempted to close because at this point we're on that release and I am pretty sure I tested this and it works? Wouldn't mind someone else giving it a try on curr dev.

**Comment by Eranziel** [comment]
Can confirm this is fixed on dev-1.0, so I'm closing it.
