### ISSUE TITLE
[FEATURE] Add Reserves to Pilot Sheet

### ISSUE THREAD

**Issue by DMRaven** [Eranziel/foundryvtt-lancer#268]
**Is your feature request related to a problem? Please describe.**
I like that Reserves currently exist as an item type. However, they cannot be added to pilot or mech sheets at the moment. 

**Describe the solution you'd like**
I'd like for there to be a Reserves section on the Pilot actor sheet. Preferably under Pilot//Tactical as that is where the other 'gear' is located. That section would then allow drag + drop from the compendium/item directory to the actor sheet. Additionally, it would be helpful to have an icon that links open the compendium like exists for NPC features.

**Describe alternatives you've considered**
I've been encouraging Players to track their reserves as notes on their Dossier.

**Additional context**

**Discord contact info**
If you are willing to answer questions regarding this feature request on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
Demi_Dad#4073

**Comment by Eranziel** [comment]
Complete at b1f668a4b6543bd4d68b623ad63c150a473691d8
