### ISSUE TITLE
[FEATURE] License data doesn't import from C/C

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#274]
![image](https://user-images.githubusercontent.com/647846/128953836-9468a1c3-a64f-4c7e-a41b-3993b74571be.png)
![image](https://user-images.githubusercontent.com/647846/128953847-50987811-063f-44a1-ba55-a9d8321440b8.png)

**Comment by Eranziel** [comment]
Not sure when this was added, but it's fixed in 1.0.
