### ISSUE TITLE
[FEATURE] Uses don't automatically deduct on items

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#275]
When a macro is used for an item with uses, it should deduct a use to keep it consistent with reloading--otherwise, we'll just cause confusion

**Comment by Grygon** [comment]
Addressing in #326

**Comment by msprijatelj** [comment]
This seems to be working for weapons and systems; clicking the Action or the Roll macro deducts a use as expected, and Full Repair replenishes all uses.
