### ISSUE TITLE
[BUG] Spacing between Dice Icon and Label on Macro Roll buttons

### ISSUE THREAD

**Issue by Alkyama** [Eranziel/foundryvtt-lancer#276]
**Describe the bug**
Destroy and Hull check buttons on the Structure macro has no spacing between the dice icon and the label.

**To Reproduce**
1. Select a player mech token.
2. Use "Structure Token" macro
3. When the result has a roll associated, the buttons will display with the behavior described

**Expected behavior**
The macro buttons with the dice icon having a little bit of spacing (margin / padding) in relation to the label.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304929/129121155-da8379f2-cd66-443b-a6b1-f72b2c4d4a8d.png)

**Platform (please complete the following information):**
 - OS: MacOS X Big Sur 11.5
 - Browser: Google Chrome V92.0.4515.131
 - Foundry version: v0.8.8
 - Lancer system version: v0.9.6

**Additional context**
Tested both without UI modules and using Ernie Modern's UI.

**Discord contact info**
alkyama#2737

**Comment by Eranziel** [comment]
Fixed on `dev-1.0`, will be in next release.
