### ISSUE TITLE
[BUG] Can't rename or delete weapon profiles

### ISSUE THREAD

**Issue by Alkyama** [Eranziel/foundryvtt-lancer#278]
**Describe the bug**
On _Mech Weapon_ sheets, when I add a _New Profile_ for a weapon, I have no controls to rename it, or deleting it.

**To Reproduce**
1. Create a new _Mech Weapon_ sheet on the item directory or edit a _Mech Weapon_ directly from a sheet.
2. Click on the '+' sign to add a new profile
3. Click on the New Profile.

**Expected behavior**
When I open a New Profile, I want to be able to see controls for me to rename or delete it, so I can better organize the weapon's profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304929/129122540-1ef54609-d016-4c6a-8c50-6c5f4f1dbc62.png)

**Platform (please complete the following information):**
 - OS: MacOS X Big Sur 11.5
 - Browser: Google Chrome V92.0.4515.131
 - Foundry version: v0.8.8
 - Lancer system version: v0.9.6

**Additional context**
- Was using profiles to add _Weapon Mods_ to the player's chosen weapon. Are _Weapon Mods_ working somehow?

**Discord contact info**
alkyama#2737

**Comment by Grygon** [comment]
> Are Weapon Mods working somehow

Yup, you should be able to drag & drop a mod onto a weapon just fine!

**Comment by Grygon** [comment]
Just tested... maybe that broke :( I'll double check and open an issue if so
