### ISSUE TITLE
[FEATURE] Show talent Actions and Reactions directly on the talent Entry on the Character Sheet.

### ISSUE THREAD

**Issue by Alkyama** [Eranziel/foundryvtt-lancer#280]
**Is your feature request related to a problem? Please describe.**
As of now if I want to see a talent's action or reaction, I need to double click any talent to see it's copy from the compendium, instead of doing it from the sheet.

**Describe the solution you'd like**
When I open the character sheet, I want to be able to select directly from the sheet the actions and reactions regarding my talents, even if not with the full description of it.

Also if possible, if I could have the actions and reactions from talents on the Token Action HUD, that would be awesome too.

**Describe alternatives you've considered**
Double clicking the talent shows me the action information I need, albeit having a few extra clicks to reach the information.

**Additional context**
- Screenshot of the issue:
![image](https://user-images.githubusercontent.com/25304929/129590644-c00bdb1b-8cbc-41ca-b465-42982579f076.png)

**Discord contact info**
alkyama#2737

**Comment by whitespine** [comment]
@Grygon now that you made mech tabbed, this should be trivial to just mirror between them, right? Just put some styling so people know it's just a reflrection of sorts
