### ISSUE TITLE
[FEATURE] Have Tech attacks, talents, & core bonus show what they do

### ISSUE THREAD

**Issue by yoshifanx** [Eranziel/foundryvtt-lancer#284]
So currently anything that isn't weapons doesn't display their text when rolling them (see attached)

![Tech text](https://user-images.githubusercontent.com/69432779/130331979-afe936d7-042b-4414-abef-b511835de6b5.png)

Having it display the text would be extremely helpful.

Thank you.

**Comment by Eranziel** [comment]
I think we can call this one closed.
