### ISSUE TITLE
[FEATURE] Add inactive mech management to pilot sheet

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#292]
**Is your feature request related to a problem? Please describe.**
Currently to swap in/out your active mech, you need to be able to drag/drop from the sidebar which isn't necessarily a given. Also, it's messy.

**Describe the solution you'd like**
On import we have the necessary info to create an InactiveMechs array on the Pilot--so we should do so. Once that's populated, it would be pretty trivial to add the necessary UI around that to let players manage that on sheets.
Drop can add a mech to InactiveMechs if it isn't already present
@whitespine sound feasible for MM?

**Comment by whitespine** [comment]
Due to fragility of 2 way binding I would prefer we not have pilots track owned mechs. That can readily be deduced simply by looking at all mechs and finding which match the pilot!

Such a call already exists (I believe as await pilot.Mechs()) but I could probably look into making it more efficient for frequent calls.

**Comment by Grygon** [comment]
So there is!

Looking at all mechs seems inefficient but if we have a function I can start there and see how bad it is...

**Comment by Grygon** [comment]
So the issue (which we've run into before) is that since that loads async, we can't actually use any of that data with Handlebars. We could do some post-load stuff, but that's messy...

The best solution might be an external Dialog that handles editing mechs? That sorta sucks though.

**Comment by BoltsJ** [comment]
`return game.actors.filter(a => a.is_mech() && a.data.data.pilot.id === this.id)` should get mechs assigned to a pilot synchronously outside of MM. This should have good performance unless there's hundreds of mechs, but in that case foundry is going to chug regardless.

**Comment by whitespine** [comment]
You can just await the async data into the getData call for the sheet, no? In hindsight I regret ever trying to support the compendium in machine mind - async workflows just aren't supported in foundry, really.

**Comment by BoltsJ** [comment]
Fair point, yeah. getData is awaited in the sheet render workflow, so it can be a promise.
