### ISSUE TITLE
[BUG] CORS errors on Comp/Con generated mech tokens

### ISSUE THREAD

**Issue by Argonius-Angelus** [Eranziel/foundryvtt-lancer#300]
**Describe the bug**
Tokens using Amazon AWS URLS for their token icon (default behaviour when generating mechs through Comp/Con import) causes a CORS error whenever the token needs to be rendered once more (placing onto field, dragging, dropping).

**To Reproduce**
This seems to be unpredictable as to whether or not this can be replicated, as a few others weren't having this issue. However, for me it was the following:
1. Ensure you're running a locally hosted Foundry instance on 0.8.9 (either Electron or NodeJS seems to be fine to reproduce this). There is no SSL or AWS configured. There is no nginx configured for the NodeJS version.
2. Create a new LANCER World with no add-on modules enabled.
3. Import a mech that uses Comp/Con artwork (basically any mech with default artwork).
4. Generate its token by dragging the actor onto a scene.
5. If it generates a mystery-man.svg instead of matching token artwork, check the console logs.
6. This also causes other issues as "this.icon" is undefined when using the fallback.

**Expected behavior**
With the current implementation, it should display the same art for the token as displayed on the sheet. For some reason the sheet is fine when it comes to CORS policies, but tokens are not.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox, Chrome, Electron App
 - Foundry version: 0.8.9
 - Lancer system version: 1.0.0

**Additional context**
The error messages seem to be purely constrained to Foundry itself, rather than the Lancer system itself. However, if possible, it might be safer to set the Prototype Token to being "mystery-man.svg" instead of trying to deal with CORS issues.

`Failed to load texture https://compcon-image-assets.s3.amazonaws.com/frames/mf_standard_pattern_i_everest.png: CORS failure foundry.js:35746:13
    loadTexture foundry.js:35746
    draw foundry.js:44999
    _onCreate foundry.js:45893
    _onCreate foundry.js:8500
    callback foundry.js:8765
    documents foundry.js:8747
    _handleCreateEmbeddedDocuments foundry.js:8747
    activateSocketListeners foundry.js:8550
    emit index.js:145
    value typed-events.js:46
    value socket.js:270
    value socket.js:257
    value socket.js:222
    emit index.js:145
    value typed-events.js:59
    value manager.js:214
    emit index.js:145
    value index.js:120
    value manager.js:206
    emit index.js:145
    value socket.js:416
    emit index.js:145
    value transport.js:107
    value transport.js:100
    onmessage websocket.js:112
`

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
`[REDACTED]#0001`

**Comment by BoltsJ** [comment]
Ref #312
