### ISSUE TITLE
[BUG] Creating new pilot actor inherited traits of existing pilot actor, despite different Comp/Con codes used

### ISSUE THREAD

**Issue by CosmiCadet** [Eranziel/foundryvtt-lancer#306]
**Describe the bug**
Creating a new character using Comp/Con code/cloud inherited some traits from a different, already created character rather than those particular to the code.

**To Reproduce**
Steps to reproduce the behavior: (this is how it happened, it's not reliably reproduceable)
1. One player creates a character using Comp/Con code/cloud.
2. Second player also creates a character using Comp/Con code/cloud.
3. Second character's Mech Stats and Pilot Talents are those of first character, but mech name and loadout are normal.

**Expected behavior**
New character would load on new sheet with its own stuff and not inherit things from a totally different code.

**Screenshots**
LBW1 - character inheriting talents from a different sheet.
LBW2 - what the character should have had (after we deleted first attempt and retried the loading).

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Firefox  (for player who had the issue)
 - Foundry version: 0.8.9
 - Lancer system version: 1.0.0

**Discord contact info**
Kee#3883
![LBW1](https://user-images.githubusercontent.com/68166208/131861881-0b49c17e-ce54-4524-a11c-65e58c52f683.png)
![LBW2](https://user-images.githubusercontent.com/68166208/131861888-40f52637-507d-4be1-b208-36bf76eb4542.png)

**Comment by Eranziel** [comment]
This was likely due to growing pains with Comp/Con import that have been fixed. Haven't had any recent reports of a similar nature, so closing this.
