### ISSUE TITLE
[BUG] Formorian Frame core bonus upgrades size ½ mechs to size 1.5

### ISSUE THREAD

**Issue by BoltsJ** [Eranziel/foundryvtt-lancer#309]
**Describe the bug**
When Fomorian Frame upgrades size, it just adds 1, so since size ½ mech have a size field of `0.5` it goes to `1.5`

**To Reproduce**
1. Create a pilot with the Formorian Frame core bonus
2. Create a mech with a size ½ frame
3. Assign the mech to the pilot
4. The size field on the sheet doesn't show and the actor is considered size 1.5

**Expected behavior**
Size ½ mechs should upgrade to size 1

**Screenshots**
![image](https://user-images.githubusercontent.com/182554/131965303-4225c09f-02ed-4a0d-8ffa-d03c6bb4166a.png)

**Platform (please complete the following information):**
 - OS: Pop_OS 20.10
 - Browser Firefox
 - Foundry version 0.8.9
 - Lancer system version 1.0.0
 
**Additional context**
The image for size ½ also seems to not display

**Discord contact info**
Bolts#9418

**Comment by whitespine** [comment]
Should be fixed in next MM
