### ISSUE TITLE
[BUG] Prototype Tokens are reverting to MysteryMan after reloading World

### ISSUE THREAD

**Issue by Miaradz** [Eranziel/foundryvtt-lancer#32]
On closing and re-entering a world running the Lancer system, tokens generated from Actor sidebar are reverting to the mysteryman icon. All other attributes are preserved.

Hex Size Support Module was used initially. Problem persists even when module is removed.

**Comment by Eranziel** [comment]
Found the problem, this will be fixed in 0.1. Thanks!

**Comment by Grygon** [comment]
Closing since issue is fixed in v0.1 (out soon!)
