### ISSUE TITLE
[BUG] Engineering skill incorrectly gives bonus uses to pilot gear.

### ISSUE THREAD

**Issue by Alexcasey64** [Eranziel/foundryvtt-lancer#324]
**Describe the bug**

Engineering in Pilot//Tactical gives bonuses to limited equipment uses in Pilot//Narrative

**To Reproduce**
1. Go to Pilot tactical
2. Increase engineering level to an even number
3. See limited use item gaining charges as if it were mech equipment

**Expected behavior**
That to not happen

**Screenshots**
![image](https://user-images.githubusercontent.com/90571301/132997225-5e90705f-e214-4b9c-b57f-94d1030c5713.png)

![image](https://user-images.githubusercontent.com/90571301/132997234-4a2ecea2-f169-4e9c-b15b-d3afbddce569.png)

![image](https://user-images.githubusercontent.com/90571301/132997246-ef862609-e2ac-4c4d-b4c6-e99968caaafe.png)

![image](https://user-images.githubusercontent.com/90571301/132997262-98d6d9af-4523-4767-bf13-03753a3757d0.png)

**Platform (please complete the following information):**
 - OS: windows 10
 - Browser Chrome, but persistent on host PC and other players
 - Foundry version 0.8.9
 - Lancer system version 1.0.2

**Additional context**
N/A

**Discord contact info**
Maccasey66#1347

**Comment by Davis-K-Johnson** [comment]
Just checked and engineering is correctly increasing mech systems but not affecting pilots.

OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0
