### ISSUE TITLE
[FEATURE] Generate Pre-Built NPC When NPC Class Imported

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#328]
**Is your feature request related to a problem? Please describe.**
People keep asking where to find NPCs after importing them, since the "NPC" compendium is at the top and it's empty for core NPCs at least.

**Describe the solution you'd like**
It would be nice to populate that compendium with a "standard" NPC of each class that exists in the NPC Class compendium whenever that changes. Especially now that we have default tokens, those could theoretically be pretty much ready to go for GM use.

**Describe alternatives you've considered**
Leave it as is--nah

**Additional context**
I could handle it--and maybe it doesn't even need to be on Import, just on NPC Class Compendium change? As long as that's done properly it may be the better route.

**Comment by Eranziel** [comment]
Finished!
