### ISSUE TITLE
[BUG] Compcon cloud import has caching issues

### ISSUE THREAD

**Issue by toadchild** [Eranziel/foundryvtt-lancer#334]
**Describe the bug**

When repeatedly importing a character from compcon cloud, it will only go to the server once. Subsequent fetches will pull data from the browser cache instead. (Tested with Chrome 93.0.4577.82) and module 1.0.1.

**To Reproduce**
1. Open character sheet on foundry
2. Use cloud import to pull in the character
3. Character shows same as compcon
4. Edit character in compcon
5. Manually export character from compcon
6. Import character from foundry
7. Update is missing
8. Clear browser cache (not cookies or history; just cache)
9. Import character from foundry
10. Data is up to date

**Expected behavior**
The fresh data should have been fetched without a manual cache clear being required.

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Chrome 93.0.4577.82
 - Foundry version 0.8.9
 - Lancer system version 1.0.1

**Comment by Eranziel** [comment]
This has nothing to do with your issue - hi toadchild! I used to play Infinity and got a lot of use out of your token maker and of course your dice app, thanks for your work on those! Hope you're enjoying this system. ;)

**Comment by SohumB** [comment]
Thanks for the detailed investigation! I believe we've actually fixed this in #331 (https://github.com/Eranziel/foundryvtt-lancer/commit/ac595b4b61d34af52f2b1653e1b47608e249ae7a), which is due to make it to a release this week. Can I ask you to check again after the new release?

**Comment by Grygon** [comment]
With 1.0.3 out, would you mind testing again to confirm?

**Comment by toadchild** [comment]
Everything looks correct to me now, thanks!
