### ISSUE TITLE
[BUG] Syncing pilots unconditionally overwrites some images

### ISSUE THREAD

**Issue by BoltsJ** [Eranziel/foundryvtt-lancer#335]
**Describe the bug**
When syncing a pilot from Comp/Con, the portrait from comp/con is written to the pilot actor as the portrait and token image, even if they've been customized. Additionally, mech token images are unconditionally set to the mech portrait image, even if they have have been set to different images.

**To Reproduce**
1. Create and import a pilot
2. Set a custom portrait and token image for the pilot. Set a custom image for the mech token only.
3. Sync the pilot.
4. The pilot portrait and token image are set from comp/con. The mech token image is set to the mech actor portrait.

**Expected behavior**
Customized images should not be overwritten.

**Screenshots**
https://images-ext-1.discordapp.net/external/OehkxYFgGTC72nbdXjbkoYhY3yTooKD7b0Oq8UxldzY/https/i.imgur.com/J0zCtuy.png?width=1203&height=658
https://images-ext-2.discordapp.net/external/GSGMHf4rlyl9srT_FgMjFjs_USekZb45rsWQfPp7pDY/https/i.imgur.com/rXanSTd.png?width=1203&height=658
https://images-ext-2.discordapp.net/external/h3Wx81LFjrcRW7XSHmLup4XwO97y_7R5B5YqLxDPg8w/https/i.imgur.com/eFCWsGU.png?width=1203&height=658

**Platform (please complete the following information):**
 - OS: Windows, Pop_OS
 - Browser Electron app
 - Foundry version 0.8.9
 - Lancer system version 1.0.2

**Additional context**
https://discord.com/channels/426286410496999425/890286216417783808/890286758284111932

**Workaround**
Mech images getting overwritten can be worked around by setting the mech portrait to the desired token image.

**Comment by BoltsJ** [comment]
Ref #337

**Comment by msprijatelj** [comment]
@Eranziel Tested this one out on Lancer v1.1.0; looks like it's been fixed!
