### ISSUE TITLE
[BUG] Integrated Weapons Can't be Modified

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#338]
**Describe the bug**
Integrated weapons on mechs that have a new frame assigned to them can't be modified (e.g. change Loaded, edit stats, etc.), as if it were directly referencing the compendium item.

**To Reproduce**
1. Create a new mech
2. Assign a Frame with an integrated weapon (e.g. Barbarossa, Raleigh)
3. Attempt to modify the integrated weapon (e.g. Mark as Destroyed, even use the Full Repair macro)
4. Foundry throws an error: `You may not modify the world.mech_weapon Compendium which is currently locked.`
5. Attempt to Edit the integrated weapon
6. Observe the options to change are greyed out and locked (and "Import" is in the top right corner)

**Expected behavior**
Adding a frame to a mech creates an instance of the integrated weapon, not a reference to the Compendium item (if the Compendium item is subsequently unlocked somehow, modifying it from a Mech sheet also seems undesirable).

**Screenshots**
Attempting to Edit the M35 Mjolnir:
![image](https://user-images.githubusercontent.com/44978587/134529506-74e31235-1039-413c-8e33-56ff69b32927.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Foundry version 0.8.9
 - Lancer system version 1.0.3

**Additional context**
This seems to also cause the Full Repair macro fail, as it's probably trying to modify the integrated weapon.

EDIT: This error doesn't occur when drag-and-dropping a weapon from the compendium; in that case, it instantiates the weapon as expected.

**Discord contact info**
Valkyrion#6196

**Comment by Eranziel** [comment]
This appears to be fixed now.

**Comment by msprijatelj** [comment]
@Eranziel After the update to Lancer v1.1.0, I'm seeing that this error still happens when directly dragging the Frame from the Compendium.  An instantiated weapon still appears in the mech inventory, with its own state, but the auto-equipped integrated weapon is still compendium-locked.

The good news is that it's equipping correctly when importing mechs directly from CompCon; I imported a Raleigh without this issue on its Mjolnir.

**Comment by Eranziel** [comment]
Okay, I'll reopen. I believe I tested by importing a pilot with a relevant frame (Caliban), but I didn't try dragging the frame directly.

**Comment by Davis-K-Johnson** [comment]
I just tested this by dragging the frame directly onto the sheet. It's fixed there too.

OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0
