### ISSUE TITLE
[BUG] Overheat macro rolls stress over incorrectly

### ISSUE THREAD

**Issue by sirbayer** [Eranziel/foundryvtt-lancer#341]
**Describe the bug**
The overheat macro incorrectly rolls stress over, causing more heat to be present than should be.

**To Reproduce**
1. Create an NPC.
2. Add the Archer class.
3. Add the Veteran template.
4. Set the Heat to 9.
5. Roll the overheat macro.
6. Observe that the NPC's new heat is 1.

**Expected behavior**
The NPC's new heat should be 0.

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 92.0
 - Foundry version: 0.8.9
 - Lancer system version: 1.0.3

**Discord contact info**
Maersk Aerospace#6777

**Comment by BoltsJ** [comment]
The 1 heat left over is actually the correct behavior according to Tom.

https://discord.com/channels/426286410496999425/760966283545673730/789297842228297748
![image](https://user-images.githubusercontent.com/182554/134719969-2ac25e84-da15-4e6a-942a-af083e0cc260.png)

**Comment by sirbayer** [comment]
Oh. I was told we had seen the opposite before, but this has receipts. Okay, this can go in the trash.

**Comment by BoltsJ** [comment]
Yeah, it's also the same as what comp/con does.
