### ISSUE TITLE
[BUG] Flex mounts can sync with extra Aux

### ISSUE THREAD

**Issue by Ashgar225** [Eranziel/foundryvtt-lancer#345]
**Describe the bug**
When syncing a mech from comp/con, a mech with a flex mount (with a main equipped) may come over with an extra aux if the mech in comp/con previously had aux/aux before being changed.

**To Reproduce**
1. Add two aux weapons to a mount in Comp/Con
2. Delete the first weapon, leaving the mount listed as "empty"
3. Add a main weapon
4. Sync with Foundry

**Expected behavior**
The "invisible" aux weapon in this case should not appear in the flex mount.

**Screenshots**
![Foundry Import Results](https://cdn.discordapp.com/attachments/594257637567102976/892916021067939860/unknown.png)

**Platform (please complete the following information):**
 - OS: Windows 10/11
 - Browser: Edge
 - Foundry version: 0.8.9
 - Lancer system version: 1.0.3

**Additional context**
Vault code for above pilot:
990124AE-8316-44FD-8CC4-6D190F6D7A95//65116F12-5A67-4685-8FD7-9231E62448AE

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
`Ashgar#0225`

**Comment by toadchild** [comment]
If you try:

1. Put two aux weapons on a flex mount in compcon
2. Delete the first one, causing compcon to show the mount as empty
3. Sync to foundry

Do you see the second ghost aux weapon show up instead of an empty mount?

**Comment by Eranziel** [comment]
Should be fixed in Comp/Con, so I'm closing this issue.
