### ISSUE TITLE
[BUG] Unable to edit weapon on hit or other effects 

### ISSUE THREAD

**Issue by peachez33** [Eranziel/foundryvtt-lancer#346]
**Describe the bug**
Unable to change a weapon's On Attack or On Hit effects. 

**To Reproduce**
1. Open weapon item
2. Click edit 

**Expected behavior**
Being able to alter the text for On Attack or On Hit effects. 

**Screenshots**

**Comment by Eranziel** [comment]
Related to #362, fixed by a6e5dae6c11c3f52d9dcd41617adceb7868fc209.
