### ISSUE TITLE
[FEATURE] Pilots have no sensors or save target

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#350]
**Is your feature request related to a problem? Please describe.**
Pilot actors do not have a sensors or save target value, which would be valuable for reference.

**Describe the solution you'd like**
I think machine-mind should add sensors and save target to the `data.derived` object. Consensus is that pilots have a save target 10, relevant for some pilot gear such as frag grenades. Pilots technically do not have a sensor range, but they can perform the Search action with a range of 5. Since this is the only thing that sensors would be relevant to for pilots, I think that's a good case to give them a default sensors of 5.

**Describe alternatives you've considered**
Just ignore pilot sensors and save target, i.e. current state.

**Comment by Eranziel** [comment]
We should definitely keep the property name the same on all actors. Is there an issue with `SensorRange`? I didn't mean to suggest that we should change the property name, just pointing out that Pilot actors lack these two properties entirely. Apologies for being unspecific in the description!

**Comment by Eranziel** [comment]
I see the confusion now. I'm not sure that they need to be copied into `derived` if they already exist in `derived.mm`, DRY is a good practice. 😉 I wrote this issue from memory without checking the data structure, my bad.

**Comment by msprijatelj** [comment]
Oh hey, @Eranziel this got addressed recently yeah?

**Comment by Eranziel** [comment]
Yup, closed in #598.
