### ISSUE TITLE
[BUG] NPC Features - Text Macros don't consume charge

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#352]
**Describe the bug**
When a text macro for an NPC feature with the recharge tag is used, it does not mark the feature as discharged.

**To Reproduce**
Add a non-attacking recharge 
1. Create an NPC actor and add the Hive class
2. Click the text macro button on Razor Swarms
3. Feature is not marked as discharged.

**Expected behavior**
Using text macros should consume charge.

**Comment by msprijatelj** [comment]
My take on this: On the Mech sheet, having the Text Macro be a separate macro from the Action macro is useful for sharing what an effect does without triggering a "use".  If a similar pattern could be followed for NPC features, that could prove convenient for GMs/NPC users for sharing information in a piecemeal fashion without toggling a use.  

Granted, I know NPC data is structured differently from Mech data, so these actions may not even exist; they seem to mostly exist only as tags.  Following this pattern may also be easier after CompCon's GM toolkit update.

**Comment by mason-bially** [comment]
This should also come as a consequence of #374 but I'll double check this now.

**Comment by Davis-K-Johnson** [comment]
Just checked with Defense Net, Hardlight Cover System, and Covering Fire. This seems to be working as intended now.

OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0
