### ISSUE TITLE
[BUG] Issue when adding Tags from Compendium to New/Custom items

### ISSUE THREAD

**Issue by SpaceCadetSiege** [Eranziel/foundryvtt-lancer#356]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Items in Foundry
2. Create new item, types with the issue were mech_system and mech_weapon
3. Drag tags from Tag subfolder in Item Compendium to the Tags section under the new Item Sheet

**Expected behavior**
To be able to drag the tags under/near the TAGS section of the sheet and have them appear there.

**Screenshots**
From this point onwards, there's a few screenshots there. https://discord.com/channels/426286410496999425/760966283545673730/894570684448129085

**Platform (please complete the following information):**
 - OS: [Windows 10
 - Browser Chrome
 - Foundry version 0.8.9
 - Lancer system version 1.0.3

**Additional context**
Was creating two weapons as Items in foundry, but was running into issues adding tags to them. Seemed to only allow tags to be dragged on the far right side of the tags bar, with a very small/almost no indication of where to drag them to. Anywhere else bar the far right side didnt work. After adding one tag this way, adding other tags were more lenient. 

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
Siege#0001

**Comment by Eranziel** [comment]
This seems to be fixed on the dev branch. Dropping a tag anywhere in the grey box under the Tags header adds the tag to the item.
