### ISSUE TITLE
[FEATURE] Make a system's additional actions visible on the main item sheet

### ISSUE THREAD

**Issue by Z3nner** [Eranziel/foundryvtt-lancer#361]
**Is your feature request related to a problem? Please describe.**
Additional actions on a system's sheet are not viewable without editing the item.

**Describe the solution you'd like**
A button with the action's name to be visible on the item sheet that pops up a window describing the action(s) provided by the system similar to how comp/com handles this.

**Describe alternatives you've considered**
The entire action description to be included in the item sheet? Might be a bit bulky.

**Comment by Eranziel** [comment]
@Z3nner I'm not sure what you're getting at here. Systems with multiple actions show all of those actions both on the mech's sheet and their own system sheet. Is there a different location you're looking for this data to be shown?

**Comment by Z3nner** [comment]
I think the most recent update mostly addresses this issue.  There are still a few places that could stand to have a hyperlink or something.  See for example the Goblin's Reactive Code trait.  The details of the trait or it's reaction aren't listed anywhere.

**Comment by Eranziel** [comment]
Thanks for pointing that out. Should be able to add actions to the trait views relatively easily. I may be able to render them collapsed by default, but might just need to live with it being bulky for now.
