### ISSUE TITLE
[BUG] Loaded Shows "todo" on Mech Weapon sheet

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#363]
**Describe the bug**
The "Loaded" field on a Mech Weapon sheet is set to display "todo"

**To Reproduce**
1. Open any Mech Weapon's item sheet
2. Observe that "Loaded" is set to "todo"
3. Observe that this is the case for any weapon, even those without the Loading tag.

**Expected behavior**
- When a weapon has the "Loading" tag, "Loaded" is some indicator of "true" or "false", which can be toggled and modified like other settings.
- When a weapon lacks the "Loading" tag, "Loaded" is either not present or some unchangeable version of "N/A" until it gains the "Loading" tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/44978587/141824453-f27ab5ca-5e12-45c2-a35b-ad058eeba8a5.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.9
 - Lancer system version 1.0.3

**Discord contact info**
Valkyrion#6196

**Comment by Eranziel** [comment]
Oof.
