### ISSUE TITLE
[FEATURE] automated-jb2a-animations compatibility

### ISSUE THREAD

**Issue by zautos** [Eranziel/foundryvtt-lancer#364]
I would like it to work with automated-jb2a-animations [https://github.com/otigon/automated-jb2a-animations].
To add a lot of visual flair to the game.

Make compatibility code and then make a pull request on the module.
https://github.com/otigon/automated-jb2a-animations/issues/194

I don't think there are any alternative modules that can do the same thing.

**Comment by Eranziel** [comment]
I'm leaving this open, but it's pretty far down my priority list. Most likely someone else will need to work on this compatibility if it's going to happen, I do not expect to have time to pursue it.

**Comment by Eranziel** [comment]
This is implemented by the Lancer Weapon FX module, so closing this issue.

**Comment by MrVauxs** [comment]
> This is implemented by the Lancer Weapon FX module, so closing this issue.

Lancer Weapon FX module is pretty much a Compendium of macros you have to enable manually, it does not add automated animations functionality (i.e. you attack from any place on your sheet, and an animation happens, you need to exclusively create a macro to do the animations and roll attacks with that macro or else animations don't happen).

I would argue keeping this issue open, as the feature is not implemented by that module. Animations, sure, but not the actual feature request.

**Comment by MrVauxs** [comment]
By the way, the way to implement this is to pass down the entity that caused the animation in the chat message.

I.e. if you are rolling an attack roll with a weapon, a reference to that weapon is passed down to chat message data.

**Comment by Eranziel** [comment]
We do pass the actor and item IDs down to the chat message, and the latest version of Lancer Weapon FX will automatically use those to identify the weapon type and play an animation. The module currently supports all weapons (player and NPC) from official Massif sources.

**Comment by Eranziel** [comment]
That seems to fulfill the intent of the issue to me, am I missing something?

While Lancer Weapon FX doesn't currently support non-official weapons automatically, the devs have been discussing ways to support third party and custom items.

**Comment by MrVauxs** [comment]
If that's the case I think then the only thing left is to let @Otigon know.
If the LWFX module also starts doing automated animations, then sure, this
would be fulfilled.

niedz., 4 wrz 2022, 03:52 użytkownik MJ ***@***.***> napisał:

**Comment by dodgepong** [comment]
The latest version of LWFX supports zero-config automated animations for official Massif content as of a couple versions ago. If it's not working for you, I recommend reporting it on the LWFX repo.

**Comment by MrVauxs** [comment]
I haven't used it in a while, thus my surprise, but just looked at the code and I see certain... [similarities](https://github.com/Z3nner/lancer-weapon-fx/blob/9220ba5ecbfbc390c275ce64e42eab9b29256a37/scripts/WeaponFX.js#L3) to other [modules](https://github.com/MrVauxs/pf2e-jb2a-macros/blob/78d4f4ec73dd09d3e8f768b90c77e00bb5ecd8ac/module/module.js#L92) hahah
Kudos!
