### ISSUE TITLE
[FEATURE] allow npc deployables to be actors

### ISSUE THREAD

**Issue by ehildebrand** [Eranziel/foundryvtt-lancer#365]
**Is your feature request related to a problem? Please describe.**
When I have an engineer or any other Npc that deploys things I have to prepare tokens for the turrets/other deployables in advance

**Describe the solution you'd like**
Classes for NPC deployables just like PC deoyables have. Preferably this includes some nice retrograde minis-type default art.

**Describe alternatives you've considered**
Manually find art and create actors for NPC deployables

**Discord contact info**
If you are willing to answer questions regarding this feature request on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
e.g. Oxox#9292

**Comment by Eranziel** [comment]
This may come after the Comp/Con GM-side update. Currently there is no information about deployables in the NPC data model that Foundry shares with Comp/Con.

**Comment by Eranziel** [comment]
I am going to close this for now. If there is data about deployables in the NPC data model after the Comp/Con GM-side update we will work to integrate those in a similar way to how PC deployables currently are.
