### ISSUE TITLE
[BUG] Drag-and-drop to reorder isn't working on NPC sheets

### ISSUE THREAD

**Issue by sirbayer** [Eranziel/foundryvtt-lancer#367]
**Describe the bug**
When attempting to 

**To Reproduce**
1. Open an NPC sheet.
2. Attempt to drag features around to rearrange them.
3. Observe it doesn't work.

**Expected behavior**
NPC features should be rearrangeable.

**Screenshots**
Stack trace on fail:
![image](https://user-images.githubusercontent.com/5484128/147719903-dbe79936-c02b-4369-806f-7d8bdbc02787.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 95.0.2 (64-bit)
 - Foundry version: 0.9.238
 - Lancer system version: 1.0.3

**Additional context**
This sometimes seems to apply to dragging features from NPC classes to NPC sheets.

**Discord contact info**
Maersk Aerospace#6777

**Comment by sirbayer** [comment]
I will add at this point an addendum that this is happening to me when attempting to add features to NPC sheets with 100% consistency. This only happens when dragging from a class sheet to an NPC sheet, however - if I open the feature directly and use [Search Anywhere](https://gitlab.com/riccisi/foundryvtt-search-anywhere)'s drag and drop, it works successfully. Also, I'm able to drop features into the ordering I want - they correctly place in front of whatever existing feature is dragged over.

**Comment by mason-bially** [comment]
I've been tracing this issue down so far I'm at:

- `ctx` is undefined when using the sheet as a resolver
- because this function is returning undefined: https://github.com/Eranziel/foundryvtt-lancer/blob/dev/src/module/actor/lancer-actor-sheet.ts#L766-L768
- because this function *is not getting called* https://github.com/Eranziel/foundryvtt-lancer/blob/dev/src/module/actor/lancer-actor.ts#L754-L761

**Comment by mason-bially** [comment]
That fixes my reproduction of it!

**Comment by mason-bially** [comment]
For posterity, this issue was what caused the #378 refactor being necessary (now that another intermittent bug has potentially been found).
