### ISSUE TITLE
[REFACTOR] Macro Function Deprecations

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#371]
Several macro functions are named unintuitively, and are slated for more intuitive renames. In each case, the old names will remain available in v1.1 and follow this prototype:
```js
export function oldMacroFunction(args) {
    console.log(`${lp} oldMacroFunction is deprecated, use newMacroFunction instead.\noldMacroFunction will be permanently removed in Lancer v1.2`);
    return newMacroFunction(args);
}

export function newMacroFunction(args) {
...
```

Functions to rename:
* `prepareOverheatMacro` -> `prepareStressMacro`
* `prepareChargeMacro` -> `prepareNpcRechargeMacro`
* `stabilizeMacro` -> `userStabilizeMacro`
* `fullRepairMacro` -> `userFullRepairMacro`

See #370 for original discussion.

**Comment by mason-bially** [comment]
re: `prepareOverheatMacro` -> `prepareStressMacro`
I feel weird about this one. It has a pair in `prepareStructureMacro` I think if we are doing it anyway it might be better to do:
- `prepareOverheatMacro` -> `prepareStressOverheatMacro`
- `prepareStructureMacro` -> `prepareStructureDamageMacro`

**Comment by Eranziel** [comment]
These functions have been fully replaced by the Flow framework, so this issue isn't needed anymore.
