### ISSUE TITLE
[FEATURE] Separate the Attack and Damage steps of making attacks

### ISSUE THREAD

**Issue by Eldraen** [Eranziel/foundryvtt-lancer#379]
**Is your feature request related to a problem? Please describe.**
When players attack enemies, damage is automatically rolled on top of that, this is fine most of the time, however it runs into some issues with some npcs reactions that need to happen between the "to hit roll" and the "damage roll", making it impossible to use them as intended.

**Describe the solution you'd like**
I would like it if damage rolls were a prompt like how structure and stress checks work currently, allowing GMs to react to being hit by an attack (this could also potentially allow for calculating resistance to certain types of damages, automatically halving and whatnot), i have no idea if this would be needed on the NPC roll side of things as no player sided reactions happen before having seen the damage to my knowledge.

**Describe alternatives you've considered**
Hide the damage by default until clicked on could also work, like how you can currently selectively hide parts of the roll.

**Discord contact info**
Eld#7590

**Comment by mason-bially** [comment]
duplicate #189

**Comment by Eldraen** [comment]
don't know if its quite a duplicate because i'm not really after damage application automation as much as i want the option for players to separate the roll to hit from the damage roll itself

**Comment by mason-bially** [comment]
Ah you are right, apologies. It's certainly related though.

If implemented it should probably be an automation flag because I suspect people will miss the current behavior.

**Comment by msprijatelj** [comment]
My 2 cents: Separating the damage roll from the attack sounds similar to Fantasy Grounds Unity’s pattern to attack/damage/effects, where an attack or save is performed with 1 “macro” and the damage roll is performed with a 2nd “macro”. I think such a pattern would be good to investigate when work on Damage Automation begins, as it would be much easier to stage and apply bonus damage abilities if damage wasn’t rolled immediately with the attack.

**Comment by Eranziel** [comment]
Completed as of 74e1cc0d6386554375c37a8ea77902fc05a52c55 !
