### ISSUE TITLE
[BUG] NPC Optional Feature Drag and Drop Not Working From Class Templates

### ISSUE THREAD

**Issue by dysphoniq** [Eranziel/foundryvtt-lancer#380]
**Describe the bug**
When creating NPCs, clicking and dragging features from the class template does not work. Clicking and dragging the feature directly from "Npc Feature" _does_ work. 

**To Reproduce**
1. Create an NPC and assign it an Npc Class template.
2. Open the class template (from either the compendium or the sheet)
3. Select an optional feature and attempt to click and drag it onto the sheet
4. Visually, it looks like this action is allowed, but has no effect.

See also: https://thumbs.gfycat.com/CandidHalfAnemoneshrimp-mobile.mp4 from the wiki, this functionality is shown working at ~ 30 second mark

**Expected behavior**
Expectation is that the feature would then be listed under the "Features" tab, similar to how it works when clicking and dragging from the "Npc Feature" in the compendium.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Foundry version: 9.242+
 - Lancer system version: 1.0.3

**Additional context**
This was working before I upgraded both Foundry and Lancer by at least a major version each. This also affected other users with later Foundry versions than I have running (hence the +), but wanted to give you the oldest one we know it didn't work on.

**Discord contact info**
dysphoniq#3349

Edit: removed inquiry about the recharge macro, turned out to be unrelated to this feature

**Comment by mason-bially** [comment]
Known issue with lancer system on version 9, documented under #367 and (should be) fixed on dev by commit c48e98ba7d9713b5bab754b5d5276067d765d55d

**Comment by mason-bially** [comment]
(also that button (is supposed to) run the "recharge macro" for the NPC's systems)

**Comment by dysphoniq** [comment]
@mason-bially Apologies for the dupe! I didn't realize that issue would also fix adding new features as well. 

And that button is 100% functional and working, sorry for misunderstanding what that button does! I didn't have any rechargable features on my actor when pressing it, so it correctly took no action :+1:

What is the protocol for this reported bug then?  Would you like to close it or should I?

**Comment by mason-bially** [comment]
No idea, probably fine to leave open until the 1.1 merge in case anyone else comes to report it, you would have to close it as I am not a maintainer and cannot close it 😅.

**Comment by Eranziel** [comment]
I got this. ;)
