### ISSUE TITLE
[BUG] NPC sheets occasionally stop loading

### ISSUE THREAD

**Issue by skalchemist** [Eranziel/foundryvtt-lancer#385]
**Describe the bug**
Periodically, an NPC sheet will simply stop appearing when you click the name in the Actors directory.  Double-clicking on the token itself still brings up the sheet.  

**To Reproduce**
I wish I could, I have yet to figure out exactly when it happens.  After a reload everything works fine, but then at some seemingly random point the sheet will stop appearing.

**Screenshots**
Here is the error message that is generated in the console:
![image](https://user-images.githubusercontent.com/92228111/149448697-8ac0bff1-f774-4296-84ce-c93649718ec7.png)

There is not much to see otherwise, as the problem is something NOT happening.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry version: 9 build 242
 - Lancer system version: 1.0.3

**Additional context**
I am running the recommended modules per your wiki, but I'm nearly certain I'm running only modules on your wiki

**Discord contact info**
Skalchemist#5765

**Comment by skalchemist** [comment]
UPDATE: Looking deeper into the console, I think this is actually the first error that happens when it stops working, the other was the error when you try to click on it after it stops working:
![image](https://user-images.githubusercontent.com/92228111/149449627-c257516f-7444-4ec0-b91a-08801cf3ed24.png)

**Comment by mason-bially** [comment]
To me this seems like a #378 issues.

**Comment by mason-bially** [comment]
Personally I would be curious to know if the current version of dev fixes the issue.

**Comment by skalchemist** [comment]
Also I realize now I wasn't clear above, it's not always the same NPC, it seems as if any of them can have this happen.

Also, I realized late last night that I had just restarted my cloud backup sync app.  I wonder if this could be happening in brief moments when the cloud backup is accessing the Lancer files?  I'll turn off cloud backup on these folders tonight during our game and see if the problem still arises.

**Comment by mason-bially** [comment]
For reference this is the link to the [Development Setup](https://github.com/Eranziel/foundryvtt-lancer/wiki/Development-Setup), the current dev branch would have the fix. I would not try this unless you are comfortable with development.

**Comment by Eranziel** [comment]
@skalchemist the commit Mason noted above is part of the v1.1.0 release. Have you updated, and if so has that seemed to solve the issue? It is also plausible that it could be due to file management conflicts with your cloud backup software, interested to hear if that solved the issue.

**Comment by skalchemist** [comment]
@Eranziel we have only had one session since then, which was Feb 11.  The issue did not come up at all. In fact it was so smooth I didn't even remember there had been a problem! I did update everything beforehand.  We have another session on Feb 25 I will pay special attention.
