### ISSUE TITLE
[BUG] Player Can't Clear Lock-On Status on Unowned Tokens

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#397]
**Describe the bug**
A player lacking ownership of a token cannot clear the Lock-On status after consuming Lock-On on an attack due to token permissions.

**To Reproduce**
1. As a GM, setup a mech token owned by a non-GM player and a token owned only by the GM on the same scene.
2. Apply the Lockon condition to the GM-owned token.
3. Log out as GM, and log in as the player.
4. Select the player-owned token, then target the token with Lock-on.
5. Make sure that "Consume Lock-on" is enabled in the Attack popup, then click roll.
6. Observe that the Attack rolls normally, with the correct Accuracy from Lock-on, but an error notification appears saying that the player lacks permission to update the token. Observe that the Lock-on condition is still present on the GM token.

**Expected behavior**
**Expectations for this bug report:** A player consuming Lock-on will clear the Lock-on condition from a target.

**Expectations for future development:** System-level automation or macros (like automatically consuming Lock-on) will allow non-GM players to bypass token ownership permissions, such as adding/removing Statuses or (when the system supports it) applying/removing damage/heat.  

**Screenshots**
Error message after enabling "Consume Lock-on" and clicking "Roll":
![image](https://user-images.githubusercontent.com/44978587/151844301-9da80b55-d3e8-422c-93c1-a9ef05869c73.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 9.245
 - Lancer system version 1.1.0

**Additional context**
It's unclear whether this is a Core Foundry issue or a Lancer Game System issue.  Maybe take a look at the D&D5e and PF2e systems to see how they handle adding/removing statuses? EDIT: Checked vanilla D&D5e and PF2e. They don't support updating the statuses non-owned tokens/actors; at best they just post statuses in the chat and the GM needs to click/drag them.  It seems to be assumed that applying/removing statuses on non-owned tokens/actors must be performed by the GM. 😕 Expanding status update permissions to non-owned tokens may require inspiration from modules.

**Discord contact info**
Valkyrion#6196

**Comment by msprijatelj** [comment]
Tested permissions further today; Core Foundry seems to have invisible delineations between GMs (Gamemaster & Assistant GM) and Players (Players & Trusted Players).  Users with Assistant GM permissions can apply conditions & update unowned tokens much like a GM can.  They also seem to ignore token ownership when it comes to a token's sheet visibility.  Basically, if you make all your players Assistant GMs so they can apply conditions to tokens, they will also be able to see the tokens' statblocks.  This may not be a tolerable workaround for some folks, but at least it's on the table.

**Comment by msprijatelj** [comment]
Did some more research on this: Since Players can't update unowned tokens/actors, the code that updates the actor needs to be split into 2 parts: 1 that the Player can trigger (and acts as a pass-through), and 1 that runs the actual code as GM.  I'll investigate further; if anyone has any alternative ideas on how to handle this, I'm open to them!

**Comment by ParadoxSong** [comment]
You can ask in #dev-support in the foundryVTT discord and they might tell you a better solution. I'm sure they're not happy about a primary selling point being touchy.

**Comment by msprijatelj** [comment]
Sohum found this issue on the FoundryVTT Gitlab: https://gitlab.com/foundrynet/foundryvtt/-/issues/4808

If addressed, it would address our issue here.

**Comment by Eranziel** [comment]
I'm marking this as won't fix for now, since it seems to be a purposeful Foundry behaviour. Dispatching requests to the GM works in some but not all cases. (Like my PbP game. :P)

That said, if someone really wants to tackle this don't let me stop you.

**Comment by msprijatelj** [comment]
Fair, even if it’s frustrating.

**Comment by msprijatelj** [comment]
Closing this since we have a workaround as of v1.5.2! It requires a GM to be logged in, but hey, it that use case, it works.
