### ISSUE TITLE
[BUG]Scenes are not showing up

### ISSUE THREAD

**Issue by AJtheRonin** [Eranziel/foundryvtt-lancer#398]
**Describe the bug**
Using Foundry in Forge, version 9. When trying to set up a scene we get the scene thumbnail but we don't get the scene itself. 

**To Reproduce**
1. Go to 'Scene'
2. Click on 'create Scene'
3. In Background select file and create scene

**Expected behavior**
We should get scenes

**Screenshots**
![image](https://user-images.githubusercontent.com/64420850/153064257-e22ae8fa-5e99-4362-82de-5b7ccbf0fe92.png)

**Platform (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Foundry version [9]
 - Lancer system version [1.1.0]

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
ajtheronin#9736

**Comment by Eranziel** [comment]
I haven't been able to reproduce this. AJ, have you found a solution or still does this issue still exist for you?

**Comment by Eranziel** [comment]
Last news on Discord was that it was probably a module conflict.
> ajtheronin — 02/10/2022
I removed all the modules (except Dice so Nice and Libwarper) and it worked.
