### ISSUE TITLE
[FEATURE] Integrate PDFoundry into system

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#40]
**Describe the solution you'd like**
Integrate the [PDFoundry Library](https://github.com/Djphoenix719/PDFoundry) so we give users the ability to have lancer rules Foundry.

**Comment by Miaradz** [comment]
Now that PDFoundry is available as a mostly standalone module, is this still necessary or are there cooler things that integration will allow?

**Comment by Grygon** [comment]
Nope! Closing
