### ISSUE TITLE
[FEATURE] Include Lancer Macros as buttons on Mech Sheets

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#401]
**Is your feature request related to a problem? Please describe.**
I don’t enjoy relying upon my hot bar and selecting a token to use the LANCER Macros like Stabilize, Overheat, or Full Repair. 

**Describe the solution you'd like**
It would be convenient to have the LANCER Macros on the actor sheet as buttons to allow for quick, actor-specific access to macros like Stabilize, Overheat, or Full Repair. This would not require selecting the actor ahead of time, as well. 

**Describe alternatives you've considered**
The system as-is is workable enough. 

**Additional context**
Having a Stabilize or Full Repair macro would make a lot of sense on the Stats page of the Mech (i.e. alongside hp, heat, etc) and help fill out some of the empty space on that tab. I also wouldn’t need to manage macro permissions for my players; they could simply press the button!

It may also be user-friendly to move the “basic attack” prompt to a macro on the actor sheet, so that the prompt doesn’t automatically load after targeting anything (this has been a recurring ask on PilotNet). 

**Discord contact info**
Valkyrion#6196

**Comment by Eranziel** [comment]
Good suggestion! I agree the stat-related make sense. 

Maybe just have the Grit macro be the only trigger for basic attack?

**Comment by ScyllPoesis** [comment]
Yoinking this one for a slow saturday.

**Comment by ScyllPoesis** [comment]
![image](https://user-images.githubusercontent.com/40338743/166118170-52df146a-d4fd-4a35-8d6f-6d4fd34cec98.png)

Taa-dah. All neat.

I also went ahead with the above suggestion of disabling the basic attack trigger. If you need a basic attack you can click the little weapon icon next to GRIT.

**Comment by msprijatelj** [comment]
@ScyllPoesis I’m digging this a lot! Good to see clear labels on those buttons too. If I were to be nitpicky, I would probably put the buttons in the order of “Stabilize, Full Repair, Structure, Stress” since “Stabilize” is like a “small repair”, so it reads from “small stabilize” to “large full repair” if that makes sense? Also heck yes on the Grit attack button, that’ll cover Grapples and Rams too!

**Comment by ScyllPoesis** [comment]
Adjusted and gave some separation between the two "types".
![Capture](https://user-images.githubusercontent.com/40338743/166127619-730b51c6-0273-48e2-abcc-3b615946a2b5.PNG)
I (unfortunately) don't have a lot of mileage actually playing this beautiful game yet, so insight on small stuff like this is appreciated. 👍

**Comment by Eranziel** [comment]
Looking good! Planning to review the PR soon.

I wonder about swapping stabilize and full repair? Then the more frequently used ones (stabilize, structure, overheat) would be all next to each other.

**Comment by msprijatelj** [comment]
> Looking good! Planning to review the PR soon.
> 
> I wonder about swapping stabilize and full repair? Then the more frequently used ones (stabilize, structure, overheat) would be all next to each other.

Poor Scyll, between Eranziel and me we’ll have the Full Repair and Stabilize macro flopping back and forth lol

**Comment by ScyllPoesis** [comment]
Was busy but I just merged so I'm no longer responsible for moving the dinnerware back and forth. 🛌 

Jokes aside, full repair definitely is in a different sort of category from the other three. Perhaps it can live on a separate row. FR can't be used during combat, correct? If it's only a long rest equivalent, we can also just hide it if the token is in combat (similar to how I show/hide the action tracker block).
