### ISSUE TITLE
[BUG] Jericho Deployable Cover is listed as a full action to deploy

### ISSUE THREAD

**Issue by OddDirective** [Eranziel/foundryvtt-lancer#403]
**Describe the bug**
The Jericho Deployable Cover does not have the appropriate Quick Action tag in the compendium or when equipped to a mech. As such, it is a piece of LL0 gear nerfed in only Foundry VTT play.

**To Reproduce**
1. Go to the Mech Systems Compendium
2. Click on Pattern-A Jericho Deployable Cover
3. Note that it has only the Deployable and Unique tags, and is listed as a Full Action to deploy.

**Expected behavior**
I expected the Jericho Deployable Cover system to be accurately represented, and that it properly takes a quick action to deploy.

**Screenshots**
![part1](https://user-images.githubusercontent.com/101533087/158087050-ac7ccae6-f12b-43f7-ad84-bdd4c9a20b07.PNG)
![part2](https://user-images.githubusercontent.com/101533087/158087056-5648b113-9967-451b-8989-d32a3e0effd6.PNG)

**Platform (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Foundry version: 9.249
 - Lancer system version: 1.1.0

**Additional context**
I just learned that it's a Quick Action in the book and on Comp/Con, so I figure it's just that this one got missed.

**Discord contact info**
OddDirective#4143

**Comment by Eranziel** [comment]
The Jericho's data has the "redeploy" cost as quick and the "recall" cost as full. Machine-mind must be using the "recall" cost instead of the "redeploy" cost on import.

**Comment by Davis-K-Johnson** [comment]
![Image](https://github.com/Eranziel/foundryvtt-lancer/assets/89803504/207514f8-236f-4231-bb19-55be6b6692aa)

This seems to be fixed. I looked at both the compendium version and applied it to a mech. Both list the correct action costs for activating, picking up, and redeploying
