### ISSUE TITLE
[BUG] Brutal 3's Counter Needs a smaller limit

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#408]
**Describe the bug**
The counter imported with Brutal 3 has a cap far above the room available for renderable pips, leading to pips trailing off the end of the sheet.

**To Reproduce**
1. Create a pilot with the Talent Brutal 3: Relentless in CompCon
2. Import that pilot into Foundry
3. Check the pilot sheet's counters; see that "Brutal Die" has over 50 pips.

**Expected behavior**
Counters either:
- Have a reasonable cap for pips that reasonably fits on the pilot sheet
- Use a number text box with arrows to tick the counter up or down (or manually set it) without using pips.  This could possibly be special behavior for "high cap" or "limitless cap" counters.

**Screenshots**
![image](https://user-images.githubusercontent.com/44978587/161409548-107ab5b8-c0b3-4237-8b8f-3340e107f40a.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 9.255
 - Lancer system version 1.1.0

**Additional context**
This also occurs by simply adding the Brutal talent to a pilot and increasing its rank to 3.  Side note: It's also possible to increase Talent ranks higher than 3 (to no effect other than unexpected numbers in the "tier" spot).

**Discord contact info**
Valkyrion#6196

**Comment by msprijatelj** [comment]
It may be better to instead cap the Brutal Die's maximum on `lancer-data` instead, since it's the biggest anomaly here.

**Comment by Eranziel** [comment]
This is due to Brutal 3's counter having a max value of 100 in `lancer-data`, but we should still do something about it. I think applying a maximum (10?) is a good starting place, and replacing the array of pips with +/- buttons for large counters is a good long term solution.

**Comment by ScyllPoesis** [comment]
Went through and tidied this one up a bit. Counters will now revert to a generic mod input (like stats) mode when max counters is above a certain hardcoded limit (for now when set above 8). This allows us to not have to manually alter incoming data, and just let it be large. The use cases for large counters is usually not a `x out of y` scenario, so for now the maximum in this mode is hidden.

Counters now also have +/- wings for easier input and more unified styling, and while I was working on that I also took care of the side-effect noted above and made it so adding a `data-max` attribute to the `mod-plus-button` puts in a flag for the handler to not go past.
