### ISSUE TITLE
[BUG] Infinite grey screen after installing LANCER Core Data

### ISSUE THREAD

**Issue by JediDM99** [Eranziel/foundryvtt-lancer#410]
**Describe the bug**
Installing the LANCER Core Data after creating a new world, then closing and reopening Foundry stops the world from loading.

**To Reproduce**
1. Create a new world using the Lancer system.
2. Launch the world.
3. When the "Install Core Data" popup appears, click "Yes".
4. Once the Core Data has been installed, exit out of Foundry.
5. Reopen Foundry and launch the world. After logging in, you'll get stuck on the grey screen. Eventually, the program will stop responding.

**Expected behavior**
The world to load as expected.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/10265009/162595999-4b904502-5d02-4651-b242-b70e877da8bd.PNG)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: N/A, locally running Foundry Desktop app
 - Foundry version v9.0.0
 - Lancer system version v0.1.10
 - LANCER Core Data v3.0.34

**Additional context**
I just bought and downloaded the software/system today, and don't have any modules installed. Clearing the Compendium Data using the LANCER Compendium Manager between steps 3 and 4 prevents the error from happening.

**Discord contact info**
Radio_Throne_Matt#3704

**Comment by Eranziel** [comment]
Can you post a copy/screenshot of your browser's console output when you get that screen? Ctrl+Shift+I or F12 in most browsers opens the dev tools.

**Comment by JediDM99** [comment]
I'm not yet doing any client/server stuff, this is all on the locally-running desktop app, as I literally just downloaded Foundry and started messing around with it a few hours ago. I haven't looked into what it takes to host a server yet. However, I get the following logs when I run the program via command line:
```
C:\Program Files\Foundry Virtual Tabletop>"Foundry Virtual Tabletop.exe"

C:\Program Files\Foundry Virtual Tabletop>
FoundryVTT | 2022-04-09 22:25:37 | [info] Running on Node.js - Version 16.5.0
FoundryVTT | 2022-04-09 22:25:37 | [info] Foundry Virtual Tabletop - Version 9 Build 266
FoundryVTT | 2022-04-09 22:25:37 | [info] Loading data from user directory - C:/Users/[MY_USERNAME]/AppData/Local/FoundryVTT
FoundryVTT | 2022-04-09 22:25:37 | [info] Application Options:
{
  "port": 30000,
  "upnp": true,
  "fullscreen": false,
  "hostname": null,
  "localHostname": null,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "awsConfig": null,
  "dataPath": "C:/Users/MGC/AppData/Local/FoundryVTT",
  "passwordSalt": null,
  "proxySSL": false,
  "proxyPort": null,
  "serviceConfig": null,
  "updateChannel": "stable",
  "language": "en.core",
  "upnpLeaseDuration": null,
  "compressStatic": true,
  "world": null,
  "isElectron": true,
  "isNode": false,
  "isSSL": false,
  "noupdate": false,
  "noIPDiscovery": false,
  "demo": null
}
FoundryVTT | 2022-04-09 22:25:37 | [info] Software license verification succeeded
FoundryVTT | 2022-04-09 22:25:37 | [info] Requesting UPnP port forwarding to destination port 30000
FoundryVTT | 2022-04-09 22:25:37 | [info] Running Electron application with version 15.3.5 using Chromium 94.0.4606.81
FoundryVTT | 2022-04-09 22:25:37 | [info] Server started and listening on port 30000
FoundryVTT | 2022-04-09 22:25:39 | [info] Created client session e03c8c10d497981e947c7e08
FoundryVTT | 2022-04-09 22:25:39 | [warn] Package lancer contains 2 compendium definitions that still use the deprecated 'entity' field instead of 'type'.
FoundryVTT | 2022-04-09 22:25:39 | [warn] Package lancer contains 27 compendium definitions that still use the deprecated 'entity' field instead of 'type'.
FoundryVTT | 2022-04-09 22:25:43 | [warn] Package lancer contains 2 compendium definitions that still use the deprecated 'entity' field instead of 'type'.
FoundryVTT | 2022-04-09 22:25:45 | [info] User authentication successful for user Gamemaster
FoundryVTT | 2022-04-09 22:25:46 | [info] No system update is currently available.
```

And nothing happens beyond that. I tried to connect to the locally-running instance in my browser via navigating to localhost:30000 but that's also been infinitely loading...

**Comment by zprice0** [comment]
I've encountered a similar error doing this same thing.

![Screenshot 2022-05-17 230530](https://user-images.githubusercontent.com/105764616/168948877-9ca29898-77f3-46a3-90dc-1f9be79e66fc.png)

After fiddling around with it for a while, it seems to be having a issue with downloading the base compendium. I didn't encounter this bug using an older version, but then I was unable to upload pilots from COMP/CON. In addition, all of the compendium folders for Mechs and PC Presets were empty. Other folders like traits were populated though.

**Comment by JediDM99** [comment]
While I've spoken to Eranziel privately, I never followed up on this here. This was caused by an antivirus software I didn't know I had installed. Removing that antivirus allowed the server to start as expected.

**Comment by zprice0** [comment]
Was it a third party antivirus? As far as I can tell I am only running Windows Defender. I also tried on a second device and ran into the same error.

**Comment by Eranziel** [comment]
I'm not certain zprice's error is the same. They seem to be getting a different error message in the console.

@zprice0, what version of Lancer and Foundry are you on?
