### ISSUE TITLE
[BUG] Importing homebrew from cc-lcp-editor, problem with ids?

### ISSUE THREAD

**Issue by skalchemist** [Eranziel/foundryvtt-lancer#411]
**Describe the bug**
I created a homebrew lcp in the cc-lcp-editor (https://github.com/massif-press/cc-lcp-editor ).  This file looked fine in Comp/Con. When it was added to Foundry VTT via compendium manger, all the bits also looked fine.  However, when a pilot was loaded into Foundry (via RM-sync), the pilot/mech record in Foundry did not "connect" up with any of the bits from the homebrew lcp.  

**To Reproduce**
See the file here: https://skalchemist.cloud/mediawiki/index.php/File:Serpentrocktechnology_0.0.2.zip (you will need to change the file extension to "lcp"

This is the raw file from lcp editor, it causes the failure to connect described above. To reproduce:
* Install that file in both comp/con and Foundry VTT
* Create a new pilot (license lvl 2 will work) and unlock two levels of the "Serpent Rock Technology" license "KETOS"
* Create a mech using the "KETOS" frame for that pilot, and add some "KETOS" systems.
* Create new blank pilot in foundry
* Sync that pilot to the pilot in Comp/Con
* Synced pilot will have any GMS or core rulebook systems you added, but will show no mech frame and will not have any of the homebrew systems

**Troubleshooting**
By going in and by hand editing the lcp file from the editor, I was able to create a version that works, which leads me to believe that Foundry VTT is not parsing the random ids that come out of the lcp editor. Try the same experiment with these two files:
https://skalchemist.cloud/mediawiki/index.php/File:Serpentrocktechnology_0.0.2.1.zip - This is the same lcp with linebreaks added to make it more legible. It still has the problem.
https://skalchemist.cloud/mediawiki/index.php/File:Serpentrocktechnology_0.0.2.2.zip - this is the same as 0.0.2.1, but has all the random gibberish ids replaced with ids that match the formats used in the base comp/con data. This version seems to work.

Therefore, it seems like the issue is that Foundry VTT Lancer system is not parsing the id's properly?  That is the only change between 0.0.2.1 and 0.0.2.2

NOTE: I have also submitted this as an issue to the cc-lcp-editor github, because it is not clear to me which side of the issue has the problem.  https://github.com/massif-press/cc-lcp-editor/issues/26

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry version 9, build 255
 - Lancer system version: 1.1.0 

**Discord contact info**
Skalchemist#5765

**Comment by mason-bially** [comment]
This is an issue with whitespine/machine-mind that came up with another homebrew LCP. See [this discord thread](https://discord.com/channels/426286410496999425/966456845118095461). I'll probably be submitting a pull request for this for machine-m,ind at somepoint.
