### ISSUE TITLE
[BUG] Hidden Right Click Menu on Chat Messages

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#416]
**Describe the bug**
Right clicking on a chat message header should bring up a context menu for stock Foundry functionality. This menu is not visible when running Lancer.

This is an issue with, for example, whispered chat messages. The context menu includes an option to show the message to others, so this becomes impossible.

**To Reproduce**
1. Creare a whispered chat message.
2. Right click on the header, no context menu appears.
3. Open the inspector and disable the clip path styling applied to the chat message by Lancer.
4. Right click the header again. Context menu now appears.

**Expected behavior**
The context menu should be usable.

**Comment by mason-bially** [comment]
My current UI refactor will fix this, but for posterity's sake the offending lines of code appear to be:
- https://github.com/Eranziel/foundryvtt-lancer/blob/master/src/lancer.scss#L205
- https://github.com/Eranziel/foundryvtt-lancer/blob/master/src/lancer.scss#L209
At least for me, the clip path doesn't appear to have any relationship to the issue.

**Comment by Davis-K-Johnson** [comment]
A context menu appears for me on both normal and hidden messages.
