### ISSUE TITLE
[FEATURE] Numbered Condition Icons

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#42]
Implement a feature to facilitate visually tracking conditions with numbered states on the canvas. Useful for burn, or anything with a tracking die.

The Pathfinder 2e system implements something similar, for a source of inspiration.

**Comment by Grygon** [comment]
There's a module that looks like it does this decently: https://foundryvtt.com/packages/statuscounter/

Do we want to just have it as a suggested module, at least for now?

**Comment by Eranziel** [comment]
I think this is covered well enough by various modules - Resource Icons, Bar Brawl, and Status Icon Counter. Closing.
