### ISSUE TITLE
[BUG]Removing a Class or Template from an NPC sheet no longer removes applicable features

### ISSUE THREAD

**Issue by Z3nner** [Eranziel/foundryvtt-lancer#424]
Removing a Class or Template from a character sheet no longer removes applicable features.

**To Reproduce**
1. Create a new NPC or open an existing one.
2. Add a class or template to the character sheet Observe the base features being populated
3. Remove the class or template.  Observe that the previously added features are not removed.

**Expected behavior**
I believe in the past these features were automatically removed with the class/template.

**Comment by Davis-K-Johnson** [comment]
![Image](https://github.com/Eranziel/foundryvtt-lancer/assets/89803504/450be231-5628-4f0e-9073-6ce21da8e2e2)

I used the steps to recreate the problem and it appears to still be working like that. All of the mech stats reset to 0 as expected but systems are still left over.
OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0

**Comment by Eranziel** [comment]
Fixed in #625.
