### ISSUE TITLE
[FEATURE] Wreck Macro Removes Token from Combat Tracker

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#425]
**Is your feature request related to a problem? Please describe.**
When an NPC is destroyed, I like to use the Wreck macro to leave behind a wreckage on the battlefield. However, the NPC remains on the combat tracker, causing some confusion as to whether they’re still in play. 

**Describe the solution you'd like**
Add a few lines of code that will remove a token targeted by the Wreck macro from the combat tracker. 

**Describe alternatives you've considered**
The workaround of actively removing a token from the combat tracker is workable, but takes too many clicks when I just want to move on to the next action. 

**Discord contact info**
Valkyrion#6196

**Comment by ScyllPoesis** [comment]
I agree with this. Was running my demo the other day and could not find an easy way to mark as defeated like other systems, and literally had this confusion happen. Will wrap into #426.
