### ISSUE TITLE
[BUG] LCP Import does not preserve special characters in IDs

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#432]
**Describe the bug**
Some non-standard characters are stripped from LIDs when importing LCPs. For example, [Jager Kunst 1 & 2](https://github.com/massif-press/long-rim-data/blob/c468eed6c961e111018d0e88a1dd4ce3cb7b2264/systems.json#L20). This causes imported pilots which use those systems to skip affected systems.

**To Reproduce**
1. Import the Long Rim 1.0.10 LCP.
2. Import a pilot from Comp/Con which has Jager Kunst 1 and/or 2.
3. Imported mech does not have the system installed.

**Expected behavior**
IDs should be preserved so that they match imported Comp/Con data.

**Screenshots**
Jager Kunst 2 in raw pilot data from Comp/Con:
![jk2](https://user-images.githubusercontent.com/49248157/169712711-de0f2023-53e8-43cd-bce1-b30501eef4c8.png)

Jager Kunst 2 in compendium after importing LCP:
![image](https://user-images.githubusercontent.com/49248157/169712678-41821fed-cef4-4061-b2a3-7b9e9da3bd9c.png)

**Comment by mason-bially** [comment]
Is this possibly related to whitespine/machine-mind#20

**Comment by Eranziel** [comment]
Looks like the sanitization code in `generateItemID` will strip out the `ä`, so seems likely to me. My question then is, how does that ID work on the Comp/Con end and make it into cloud saves? Do we need to sanitize every ID in a cloud-downloaded pilot before trying to match to the compendia?

**Comment by msprijatelj** [comment]
> Looks like the sanitization code in `generateItemID` will strip out the `ä`, so seems likely to me. My question then is, how does that ID work on the Comp/Con end and make it into cloud saves? Do we need to sanitize every ID in a cloud-downloaded pilot before trying to match to the compendia?

I'm pretty sure it just writes it as-is? Otherwise it wouldn't match up on loading from the cloud.

**Comment by BoltsJ** [comment]
Just tested and this appears to have been fixed in 2.0 already.
