### ISSUE TITLE
[BUG] TAH Support Audit

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#433]
**Describe the bug**
Token Action HUD's tech attack macro no longer triggers the attack HUD, instead triggering the check HUD. Other macros may be affected as well.

**To Reproduce**
1. Target a token.
2. Use the Mech -> Tech Attack macro through Token Action HUD.
3. Check HUD is presented instead of attack HUD.

**Expected behavior**
Tech Attack should trigger the attack HUD, same as clicking the Tech Attack roller from a mech's sheet.

**Screenshots**
![image](https://user-images.githubusercontent.com/49248157/170892311-3f43ee99-9cbc-42a8-b1c3-c46a3b9dd753.png)
![image](https://user-images.githubusercontent.com/49248157/170892314-a588bacd-0b2b-41f6-b276-71e32d7fe6f9.png)
![image](https://user-images.githubusercontent.com/49248157/170892317-546bb291-7760-4fd2-8bb6-271a437b007e.png)
![image](https://user-images.githubusercontent.com/49248157/170892322-e7cd1b9a-8930-403f-a606-cd5717007c03.png)

**Platform (please complete the following information):**
 - Foundry version 9.269
 - Lancer 1.2.0

**Comment by Eranziel** [comment]
This will need to be fixed in a PR to Token Action HUD.

**Comment by purringInsanity** [comment]
I've made a PR to TAH that fixes the base tech attack. It's a quick fix, but should work as a stopgap while I rework some things to make better use of the new macro functions available.  Hopefully shouldn't take me too long, schedule permitting.

**Comment by msprijatelj** [comment]
May be closed by Drental/fvtt-tokenactionhud#377

**Comment by Eranziel** [comment]
Closed indeed.
