### ISSUE TITLE
[BUG] Removing a trait from an NPC template attempts to remove from the compendium instead

### ISSUE THREAD

**Issue by LoganCF** [Eranziel/foundryvtt-lancer#435]
I was trying to create a custom NPC template, but when I tried to remove a feature from it using the vertical-... menu on the feature, it either displayed "You may not modify the world.npc_feature Compendium which is currently locked." for vanilla features, or just deleted the feature definition from the items tab when I tried it on a custom feature.

I expected it to instead just remove the feature from the template definition.

**Comment by BoltsJ** [comment]
I can confirm this. Also, removing items that are worl items from a template deletes them.

Steps to reproduce:
1. Create a blank new template
2. Add an item from a compendium to the template
3. Remove the item from the template
4. See the error
5. Create a world item and add it to the template
6. Remove the item from the template
7. World item is deleted.

**Comment by Vixiea** [comment]
I can confirm this as well, I can also confirm if you import the item from the compendium, attach it to the NPC, and then remove it, the imported item is deleted.

**Comment by kaiyihuang** [comment]
I would like to report that this issue is still present in v1.2 and should be reopened.

**Comment by BoltsJ** [comment]
This issue is still open.

**Comment by dodgepong** [comment]
My understanding is that it will be auto-closed when dev is merged into master -- this bug is already fixed on dev (see https://github.com/Eranziel/foundryvtt-lancer/pull/444).
