### ISSUE TITLE
[BUG] Traits and mounts can't be added to new frame items

### ISSUE THREAD

**Issue by Cancermantis** [Eranziel/foundryvtt-lancer#44]
When making a new frame item, new mounts and traits can't be added.

To Reproduce
Make a new item of the frame type in the items tab
Edit the new item, then click the "+" buttons next to either "Available Weapons" or "Traits"

No mount-type drop down or trait text box appears to be edited after doing so

**Comment by Grygon** [comment]
Looks like possibly a merge issue. Also noticed some other issues with frame sheets, will see about getting a fix in shortly.

**Comment by Grygon** [comment]
Fix completed & will be included in next minor version, closing.
