### ISSUE TITLE
[FEATURE] Bypass the Combat Dialog that comes up when you target but haven't chosen an attack

### ISSUE THREAD

**Issue by tbrockwood** [Eranziel/foundryvtt-lancer#442]
In most other game systems, the attack workflow is: Target enemy, choose your weapon, attack dialog appears, then roll your attack.

But in Lancer, if you target someone, it immediately pops up the attack dialog as a generic "Basic Attack", and then, when you click a specific attack, it swaps the Basic Attack for a new dialog with your specific weapon choice.

Is there (or can there be) some way to set the system so that if I'm just targeting someone, the Basic Attack doesn't pop up, and I only get the attack dialog popup once I've actually clicked to roll my weapon, like in other systems?

**Comment by dodgepong** [comment]
The basic attack box was disabled in this commit: https://github.com/Eranziel/foundryvtt-lancer/commit/6c0cb9fb93ed9d9b595ba7c3a4dbd5803d6bb838

Assuming this is unchanged in the next release, the the next release won't have the basic attack box.
