### ISSUE TITLE
[BUG] Systems Text boxes unexpected behaviour

### ISSUE THREAD

**Issue by Miaradz** [Eranziel/foundryvtt-lancer#46]
**Describe the bug**
Some systems have no description in their entries when viewed in the compendium. When opened up and then closed, "[object Object] Effect" updates on the sheet.

If this is part of non-rendered Systems data in Changelog, please feel free to close.

**To Reproduce**
1. Open a new character.
2. Go to Frame//Loadout and set up a mech.
3. Drag PATTERN-A SMOKE CHARGES to the mech loadout.
4. Click on PATTERN-A SMOKE CHARGES and then close the window.

**Expected behavior**
Text should match and also empty boxes should not display odd things.
![image](https://user-images.githubusercontent.com/66564401/87951398-1bb95200-cadb-11ea-97de-dbef9edf44ca.png)

Windows 10, Electron applet, no mods that affect sheet/chat logs.

**Comment by Grygon** [comment]
Looks like our implementation of effects isn't completely accurate on the system page:
![image](https://user-images.githubusercontent.com/647846/87968513-25fd3100-ca86-11ea-8367-1e778e4d160e.png)
![image](https://user-images.githubusercontent.com/647846/87968602-4d53fe00-ca86-11ea-84ed-7efb162d4171.png)

Will get a fix in shortly

**Comment by Eranziel** [comment]
Just keep in mind there's a lot of work to do still for system/weapon effects - see #22.

**Comment by Grygon** [comment]
That's a good point, and given #41 I'm not going to try to make an in-depth solution if this is all going to change on us shortly.

However, I implemented a fix for charges, since that's the more severe issue.
