### ISSUE TITLE
[FEATURE] Replace Exotic Features in Scan Macro

### ISSUE THREAD

**Issue by TobyPotato** [Eranziel/foundryvtt-lancer#466]
**Is your feature request related to a problem? Please describe.**
The Scan Macro is very helpful for displaying the information from a Scan to players. However, it does have one issue, as it will display Exotic Systems despite the Xenotech Feature of Exotics stating that they are obscured on a Scan. While this isn't a big deal, it can lead to players having more information through the macro than they should, which reduces some of the mystique of Exotics.

**Describe the solution you'd like**
Either remove Exotic Features (Xenotech says Systems, but I think it means Features in general, as Exotic doesn't have much of any systems) from the Scan Macro entirely, or obscure them so they can't be read.

**Describe alternatives you've considered**
As above, the alternatives are either just don't display the feature by checking where it comes from, or obscuring it. Alternatively, the Scan Macro could not be used.

**Additional context**
I've already made modifications to support either option. Below are my code modifications and the result on an Exotic Monstrosity with entirely base Features.

Removing Exotic Features:
```
let sc_list = ``;
let sc_features = sc_dir._features.filter(i => i.Origin.name != "EXOTIC");
if (!sc_features || sc_features.length == 0) {
    sc_list += "<p>NONE</p>";
} 
else {
    sc_features.forEach(i => {
        console.log(i);
        let sc_desc = ``;
        if (i.Effect) {
            sc_desc = i.Effect;
        } else {
            sc_desc = "No description given.";
        }
        if (i.Trigger) {
            sc_desc = "Trigger: " + i.Trigger + "<br>" + sc_desc;
        }
        let sc_entry = "<details><summary>" + i.Name + "</summary><p>" + sc_desc + "</p></details>";
        sc_list += sc_entry;
    });
}
```

![image](https://user-images.githubusercontent.com/78451177/188336232-597cf0d4-e83d-4db1-8458-c09b64e075a5.png)
Obscuring Exotic Features:
```
let sc_list = ``;
if (!sc_dir._features || sc_dir._features.length == 0) {
	sc_list += "<p>NONE</p>";
} else {
	sc_dir._features.forEach(i => {
		console.log(i);
		let sc_name = ``;
		let sc_desc = ``;
		if (i.Origin.name == "EXOTIC") {
			sc_name = "<code class=\"horus--subtle\">UNKNOWN</code>";
			sc_desc = "???";
		}
		else {
			sc_name = i.Name;
			if (i.Effect) {
				sc_desc = i.Effect;
			} else {
				sc_desc = "No description given.";
			}
			if (i.Trigger) {
				sc_desc = "Trigger: " + i.Trigger + "<br>" + sc_desc;
			}
		}
		let sc_entry = "<details><summary>" + sc_name + "</summary><p>" + sc_desc + "</p></details>";
		sc_list += sc_entry;
	});
}
```
![ExoticScanGlitch](https://user-images.githubusercontent.com/78451177/188336299-c8b91253-2658-4a4f-87bd-068aacbe0fe7.gif)

**Discord contact info**
If you are willing to answer questions regarding this feature request on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
e.g. Toby#0543

**Comment by msprijatelj** [comment]
This should be covered by the new Scan to journal macro now, right @Eranziel ?

**Comment by Eranziel** [comment]
Yup, should be. Missed closing the issue.
