### ISSUE TITLE
[BUG] NPC Features do not commit to chat log

### ISSUE THREAD

**Issue by Miaradz** [Eranziel/foundryvtt-lancer#47]
NPC features do not seem to roll to chat log. Also their formatting is ugly.

If this is part of non-rendered Systems data in Changelog, please feel free to close.

**To Reproduce**
Create an NPC with Class and template.
Create an NPC Feature. Make it a weapon.
Click on the dice icon.

**Expected behavior**
The accuracy/difficulty slider window should pop up and allow you to commit the roll to chat log like a PC roll.

**Screenshots**
![image](https://user-images.githubusercontent.com/66564401/87952420-64bdd600-cadc-11ea-99c6-ffbacff1bd6d.png)

Windows 10, Electron applet, no mods that affect sheet/chat logs.

**Comment by Eranziel** [comment]
Fixed in 50c256ba403bf5a10255380476d9702c5163808b.
