### ISSUE TITLE
[BUG] Mech/Pilot Sheet: Clicking Loading or Limited pips autoscrolls sheet

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#471]
**Describe the bug**
Clicking a hexagon pip for items like Loading, Limited, or even Counters on a Mech/Pilot sheet will cause the sheet to automatically scroll to the top.

**To Reproduce**
**Pilot Weapons:**
1. Create a new pilot.
2. On the Pilot/Narrative tab, give the pilot a Heavy Signature weapon and several skill triggers to cause the sheet to gain a scroll bar.
3. Scroll down to the Heavy Signature weapon. Click the "Loaded" pip.
4. Observe that the Pilot/Narrative tab automatically scrolls up to the top of the tab.

**Pilot Counters:**
1. Navigate to Pilot/Tactical tab on a new pilot. 
2. Create enough counters on the new pilot to cause a scroll bar to appear.
3. Click the bottom-most counter to change its pips.
4. Observe that the Pilot/Tactical tab automatically scrolls to the top of the tab.

**Mech Weapons & Systems:**
1. Create a new Mech.
2. Navigate to the Mech/Loadout tab.
3. Add a Loading weapon to the mech (Missile Launcher will fit in any mount).
4. Make sure that you need to scroll down to see the "Loaded" pip on the weapon.
5. Click the Loaded pip.
6. Observe that the Mech/Loadout tab automatically scrolls to the top of the tab.
7. Add a Limited system to the Mech (e.g. "Roller" Directed Payload Charges)
8. Scroll down to the system, and click one of the "Uses" pips.
9. Observe that the Mech/Loadout tab automatically scrolls to the top of the tab.

**Expected behavior**
Clicking a Loaded/Limited/Counter pip does not cause the sheet to scroll to the top; it instead stays where it is with the weapon/system still visible.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Foundry version 9.280
 - Lancer system version 1.3.1

**Additional context**
- This also occurs on a mech sheet using the "Stabilize" macro and choosing to reload.
- This **_does not occur_** when clicking pips for NPC Loading weapons or Limited systems.

**Discord contact info**
Valkyrion#6196

**Comment by sealtrowitz** [comment]
This also happens when switching the (player mech) profile of a weapon with multiple profiles.

**Comment by msprijatelj** [comment]
This appears to be fixed on [v1.4.0-beta.1](https://github.com/Eranziel/foundryvtt-lancer/releases/tag/v1.4.0-beta.1) while using the Foundry desktop client.

**Comment by msprijatelj** [comment]
This issue is fixed on release v1.4.1. Closing.
