### ISSUE TITLE
[BUG] Install fails on 10.285

### ISSUE THREAD

**Issue by RedwanFox** [Eranziel/foundryvtt-lancer#474]
Can't install plugin because Foundry tries to find `system.json` at

```
Eranziel/foundryvtt-lancer/master/src/system.json
```
But It's actually located at
```
Eranziel/foundryvtt-lancer/blob/master/public/system.json
```

**Comment by dodgepong** [comment]
There is not a v10-compatible release of the Lancer system yet.

Also, I don't think what you're describing is actually a problem -- it sounds like you may have installed the system wrong. But again, the Lancer system doesn't work on v10 yet anyway.

**Comment by Eranziel** [comment]
First just for emphasis - as dodgepong says, Lancer does not have a v10 compatible release yet.

Are you trying to update Lancer from an older version? If so, which version of Lancer do you have installed?

**Comment by msprijatelj** [comment]
Now that we have a v10 compatible release, should this be closed @Eranziel ?
