### ISSUE TITLE
[FEATURE] Show weapon range in chat when rolling

### ISSUE THREAD

**Issue by Norgad** [Eranziel/foundryvtt-lancer#485]
**Is your feature request related to a problem? Please describe.**
When rolling weapon attacks, it's very useful that all for damages, tags, and special effects are listed in chat for players to read and refer to. However, there is an odd ommission: weapon range. This is the only thing that's not shared when attacking, and given the openness of the rest of the information it seems out of place to not include.

**Describe the solution you'd like**
Having the ranges of weapon's listed inline with the rest of the attack roll's information would resolve this gap in information. As with other shared information after a character attacks, sharing the range of a weapon would allow players to plan and play more strategically as they would have a more complete understanding of the opposing force.

**Describe alternatives you've considered**
If there are GMs that don't want to share weapon ranges, perhaps there could be a toggle in the settings menu. However, I doubt this would be a sizable number of people, and this would also cerate more work to implement

**Discord contact info**
If you have any questions, or have implemented these changes, please contact Norgad#8398

💜

**Comment by mason-bially** [comment]
FWIW My long in progress chat-UI update branch does add this. I'll try to get that into a PR before the end of the year.

**Comment by Eranziel** [comment]
Closed by cbca9ab753a7c3a2a052d6432493a3b44974aa3c
