### ISSUE TITLE
[BUG] Pilot Armor cannot be increased above 1

### ISSUE THREAD

**Issue by Tenemach** [Eranziel/foundryvtt-lancer#489]
**Describe the bug**
Exactly what the title says - a pilot's armor value does not go above 1 even when wearing a hardsuit that provides more.

**To Reproduce**
1. Create a pilot
2. Drag'n'drop a Heavy Hardsuit (or any hardsuit modified to give 2 or more armor) onto the pilot
3. Behold the top bar display a big ol' 1 next to the armor score anyway

**Expected behavior**
The top bar must display the same armor value as the one specified in the hardsuit's properties

**Screenshots**
![what](https://user-images.githubusercontent.com/117484367/206623977-f449cb45-8847-4add-8b38-f114ec52d67f.jpg)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Foundry version v9.280
 - Lancer system version 1.3.1

**Additional context**
Tried adding the bonus (ID: pilot_armor, Value: 2) multiple times on the same hardsuit, does nothing. Tried increasing or decreasing it beyond normal limits, no value besides 0 or 1 showed up on the tab.

**Discord contact info**
Tenebrae Machina#2022

**Comment by Eranziel** [comment]
Going to expand this to mechs as well. v1.x limits mech armour to 4, which makes for manual bookkeeping with White Witch.

**Comment by Davis-K-Johnson** [comment]
The pilot armor works at the very least now.

![Image](https://github.com/Eranziel/foundryvtt-lancer/assets/89803504/8c070d88-5a84-4bce-9541-e12c4e75b3ee)

Speaking of the White Witch though, I can't even figure out where to edit the armor from its passive at all, which means it's probably at the very least unclear if not difficult for the average user to update. Maybe White Witch specifically should have an armor field that you can edit?

OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0

**Comment by msprijatelj** [comment]
@Davis-K-Johnson you would likely edit the Frame item within the mech’s inventory itself, and change its armor appropriately.

**Comment by msprijatelj** [comment]
That’s good context for the 2.0 branch, then, thank you!
