### ISSUE TITLE
[FEATURE] Create Basic NPC Actors on LCP import

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#490]
**Is your feature request related to a problem? Please describe.**
Users are frequently confused when checking the Foundry Actors Compendium after importing the Lancer Core NPCs and finding no NPCs within. Additionally, preparing a new NPC actor takes a small but nonzero amount of time to create a new NPC actor and dragging an NPC Class from the Compendium onto it.

**Describe the solution you'd like**
Create default NPC Actors in the Actors Compendium upon importing an LCP with NPC Classes, including all of their starting stats and base systems+traits. If this is done, creating a new "Barricade" (for example) would simply involve importing the Barricade NPC Actor from the Compendium. 

**Describe alternatives you've considered**
The existing workflow works fine for many users, though it has a higher learning curve.

**Discord contact info**
Valkyrion#6196

**Comment by perijove** [comment]
Duplicate of #328

**Comment by msprijatelj** [comment]
Ah, so it is. Closing.
