### ISSUE TITLE
[BUG] Some compendiums not loading

### ISSUE THREAD

**Issue by Arkandy** [Eranziel/foundryvtt-lancer#491]
**Describe the bug**
When downloading compendiums (either updating, clearing + updating, or fresh first-time download) via the LANCER Compendium Manager, specific compendiums do not populate. This is most noticeable with the NPC class, NPC template, and NPC feature compendiums, which should be populated as evidenced by the "How to build an NPC" tutorial in the github wiki. It is also observed on other compendiums, but since I don't know if those are supposed to be empty or not, they are listed in the additional context section.

**To Reproduce**
1. Go to the Compendiums tab.
2. Click on LANCER Compendium Manager.
3. Click Rebuild Core Data (or with a fresh install, click "update to v3.0.46").
4. Close LANCER Compendium Manager.
5. Open any of the listed compendiums.
6. Observe they are empty.

**Expected behavior**
Compendiums for NPC class, NPC template, and NPC feature should be populated with relevant core data visible in the NPC tutorial on the wiki. 

**Platform:**
 - OS: Windows 10 (19043.2311), running dedicated server via NodeJS (v16.16.0)
 - Browser: Chrome 108.0.5359.125
 - Foundry version 9.280
 - Lancer system version 1.3.1

**Additional context**
This has been replicated using:
- Existing LANCER world with all suggested modules
- Existing LANCER world with all suggested modules DISABLED
- Fresh LANCER world with no additional modules installed
- FVTT 9.280
- FVTT 9.269

Other compendiums that are empty but I am unsure if that is expected or not:

- Mech
- Pilot Preset
- Npc
- Faction
- Organization
- Quirk

**Discord contact info**
Arkandy#5926
Please reach out with any questions or requests.

**Comment by dodgepong** [comment]
This is working as intended.

NPC content is paid content, and therefore is not loaded with base Lancer content (it's not even publicly available). You will need to download the NPC LCP from itch.io where you bought the Lancer Core PDF and load it into Foundry via the LCP import functionality in order to get NPC data.

**Comment by dodgepong** [comment]
Addendum: If any action should be taken on this issue, it should be that the Wiki article should be updated to add a step 0 explaining how to manually import NPC LCP data.

**Comment by Arkandy** [comment]
Noted! In hindsight, that makes perfect sense. Thank you for the follow up!
