### ISSUE TITLE
[FEATURE] Pre-releases

### ISSUE THREAD

**Issue by MrVauxs** [Eranziel/foundryvtt-lancer#492]
**Is your feature request related to a problem? Please describe.**
V10 Development branch being in progress but no way to test (or just willingly risk games) without copying the entire repo.

**Describe the solution you'd like**
Create pre-releases. They are not treated as latest, so you don't have to worry about users accidentally downloading them off of Foundry.

**Describe alternatives you've considered**
You could provide the manifest URL to the RAW files in the dev branch instead.

**Discord contact info**
@MrVauxs#8622

**Comment by dodgepong** [comment]
I think the plan is to do a beta release once the major bugs get squashed on the dev branch. The main blocker at the moment is that v9 -> v10 upgrade migrations don't currently work correctly, essentially forcing all compendiums and actors to be re-imported.

**Comment by Eranziel** [comment]
Yes, I think you're interested in this: https://github.com/Eranziel/foundryvtt-lancer/releases/tag/v1.4.0-beta.1 😉
