### ISSUE TITLE
[FEATURE] Delete Button for Counters on Item Sheets

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#496]
**Is your feature request related to a problem? Please describe.**
Counters on Item sheets currently lack an option to delete or remove them. If a counter is accidentally added to an Item, a fresh item needs to be created to obtain a counter-free version.

**Describe the solution you'd like**
Add a "Remove" option for counters granted by items.

**Describe alternatives you've considered**
Create a fresh item to obtain a counter-free version. Avoid adding counters to items, instead making custom ones on the pilot sheet.

**Discord contact info**
Valkyrion#6196

**Comment by Davis-K-Johnson** [comment]
Verified that counters now have a working remove button.

OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0
