### ISSUE TITLE
[FEATURE] Initiative System

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#5]
Implement Lancer-specific combat initiative logic.

**Comment by Grygon** [comment]
Check out [popcorn initiative](https://foundryvtt.com/packages/Popcorn/), may be worth just relying on this as a "requirement" for v0.1 & focusing on a built-in system as a future enhancement.

**Comment by Eranziel** [comment]
Good suggestion, thanks for the link! You're probably right that it could be used as a stand-in for 0.1. It's also good as an example to draw from when implementing a built-in initiative system.

**Comment by Eranziel** [comment]
Moving this to at least 0.2, if not later, since popcorn initiative handles it for now.

**Comment by Grygon** [comment]
Moving to v0.3/future, I don't see a _need_ for this outside of the module.

**Comment by Grygon** [comment]
Throwing this in for anyone who comes looking at this issue--there's a great implementation [here](https://github.com/BoltsJ/lancer-initiative)

Not sure if we want to close this since it's met externally, or leave it open pending in-system implementation.

**Comment by Eranziel** [comment]
I would still like to integrate an in-system implementation, but will probably push that further down the road if Bolts continues to support their module.

**Comment by whitespine** [comment]
Necromancying this issue to formally specify the current intended course of action (as I understand it) - make it a foundry system level dependency.

**Comment by BoltsJ** [comment]
Ref BoltsJ/lancer-initiative#19
