### ISSUE TITLE
[BUG] Enlightenment-class NHP missing AI tag

### ISSUE THREAD

**Issue by Argonius-Angelus** [Eranziel/foundryvtt-lancer#505]
**Describe the bug**
Enlightenment-class NHP item is missing the AI tag.

**To Reproduce**
1. Create Technophile 3 character in Comp/Con.
2. Put enlightenment class NHP into mech.
3. Export as share code.
4. Import mech into Lancer for Foundry v9.
5. Notice AI tag is missing for Enlightenment-class NHP.

**Expected behavior**
Enlightenment-class NHP should have the AI tag as seen in the book and Comp/Con.

**Screenshots**
![image](https://user-images.githubusercontent.com/28706410/211202563-93f299e0-274b-4bd7-97ed-da60ceec6e56.png)
![image](https://user-images.githubusercontent.com/28706410/211202583-aafe6561-ac0e-44ec-8b39-a94cbed80bdd.png)

**Platform (please complete the following information):**
 - OS: Win11
 - Browser: Standalone Foundry app
 - Foundry version v9.269
 - Lancer system version 1.3.1

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
[REDACTED]#0001

**Comment by Eranziel** [comment]
The tag is missing in `lancer-data`, so I've opened an issue there to track this: https://github.com/massif-press/compcon/issues/2172
