### ISSUE TITLE
[FEATURE] Add a Tour

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#508]
**Is your feature request related to a problem? Please describe.**
Add a Tour to help onboard users, using the feature which was added in Foundry v10. Some of these may need to be broken up into separate Tours or cut, depending on how much can be done in a Tour. According to Foundry staff, Tours are not meant to be a fully interactive experience, instead being a demonstration of where to find UI elements and tools.
- [ ] Lancer Compendium Manager
  - [ ] Where to find it
  - [ ] How to update core data
  - [ ] How to add an LCP
  - [ ] How to check the version of installed LCPs
  - [ ] How to clear compendiums
- [ ] Comp/Con Login
  - [ ] Where to find it
  - [ ] Explain what it's for and why you might want to use it
- [ ] Create an NPC
  - [ ] Guide creating a new NPC actor
  - [ ] Show where to find NPC classes, templates, and features to add
- [ ] Create a pilot
  - [ ] Create a folder
  - [ ] Create a new pilot actor in that folder
  - [ ] Show the C/C import dropdown and share code box, have user pick one to import a pilot.
  - [ ] Point out pilot/mech item compendiums for manually configuring loadouts
  - [ ] Show how to edit items
    - [ ] Add profile to weapon
    - [ ] Modify tag values
- [ ] Simple combat demonstration
  - [ ] Add tokens to a combat, begin combat
  - [ ] Activate turns
  - [ ] Show combat macros on sheets - basic attack, stabilize, etc...
  - [ ] Trigger attack HUD
    - [ ] Manual targeting - demonstrate reactive UI
    - [ ] Trigger a different weapon to demonstrate reactive UI
    - [ ] AOE buttons and auto-targeting
    - [ ] Cover, lock-on, and acc/diff controls
  - [ ] Trigger tech attack HUD

**Comment by msprijatelj** [comment]
Should we collect #475 here too, with the links/resources it has?

**Comment by Eranziel** [comment]
I somehow missed 475. Closing this as duplicate, moved the tasks into the description of 475.
