### ISSUE TITLE
[FEATURE] Add interface element for ranking up Skills/Talents

### ISSUE THREAD

**Issue by stbz** [Eranziel/foundryvtt-lancer#51]
Ranking up Talents and Skills is unintuitive.

Maybe we want to add a button or a field to control the level of a skill or talent.

**Comment by mason-bially** [comment]
This seems to be relatively straight forward at the moment. Click `... -> edit -> + or -`. Would documentation in the wiki help close this issue?

**Comment by Eranziel** [comment]
Duplicate of #181.
