### ISSUE TITLE
[BUG] Click and Drag Doesn't replace items in occupied slots

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#513]
**Describe the bug**
When dragging a Mech Weapon, Weapon Mod, or Pilot Gear/Armor/Weapon into a slot on an actor sheet that already has an item of the same type, the newly-dragged item fails to replace the old item.

**To Reproduce**
1. Create a new pilot.
2. Go to that pilot's Narrative tab.
3. Open the Compendium -> Pilot Armor
4. Drag "Assault Hardsuit" onto the empty pilot armor slot. Observe it fills correctly.
5. Drag "Light Hardsuit" onto the occupied pilot armor slot. Observe that no change occurs.

**Expected behavior**
Dragging a new item onto an occupied item slot replaces the item currently in the slot with the new item.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Foundry built-in
 - Foundry version 10.291
 - Lancer system version 1.4.1

**Additional context**
The expected behavior occurs on Foundry v9, Lancer v1.3.1, Firefox and Chrome browsers.

**UPDATE:** Additionally, for the mech-related items, the mech item *does* go into the Mech's "Inventory"; it simply doesn't replace the equipped item. Dragging from the mech Inventory still doesn't cause the equipped item to swap.

**Discord contact info**
Valkyrion#6196

**Comment by Davis-K-Johnson** [comment]
I've checked with both mech weapons and pilot gear. I think it's working as intended now.

OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0
