### ISSUE TITLE
[BUG] Tokens always spawn with default art

### ISSUE THREAD

**Issue by VexWerewolf** [Eranziel/foundryvtt-lancer#520]
**Describe the bug**
Tokens with are always dropped into the world with the default art, regardless of what art has been assigned to their master actor.

**To Reproduce**
1. Create a mech, pilot or NPC in the actors panel.
2. Assign the actor custom artwork.
3. Drag and drop the actor into the world to create a token.

**Expected behavior**
The token should have the assigned artwork of the master actor.

**Screenshots**
![Token Art](https://user-images.githubusercontent.com/83786280/217895373-05874c48-3494-4b3e-9c87-87d5b2546f23.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Foundry version: Version 10
 - Lancer system version 1.4.2

**Discord contact info**
Vex#1075

**Comment by BoltsJ** [comment]
Are you assigning the prototype token image or just the actor portrait?

**Comment by Z3nner** [comment]
I am also having this issue, here is what I have observed.

In previous versions, assigning a character a picture on their character sheet for the first time also set the prototype token.
In the current version this isn't the case. Both have to be set independently, which is a big time sink when setting up several characters.

**Comment by VexWerewolf** [comment]
> Are you assigning the prototype token image or just the actor portrait?

Just the actor portrait, but this used to update the prototype token image as well, and it's how almost all other Foundry systems behave.
