### ISSUE TITLE
[BUG] Scan (Journal) Macro isn't updating existing scan journal entries

### ISSUE THREAD

**Issue by magusdraco** [Eranziel/foundryvtt-lancer#523]
**Describe the bug**
The Scan (Journal) macro is not updating existing scan journal entries when a NPC is scanned again. Changes in hp/heat/tier/weapons/systems, etc are not being recorded upon second or later scans when the variable updateExisting  = true.

**To Reproduce**
1. Target an NPC Actor that has not been scanned before with the Scan (Journal) Macro.
2. Execute the Scan (Journal) Macro. It will create a scan journal entry with the NPC's information.
3. Make a change to the NPC token or token's sheet (decrease or increase HP, Heat, Tier, etc).
4. Execute the Scan (Journal) Macro again. It will open the previously created scan journal entry but will not show any changes made to the NPC.

**Expected behavior**
The scan journal entry should update with whatever changes were made to the NPC when it was scanned a second time.

**Screenshots**
![scan journal entry](https://user-images.githubusercontent.com/119366831/218376709-6c5b7e93-f8d6-46c4-9889-f59f28177502.JPG)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Chrome v 109.0.5414.120
 - Foundry version 10
 - Lancer system version 1.5.1

**Additional context**

When the variable updateExisting = false the macro will create a new journal entry each time a NPC is scanned. These new journal entries do correctly document changes to the NPC.  It's working fine on new journal entries. The problem seems to only happen when it tries to update them.  I ran into this bug on both my current world and a freshly created one with no modules activated. I don't see any errors or warnings in the console. I tried this with a Tier 1 Goliath Class NPC with no templates or optionals and a Tier 1 Spite Class NPC with no templates or optionals.

**Discord contact info**

MagusDraco#1960

**Comment by Eranziel** [comment]
This was fixed by #569.
