### ISSUE TITLE
[BUG] Reserves Automatically Set to "RESOURCES"

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#524]
**Describe the bug**
Importing a Reserve from the Compendium automatically sets the Reserve's type to "RESOURCES" (note, it may look fine on the initial import, but close it and reopen it).

In addition, attempting to modify the type of a Reserve created from scratch has it initially set to be "RESOURCES" before being able to be changed.

Lastly, dragging a Reserve onto a Pilot's sheet, or modifying any of the Reserves on a pilot sheet in any way, will set all Reserves on that pilot to "RESOURCES".

**To Reproduce**
1. Go to the Reserves compendium.
2. Open the "Bombardment" reserve; observe its type is "Tactical".
3. Import the "Bombardment" reserve, then open its sheet, close it, and reopen it.
4. Observe the "Bombardment" reserve is now type "Resources".
5. Change the "Bombardment" reserve's type back to Tactical, then attempt to edit/change any other aspect of the reserve (e.g. "used").
6. Observe the reserve's type is reset to "Resources."
7. Change the "Bombardment" reserve's type back to "Tactical". Drag it onto a new pilot's Reserves section.
8. Observe the reserve's type is reset to "Resources."
9. Add another reserve to the pilot's sheet. Manually set its type to "Project". Set the "Bombardment" reserve's type back to "Tactical".
10. Mark the "Project" reserve as "used".
11. Open both the "Project" reserve and the "Bombardment" reserve's sheets and observe their types have been reset to "Resources".

**Expected behavior**
Whenever the Reserves item sheet updates in any way, it does not reset the "Type" field to "RESOURCES".

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Foundry version 10.291
 - Lancer system version 1.5.1

**Additional context**
This was likely needlessly thorough; this issue probably all stems from a single root cause.

**Discord contact info**
Valkyrion#6196

**Comment by Davis-K-Johnson** [comment]
All reserve types are working as intended for me.

OS: Windows 10
Browser: Chrome
Foundry version: 11.315
Lancer system version: 2.0.0
