### ISSUE TITLE
[FEATURE] v2.0 - No more Machine Mind!

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#526]
Noted issues with 2.0 release candidate:
- [x] Repair frame refview (used in mech inventory)
- [x] Talent rank macro errors
- [x] Talent action macro errors
- [x] Check roller HUD hangs, while attack HUD slides down immediately.
- [x] Refactor `mech_loadout_weapon_slot` to work in mech inventory
- [x] Mech mounts aren't loaded from frame properly?
- [x] Mech weapons not mounted during sync
- [x] "TODO deployables" - core power, mech traits
- [x] Mech system chat macro errors
- [x] Pilot HASE & grit do not propagate to mech
- [x] Pilot bonuses don't always propagate to mech? hp, sp, limsys
- [ ] ~~Prettier effects list on mechs~~ Not needed right now. Can be tackled in a future update to mech sheets.
- [x] WARNING: MECH INACTIVE Banner
- [x] Deployables created on import use the pilot's pre-import name. e.g. "[new pilot]'s Hex Charge"
- [x] New NPC classes have no stats
- [x] Can't add base/optional features to NPC classes or templates via drag & drop
- [x] NPC features sheet:
  - [x] Feature type selector does not commit to doc (trait, tech, weapon, etc...)
  - [x] Weapon type should be a selector
  - [x] New items have no accuracy or attack bonus so don't show an editable field when type is changed to Weapon or Tech
- [x] Several things default to "..." string content instead of "" with the "// MISSING ENTRY //" placeholder
  - [x] New talent rank descriptions
  - [x] New action descriptions
  - [x] New frame traits
  - [x] New mech weapon profile description
- [ ] #634
- [x] With Tags no longer being in a compendium, I don't see a way to add them to items anymore.
- [x] New weapon mods cannot add allowed weapon sizes or types
- [ ] #635
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/f57bb927-7f2b-4ba9-96ba-7288ae5aa44d)
- [x] Weapon mods in mech inventory should use rich renderer.
- [x] The `+` on Integrated Items for weapon mods and mech systems should be removed. ~~Clicking the `+` on Integrated Items for weapon mods and mech systems just adds a useless string "Integrated Item:"~~
- [x] Organizations don't have a model. (Closing an Organization sheet throws an error about `this.system.full_update_data` not existing.)
- [x] Reserve type has redundant redundant labels
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/f55d169a-de44-4343-b74d-0a0ca98c9654)
- [x] We should hide the skill trigger category selector, it's a useless artefact of old Comp/Con organization stuff
- [x] Core pilot weapons generate with no tags
- [x] Token bars are not editable because all attributes are seen as single values
- [x] NPC default actor images aren't working
- [x] NPC weapons origin TODO
- [x] NPC class & template sheets
  - [x] feature previews do not show tags
  - [x] feature context menus do not populate
- [x] Check and Attack roller HUDs throw error when cancelled
- [x] Right-click on item tags from actor sheet can open tag editor, but saving breaks the item?
- [x] Debug migrations for 1.X worlds
  - [x] Compendiums:
    - [x] Clear compendium data, with a popup to inform users which LCPs they had imported.
    - [x] ~~Trigger and await core data update before migrating actors & items.~~ Not actually possible, world doc migration happens as part of data preparation, before any of our migration functions get triggered. We do now trigger a re-migrate and save without diff after rebuilding core data, though, which should accomplish the same while also cleaning out data which doesn't belong in the new schema.
  - [x] Pilot HASE is not migrated, all 4 are 0 post-migration.
  - [x] Skill trigger rank resets to 1
  - [x] Existing Frame items do not have correct manufacturer post-migration. 
    - 1.X manufacturer ID is in `system.source.fallback_lid` with `system.source.type === "manufacturer"`
  - [x] Old deployables with `5 + {grit}` hp break validation.
  - [ ] ~~Existing PC deployables will lose their deployer.~~ As far as I can tell, the code to convert MM refs to Foundry UUIDs is working correctly, but for some reason the resulting UUIDs still do not work. Worlds migrated from 1.x will need to manually re-link deployers.
  - [x] Bonuses from talents & frames are not migrated correctly. e.g. +5 drone HP from drone commander and Hydra is not conferred to linked drones unless new copies (built in 2.0) are added to the pilot/mech.
  - [x] AP tag on items does not get migrated correctly.
  - [x] Check whether v10 Emperors break migration
- [x] Dragging a new Frame onto a mech should delete the old frame.
- [x] NPC sheet - templates are not click-to-open like classes are.
- [x] Hydra drones do not add pilot's grit to HP.

**Comment by whitespine** [comment]
- [ ] WARNING: MECH INACTIVE Banner

**Comment by Eranziel** [comment]
> Closing an Organization sheet throws an error about this.system.full_update_data not existing
Looks like the problem is that `organization`s don't have a model yet

**Comment by moroboshikan** [comment]
In fact, I have upgraded to the V11 version, but my friends and I really want to give it a try, and we also have partners who are very experienced in FVTT development. We would like to ask if we need testers (which also allows us to use LANCER's system first in V11). Thank you very much : ）

**Comment by Eranziel** [comment]
@moroboshikan It's not quite ready for beta testing yet - there are some other refactors that are still in progress, which leaves a lot of the automation/action features broken right now. If I decide to do a beta test before releasing 2.0 I'll try to remember to let you know!

**Comment by moroboshikan** [comment]
thanks very much! ; )

**Comment by sombranox** [comment]
I'd also potentially be interested in beta testing with a group I might be starting. And if there's any code tasks not already being worked up, I could pick some up to contribute to the refactor.

**Comment by OvanLRU** [comment]
I will be starting a campaign in December. Do you happen to have a timeline on the expected v11 release?

**Comment by Eranziel** [comment]
> I will be starting a campaign in December. Do you happen to have a timeline on the expected v11 release?

No timeline, that just leads to disappointment. 😉 It'll be ready when it's ready.

**Comment by Thegodemperorofmankind11** [comment]
Heh, I'm just as bad as the rest-of these nerds, unwillingly to go down to VTT 10, but still wanting to run lancer lol. If you do, beta test's I'd be more then happy to contribute.

**Comment by BoltsJ** [comment]
The OROCHI drones from the hydra fail data model validation on migration due to having the formula `5 + {grit}` for their hp max instead of a number. I've also seen that in 3rd party lcps. Perhaps we could convert that to an active effect on import.

**Comment by Eranziel** [comment]
@moroboshikan @sombranox @OvanLRU @Thegodemperorofmankind11 Lancer 2.0 has released now, available on Foundry v11. Thanks for your interest!

**Comment by Eranziel** [comment]
I've moved the remaining outstanding items to their own issues, so closing this one now.
