### ISSUE TITLE
[FEATURE] Configurable bonus damage for attacks

### ISSUE THREAD

**Issue by Skelepope** [Eranziel/foundryvtt-lancer#535]
**Is your feature request related to a problem? Please describe.**
My Death's Head has 3 different damage effecting modifiers than can be mixed and matched and no way to include any of them in the (automated) attack roll. This has lead to me creating 8 different weapon profiles for every combination, which was annoying to do and makes my sheet kinda bad to look at 

**Describe the solution you'd like**
In the targeting phase of the attack roll, have a selector for each numerical modifier your mech can apply (overpower calibre core bonus, nuclear cavalier 2 talent, thermal charge mod, ect)

**Describe alternatives you've considered**
The ability to copy weapon profiles, so you don't have to build them from the ground up if/when creating profiles for each modifer

**Discord contact info**
e.g. Skelepope#3174

**Comment by Eranziel** [comment]
Completed as of 74e1cc0d6386554375c37a8ea77902fc05a52c55.
