### ISSUE TITLE
[BUG] Added Tags from Mods not included in weapon attack

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#538]
**Describe the bug**
When making an attack with a weapon equipped with a weapon mod, the weapon's attack does not inherit the mod's added tags (despite showing as added on the Mech Sheet).

**To Reproduce**
1. Create a mech with a pilot.
2. Equip the mech with a Shotgun. Add "Supermassive Mod" to the Shotgun.
3. Roll an attack with the modded Shotgun. Observe that the chat card lacks the tags added by Supermassive Mod.
4. Reroll the attack until the damage rolls a 1. Observe that the Overkill applied by Supermassive Mod does not automatically trigger.

**Expected behavior**
Weapon attacks with modified weapons inherit the tags added by weapon mods. E.g. a weapon without innate Overkill equipped with Supermassive Mod should use Overkill automation.

**Screenshots**
Equipped Impaler Nailgun is modified with Supermassive Mod. Attack with the Nailgun rolled a 1 on damage despite having the "Overkill" added tag.
![image](https://user-images.githubusercontent.com/44978587/227668548-9ebfd838-f67e-4b02-b310-640708aaf496.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Foundry version 10.291
 - Lancer system version 1.5.1

**Discord contact info**
Valkyrion#6196

**Comment by tetra8** [comment]
I can confirm that this remains a problem (Foundry v10.291, Lancer system v1.5.4). In particular, Nanocomposite Adaptation does not give weapons smart and seeking, and weapons that weren't originally smart continue to target evasion.

**Comment by Eranziel** [comment]
This has been fixed in 2.0.
