### ISSUE TITLE
[FEATURE] Move or duplicate HASE values into the Frame//Loadout Tab

### ISSUE THREAD

**Issue by stbz** [Eranziel/foundryvtt-lancer#54]
HASE values are regularly used in mech combat and having to switch tabs to f.e. make an engineering check is annoying and unnecessary.

Move or duplicate the HASE Values and Macros into the Frame//Loadout Tab of the pilot sheet.

**Comment by Eranziel** [comment]
Implemented on dev as of the 21st. :) It was very annoying, agreed.
