### ISSUE TITLE
[BUG] No Automation Setting for NPC Recharges

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#546]
**Describe the bug**
There is no way to disable the automated NPC recharge roll when they start their turn.

**Expected behavior**
There should be a setting in system automation for disabling the automatic recharge rolls.

**Comment by msprijatelj** [comment]
I think a stretch goal for this one would be to find a way to only roll once for recharge when multiple GMs are logged in; perhaps a debounce function?

**Comment by Eranziel** [comment]
Yes, that's a good idea. Would be applicable to things like lock on consumption and (later) damage application.

Brainstorming, maybe a function which returns false if there are any other GMs logged in which are either 1) higher-ranked (GM > assistant GM), or 2) user ID is lower?

**Comment by Eranziel** [comment]
There is actually a function for this in Foundry v11 core. `game.users.activeGM()` returns only one or zero users, so we can use that to see if the active GM is the client's user before running this kind of code.

**Comment by msprijatelj** [comment]
@Eranziel Would using that function negatively affect people who aren’t the active GM but control an NPC?
