### ISSUE TITLE
[FEATURE] Alternate deployable sheet for NPC deployables that automatically scales to tier of assigned NPC?

### ISSUE THREAD

**Issue by Cakeisgreater** [Eranziel/foundryvtt-lancer#547]
A separate or alternate sheet for deployables that takes account of Tier scaling, much like the way NPC tier scaling is handled. This way deployables can have different HP, Evasion, and E-Def (etc). depending on their tier. A small QoL feature.

Optionally, maybe have the deployable's tier match that of their assigned NPC. Furthermore, if possible, have the sheet *toggle* to NPC deployable sheet if and NPC is assigned to the deployable, thus revealing options for stats by tier.

**Comment by Eranziel** [comment]
The NPC data in LCPs doesn't include any deployable data, so stats per tier etc... would all have to be manually entered. Is that still something that you think would be useful?

**Comment by msprijatelj** [comment]
This may be worth revisiting after the compcon v3 release? The Lancer v2 ability to pass parseable strings to deployable HP likely does a lot of work for scaling them.
