### ISSUE TITLE
[BUG] Lock On Not Automatically Removed On Player Tech Attacks

### ISSUE THREAD

**Issue by tetra8** [Eranziel/foundryvtt-lancer#549]
**Describe The Bug**
Unlike with melee and ranged attacks, lock on is not automatically removed when players consume it with their tech attacks. This applies to both basic tech attacks and tech attacks from other sources (e.g. H0R_OS System Upgrade I).

**To Reproduce**
1. As a player, target an NPC with lock on.
2. Use a tech attack with the 'Consume Lock On' box checked.

**Platform**
 - Foundry Version 10.291
 - Lancer System Version 1.5.4

**Discord Contact Info**
tetra#0821

**Comment by Davis-K-Johnson** [comment]
I was just testing this and it seems to be fixed
