### ISSUE TITLE
[FEATURE] Create Actor default to NPC sheet

### ISSUE THREAD

**Issue by perijove** [Eranziel/foundryvtt-lancer#550]
**Is your feature request related to a problem? Please describe.**
When I create NPCs, I typically make several at once. It's easy to miss the step of selecting the NPC actor type, meaning I frequently make new NPCs as Pilots by accident

**Describe the solution you'd like**
The character type for new Actors should have NPC at the top/default of the list, as that's the type that is made most often.

**Describe alternatives you've considered**
A toggle in the module settings for selecting which type of actor
A method of quickly changing the actor type, preserving the name and token info, so that a mistake can be quickly corrected

**Discord contact info**
TK#5172
Perijove#5043

**Comment by codyhod** [comment]
This seems to already be the default behaviour in 2.0, so this issue can likely be resolved.

Might be worth noting that other FoundryVTT systems also seem to default to the Player Character equivalant - so maybe Pilot is more appropriate for sticking to a standard in the community? If so, I would think a toggle in the module settings would be appropriate.
