### ISSUE TITLE
[FEATURE] Moddable Structure + Stress Tables

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#551]
**Is your feature request related to a problem? Please describe.**
I want to use alternative rules for the Lancer Structure Damage and Overheating tables, but am unable to easily change which tables are called by Structure/Overheating automation.

**Describe the solution you'd like**
I would like the Structure Damage and Overheating automation to be patchable by mods. Perhaps they could be turned into system built-in Rollable Tables that are called by the Structure/Stress automation, which could then be modified by the GM? Or at least allow for the call to the table to be patched so that module makers can introduce their own custom routes for Structure and Stress automation?

Some use cases I would love to see supported:

- Passing an arbitrary dice expression to the tables, so you could pass a custom value like "(actor.structure)d6kh1" or even simply "1d6"
- Ability to patch out the "multiple 1s" result (since it would likely need to be external to the table if Foundry doesn't support that functionality)
- Ability to provide appropriate RollTable documents for the Structure/Stress automation calls

**Describe alternatives you've considered**
Using a custom smattering of rolltables, triggers, and custom macros for Foundry as-is as a workaround.

**Additional context**
Some of this functionality may be best left to a separate module, but it would be incredibly helpful if the existing facilitated such a hypothetical module. I'm not 100% sure of the best practices for such a thing; I would trust that the main devs would know how to do that best.

**Discord contact info**
Valkyrion#6196

**Comment by Eranziel** [comment]
The [flows API](https://github.com/Eranziel/foundryvtt-lancer/blob/master/docs%2Fflow_api.md) provides a way to modify the stress/structure automation, so that should fill this need!
