### ISSUE TITLE
[BUG] Status effects no longer appear on the token status context menu

### ISSUE THREAD

**Issue by Project39** [Eranziel/foundryvtt-lancer#570]
**Describe the bug**
Since update V1.5.5 status effects no longer appear in the status right click menu on tokens

**Expected behavior**
In previous versions all the status options were displayed in that context menu

**Screenshots**
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/35593364/7c0b3fa5-3eb3-4cb1-b889-c8c2f5aef6d6)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Running from the foundry VTT window on the host machine
 - Foundry version: 10.303
 - Lancer system version: 1.5.5

**Additional context**
I spun up an entirely new world to confirm it wasn't just an issue with the world I had before the 1.5.5 update, in my old world the burning and overshield status effects are still in the menu but nothing else.

The new world has no modules installed other than the lancer core system.

The status/condition compendium entry does have all the statuses I'd expect to be there

**Discord contact info**
Prezo

**Comment by MaxPelly** [comment]
same here, just updated a world now only have burn and overshield

**Comment by sirbayer** [comment]
Similar issue where the default Foundry status icons are missing. All others are working fine, it looks like.

**Comment by MaxPelly** [comment]
anyone know if the 1.6 bump fixed this?

**Comment by Eranziel** [comment]
Sorry I missed this before I put out 1.6.0! I'll release a fix soon that enables the defaults if no icon sets are selected.

**Comment by sirbayer** [comment]
Does that fix also resolve the issue of the defaults not appearing when configured on while others are also enabled?
