### ISSUE TITLE
[FEATURE] Update to Foundry v.11

### ISSUE THREAD

**Issue by Croat86** [Eranziel/foundryvtt-lancer#577]
Will there be an Update for the Foundry Version 11? The Problem is, that Version 11 has no backwards combability for Games of older Versions.

Thx man o/
Lexmechanicus#7048

**Comment by droidcraft314** [comment]
would also like this

**Comment by dodgepong** [comment]
I suppose technically there isn't already an issue for this open, but it's worth noting that v11 support is in progress. The issue is that it's part of a whole 2.0 release of the LANCER system, so it's taking some time to complete. It's not really feasible to backport v11 support to the 1.X release, so the recommendation for now is to run v10 for the time being (in a parallel installation if possible if you need v11 for other systems).

**Comment by droidcraft314** [comment]
ah i hadn't realized there was on ongoing update. its really cool that people are working on this, i look forward to playing it

**Comment by OvanLRU** [comment]
Any update on when Version 2.0 of Lancer will be out? Seen last update was several months ago. Or how we can help get it things done.

**Comment by CyberFoxar** [comment]
Probing here, as I don't see any movement ? Or is the 2.X version developped in a separate repo ?

**Comment by nuzio1087** [comment]
> It's on the 2.0-rc branch: https://github.com/Eranziel/foundryvtt-lancer/tree/2.0-rc

Does this mean it's available for download and usage, or just that progress is being made on the 2.0 release? If its the former, how do you install this version? I'm a little lost and don't want to uninstall my current version of Foundry since that's the only way I have to play Lancer on it atm.

**Comment by dodgepong** [comment]
It just means progress is being made on the 2.0 release. There is no public release of the Lancer system for Foundry 11+ yet. The only way to use it is to download an older version of Foundry for the time being.

**Comment by nedredmond** [comment]
Could you release an alpha version in the meantime? I am using Forge and cannot have a parallel core version.

**Comment by dodgepong** [comment]
A test release will be made when it's ready.

**Comment by Eranziel** [comment]
Yeah, I'm not a big fan of alpha releases for this sort of thing. Someone's going to use it for a real game, break stuff, then expect help fixing it.

I'll be making a release when I'm confident it won't break anything major.

**Comment by nicemoreoften** [comment]
Will the upcoming release be for foundry V12 as it's now stable, or remain targeted toward V11?

**Comment by Eranziel** [comment]
Next release will be for v11. After that, we'll look at v12. There may be a few v11 releases before we release v12 support, but it doesn't look too bad to update to 12.

**Comment by nedredmond** [comment]
May I take a whack at something in [the project](https://github.com/users/Eranziel/projects/3) Senior software engineer here. If so, any recommendations for a first task to get acquianted?

**Comment by msprijatelj** [comment]
I think any help for v11 is welcome. The parsing issue sounds like a good one to investigate if the current v11 release candidate has yet to support it!

**Comment by Eranziel** [comment]
Yes, help is welcome! No one is working on that particular issue yet to my knowledge, so go ahead. I'll comment on that issue with some specifics.
