### ISSUE TITLE
[FEATURE] Allow armor on player frames to be increased beyond 4

### ISSUE THREAD

**Issue by sealtrowitz** [Eranziel/foundryvtt-lancer#597]
**Is your feature request related to a problem? Please describe.**
Currently, when editing a player frame to increase the armor value to more than 4 (via entering a mech actor's View Inventory, the frame, then increasing the value to any number higher than 4), the value in the frame item itself displays as higher than 4 but when returning to the mech actor, it is capped at 4.

**Describe the solution you'd like**
Allow the mech actor sheet to display a number higher than 4.

**Describe alternatives you've considered**
I suppose some sort of status or active effect to increase it without editing the equipped frame is also possible, though I don't think the system really does anything like that yet. Maybe similar to how traits work for NPCs?

**Additional context**
Allowing this number to increase past the core limit of 4 would be useful for systems or frames that allow you to temporarily ignore this limit (for example, White Witch's core power and the Forge Subaltern's Armor Pack option). It would also be helpful in the cases of any homebrew that does this (I don't know of any off-hand, but there probably is some out there somewhere). It also seems like something that will be important for eventual damage automation.

**Discord contact info**
skedoodlebug

(edited to clarify additional context and fix a typo in my discord handle, oops)

**Comment by BoltsJ** [comment]
This appears to be fixed in 2.0
