### ISSUE TITLE
[BUG] Pilot data does not properly import into foundry – error :"cannot read properties of undefined (reading 'src')"

### ISSUE THREAD

**Issue by snarkishark** [Eranziel/foundryvtt-lancer#619]
**Describe the bug**
When attempting to import pilot data to foundry, there is an error `Failed to update pilot, likely due to missing LCP data: Cannot read properties of undefined (reading 'src')` and the pilot data is only partially imported. I don't think it is due to missing LCP data because I have checked that the same version of Wallflower lcp is in both compcon and foundry, and the issue persists when using a test pilot that uses no expansion features. I have tried the test pilot with three methods of import: logging into compcon within foundry, using a share code, and importing pilot json.

**To Reproduce**
1. Make sure the LCPs in foundry and compcon match
2. In foundry, create a new actor with type "pilot"
3. In the newly created pilot sheet, click "RM-4://SYNC"
4. In the import section, click "choose file" and upload the provided test pilot json
5. Wait for the pilot to import
6. You will see a yellow warning banner saying "failed to update pilot"
7. Open the console to see where the warning originated
8. In Foundry, the pilot sheet has the pilot name, talents, and skill triggers, but all stats are 0. The mech that gets generated has all stats to 0, no frame/loudout, and no pilot.

**Expected behavior**
The pilot data populates within foundry and matches the pilot data from compcon as written in the json file (which was exported from compcon). The pilot's stats and mech should match compcon.

**Screenshots**
<img width="591" alt="Screenshot 2024-03-29 at 5 20 05 PM" src="https://github.com/Eranziel/foundryvtt-lancer/assets/12775139/37470267-7ce2-4998-99c1-efa96a21fdc1">
<img width="740" alt="Screenshot 2024-03-29 at 5 20 13 PM" src="https://github.com/Eranziel/foundryvtt-lancer/assets/12775139/1fbbb4a0-2e3e-404a-9252-e98da4e9e8e2">
<img width="791" alt="Screenshot 2024-03-29 at 5 27 33 PM" src="https://github.com/Eranziel/foundryvtt-lancer/assets/12775139/316a8a32-a19d-4d6f-9c11-b835defecb89">
<img width="795" alt="Screenshot 2024-03-29 at 5 25 26 PM" src="https://github.com/Eranziel/foundryvtt-lancer/assets/12775139/ba76cef5-8419-4686-bfc1-334b3180f606">
<img width="802" alt="Screenshot 2024-03-29 at 5 51 30 PM" src="https://github.com/Eranziel/foundryvtt-lancer/assets/12775139/78dada7e-8d11-42cf-bd1a-748b1a93bbbf">

**Platform (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Foundry version 10.285
 - Lancer system version 1.6.1 – we were previously on 1.5.4 but updated to 1.6.1 to see if that resolved the issue

**Additional context**
Test pilot data: [TESTER.json](https://github.com/Eranziel/foundryvtt-lancer/files/14808822/TESTER.json)
This seems to be a similar issue to #510 
The syntax that causes the error is the same as what got updated in PR #540 (the error is thrown by a foundry common file, so not sure if this is helpful but it's something I noticed while researching).

**Discord contact info**
snarkishark#7257

**Comment by msprijatelj** [comment]
@snarkishark I believe you want to update your Foundry version to the latest V10 version. I believe there was an issue pre v10.291 that forced a change that makes imports on earlier versions break? You probably want 10.312 if I recall correctly.

**Comment by Eranziel** [comment]
Good catch, Valk, I missed that in my initial read. There definitely was an issue with one of the 10.28x builds which prevented imports from working.

**Comment by snarkishark** [comment]
> @snarkishark I believe you want to update your Foundry version to the latest V10 version. I believe there was an issue pre v10.291 that forced a change that makes imports on earlier versions break? You probably want 10.312 if I recall correctly.

Exactly right! My GM updated foundry and everything is working as expected, thank you so much for your time and reply. This is so cool!!
