### ISSUE TITLE
[BUG] Removing weapons from a mount doesn't remove them from the inventory

### ISSUE THREAD

**Issue by OKSombre** [Eranziel/foundryvtt-lancer#621]
**Describe the bug**
Removing weapons or weapon mods from the mounts of a player mech doesn't remove it from the mech's inventory like it does for other systems. There's also no way to remove them from the inventory sheet.

**To Reproduce**
1. Add a weapon or weapon mod from the compendium to one of the mount slots of a player mech
2. Click the options icon and click either "Delete Document"
3. Open the "View Inventory" on the "Mech//Stats" tab
4. The weapon should still be there
5. The options button for the weapon should also display a blank menu

**Expected behavior**
The "Delete Document" button should remove the weapon or mod from the mech's inventory similar to how it does for systems. There should also be a way to remove items when viewing them from the inventory page.

**Screenshots**
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/29206874/f8b071a4-0d8d-46d7-afa5-95bc38081067)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Foundry version 11.315
 - Lancer system version 2.0-rc

**Additional context**
It seems the remove options don't remove weapons or weapon mods from the `actor.items` map.   

**Discord contact info**
somberleo

**Comment by msprijatelj** [comment]
Having an outright delete in both the mech sheet and inventory sheet sounds reasonable if alongside an “unequip” option that behaves like “Remove” is right now. Having items in the inventory that aren’t equipped would be useful for folks that use Mech Loadouts and not want to comb through the compendiums to find their options again (nor fiddle with compcon imports).

**Comment by OKSombre** [comment]
Agreed. Though it looks like this was addressed recently, and it seems the "Unlink" button now removes the weapon while keeping it in the inventory.
