### ISSUE TITLE
[FEATURE] Compatibility with Dice so Nice

### ISSUE THREAD

**Issue by mateoinc** [Eranziel/foundryvtt-lancer#63]
When rolling from the character sheet, 3D dice from Dice so Nice don't appear. They only appear if rolling manually from chat.

**Comment by Eranziel** [comment]
This appears to be related to #59. Dice so Nice now recognizes attack rolls, but not damage rolls - same change required there. Will be fixed in next release.

**Comment by Eranziel** [comment]
In order for Dice so Nice to recognize damage rolls, they would need to be split into separate chat messages. A bit more work than intended, and may need some work on the aesthetics - 3 or 4 chat messages in a row (for weapons with multiple damage types) each with their own header will take up a lot of room.

**Comment by Eranziel** [comment]
Fixed this a while ago, we construct a fake aggregate roll which includes all attacks and damages for a macro, then pass that aggregate roll to the chat message. Closing.
