### ISSUE TITLE
[BUG] Overshield has a max of 14

### ISSUE THREAD

**Issue by CesarShogun** [Eranziel/foundryvtt-lancer#639]
**Describe the bug**
Overshield has a default maximum of 14. This makes the overshield bar to appear, and I don't want that. I can't remove that max.

**To Reproduce**
1. Drag any functional PC or NPC token on a scene
2. Right click on that token
3. Click on the cog icon
4. Click on "Resources"
5. Click on "Bar 1 Attribute" and select "overshield"
7. See that on "Bar 1 Data" appears "0/14"

**Expected behavior**
The max values makes the overshield bar appear, but I don't want that. I'm using Bar Brawl.

**Screenshots**
![overshield max](https://github.com/Eranziel/foundryvtt-lancer/assets/111893933/af042556-8062-498f-b82b-29a83d672416)

![overshield max bar brawl](https://github.com/Eranziel/foundryvtt-lancer/assets/111893933/441e2ad2-7afd-4912-86e5-4c4d40bccb52)
This is with Bar Brawl

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Foundry version: v11 build 315
 - Lancer system version: 2.0.0

**Discord contact info**
I'm @Zexarius in the Pilot NET discord

**Comment by Eranziel** [comment]
This is tricky, it's not easy (perhaps even impossible?) to support both allowing overshield to be a bar and allowing it to be used as a single value with no bar.

I'll think on it; personally I prefer having overshield present as a bar, but I'm open to being in the minority here.

**Comment by CesarShogun** [comment]
I wasn't sure if it was a feature or a bug. I've found a workaround, so don't change something you don't want to. Your code, your rules ;)

**Comment by msprijatelj** [comment]
@CesarShogun what was the workaround, for reference?

**Comment by CesarShogun** [comment]
![bar brawl fix](https://github.com/Eranziel/foundryvtt-lancer/assets/111893933/acb9a14a-3109-4325-8eef-150c42821511)
I just made sure the bar will never appear by ticking those options (In Combat + Out of Combat)
