### ISSUE TITLE
[BUG] When I open a class on an NPC, I cannot drag optionfeatures out of the new window onto the NPC sheet

### ISSUE THREAD

**Issue by C-S-McFarland** [Eranziel/foundryvtt-lancer#640]
**Describe the bug**
Dragging and dropping out of the class item onto an NPC actor sheet does not work.

**To Reproduce**
1. Add the 1.0.5 NPC LCP to a Lancer world
2. Import an entry from the Premade NPCs into the actor list
3. On the new NPC actor sheet, click the three dots on the class for the actor
4. Try to drag out an optional feature onto the npc actor sheet
5. I can't get any of those objects to drag. 

**Expected behavior**
I expect to be able to drag and drop items out of the class onto the npc sheet.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Foundry version 11.315
 - Lancer system version 2.0.0

**Additional context**

**Discord contact info**
CSMcFarland

**Comment by C-S-McFarland** [comment]
I've been playing with it more, it seems I can sometimes get it to let me drag, but only systems and not weapons. And it's not always consistent. I'm getting no errors in the console.

Also, of note, I can make NPCs by hand, the old way, and it works fine.

**Comment by C-S-McFarland** [comment]
Ok, this feels like a CSS issue of some sort. The div.flexcol.lancer-body isn't draggable in reality, but if I click on div.effect-box or div.compact-tag-row.tag-list-append, those seem to work ok?

**Comment by C-S-McFarland** [comment]
After even more testing, this seems to work fine in Firefox, but in Chrome it's hard to grab a card to drag in unless you drag it in the right place.

**Comment by tw-blob** [comment]
I've poked around while coming across another issue. This is also a Chrome only issue for me.

The problem only occurs with optional features. It also only occurs when one opens the class from the NPC sheet. It's not present when one opens a class from the compendium.

Finally, it only occurs when the bottom of the non-optional features is visible. Once one scrolls down far enough so only optional features are visible it works as expected. 

It seems to only effect a certain static height of a feature. So larger features with more text can still be dragged by the lower areas.

I've marked the rough areas that are un-draggable in the first image. Everything works fine once I scroll down to the position of the second image.
![undraggable npc features](https://github.com/user-attachments/assets/ff952ab0-bab0-4ced-a4a5-8ae757539763)
![draggable npc features](https://github.com/user-attachments/assets/b632dd6d-17d2-4992-95af-4c886d8b5836)

**Comment by tw-blob** [comment]
The un-draggeble area the same size as the DROP HERE field that pops up. As it doesn't show up if you scroll further down I expect the draggble area of a features is offset by it, while where it is displayed is not.

![npc_class_drop_here](https://github.com/user-attachments/assets/d65e5b8f-0fa2-4928-bcd4-edd7f01c7c4f)
