### ISSUE TITLE
[BUG] Adding character to initiative when no encounter exists causes error popup

### ISSUE THREAD

**Issue by HydrallUrakan** [Eranziel/foundryvtt-lancer#641]
**Describe the bug**
While testing the new update, I noticed that adding a mech to the initiative tracker with no existing encounter causes a red error popup - it didn't appear to actually break anything, at least to my eyes, but there might be something weird going on there.

Each time, the errors are as follows:

```undry.js:68326 TypeError: undefined. Cannot read properties of undefined (reading 'combatantId')
[No packages detected]
    at _LancerCombat._manageTurnEvents (foundry.js:21581:53)
    at _LancerCombat._onCreate (foundry.js:21419:10)
    at ClientDatabaseBackend.callback (foundry.js:13603:11)
    at foundry.js:13576:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13576:33)
fetch @ foundry.js:68326
notify @ foundry.js:68223
error @ foundry.js:68260
(anonymous) @ lancer.ts:212
lancer.ts:213 Unhandled rejection (promise:  Promise {<rejected>: TypeError: undefined. Cannot read properties of undefined (reading 'combatantId')
[No packages dete…} , reason:  TypeError: undefined. Cannot read properties of undefined (reading 'combatantId')
[No packages detected]
    at _LancerCombat._manageTurnEvents (foundry.js:21581:53)
    at _LancerCombat._onCreate (foundry.js:21419:10)
    at ClientDatabaseBackend.callback (foundry.js:13603:11)
    at foundry.js:13576:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13576:33) ).
(anonymous) @ lancer.ts:213
foundry.js:21581 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'combatantId')
[No packages detected]
    at _LancerCombat._manageTurnEvents (foundry.js:21581:53)
    at _LancerCombat._onCreate (foundry.js:21419:10)
    at ClientDatabaseBackend.callback (foundry.js:13603:11)
    at foundry.js:13576:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13576:33)
_
```

**To Reproduce**
1. Have no active encounter in the initiative tracker
2. Open a token's right click menu and click the crossed swords and shield icon
3. See error

**Expected behavior**
There's no seeming issues in the actual initiative tracker - everyone has their actions and everything. But there might be a problem under the hood.

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Foundry Client
 - Foundry: v11.315
 - Lancer: v2.0.0

**Comment by Eranziel** [comment]
It looks like this is because the `previous` combatant does not exist yet. Hopefully an easy fix.

![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/3a01e0cf-d771-48e3-88db-a8f6a457e7e7)

**Comment by Eranziel** [comment]
Well, this is a funny one! This is actually a Foundry bug, but normally only shows up in the console logs. Lancer has a hook which bubbles console errors up to error notifications, causing it to be seen.

I'll still try to put something in place to hide the error, at least.
