### ISSUE TITLE
[BUG] Integrated Ammo Feeds doesn't increase limsys uses

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#644]
**Describe the bug**
A pilot with the Integrated Ammo Feeds core bonus doesn't confer the +2 limited systems uses to its mech/mech's items.

**To Reproduce**
1. Create a pilot and mech actors
2. Drag pilot onto the mech to set the pilot
3. Add a system with limited uses to the mech
4. Add Integrated Ammo Feeds to the pilot
5. Limited uses on the mech item(s) does not increase

**Expected behavior**
The core bonus should apply to the mech's items.

**Screenshots**
Lancer 1.6.1/Foundry v10:
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/28c9bbbc-0b89-4175-a160-331b4b05ce49)

Same pilot and mech in Lancer 2.0.0/Foundry v11:
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/74c3635d-80c0-49f0-a2fa-b74b29884a19)

**Discord contact info**
Reported by `kirbo.exe` on Discord.

**Comment by msprijatelj** [comment]
Overcharge from Heatfall also isn't supported yet; not sure if that should be its own ticket or not, though?

**Comment by Eranziel** [comment]
I think that should be its own issue. Heatfall would need new automation; IAF has a `bonus` that isn't getting propagated to mechs properly.

**Comment by msprijatelj** [comment]
Roger, made #655 to address it.

**Comment by Eranziel** [comment]
Fixed in 654dfa81995eae80ee48f285fbe155f968988f60.
