### ISSUE TITLE
[BUG] Importing COMP/CON character with content pack talent does not import

### ISSUE THREAD

**Issue by Smashman** [Eranziel/foundryvtt-lancer#645]
**Describe the bug**
My character has the talent 'Pankrati' from Karrakin Trade Baronies. When I imported my character into Foundry using this

**To Reproduce**
1. Create a character with a content pack talent.
2. Log into COMP/CON
3. Import the character into FoundryVTT

**Expected behavior**
Talent should be imported

**Screenshots**
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/2972388/a1e85fd7-0567-41f7-b13a-7e18a1712c65)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/2972388/b868a648-2952-4b76-bede-244108be55d3)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Foundry version: v10
 - Lancer system version: 1.6.1

**Comment by msprijatelj** [comment]
Have you already imported the KTB LCP into Foundry itself? There's a Lancer Compendium Manager in Foundry that will let you do so. Installing it on CompCon is not enough to import it to Foundry.

**Comment by Smashman** [comment]
That solved the issue, thanks!
