### ISSUE TITLE
[BUG] Moving NPCs to/from compendiums breaks their thumbnail image

### ISSUE THREAD

**Issue by nayr31** [Eranziel/foundryvtt-lancer#647]
**Describe the bug**
When importing (either from bulk, or by pulling one-by-one) an NPC actor from a compendium, their thumbnail image (the image associated with the NPC Class) is no longer displayed. 

**To Reproduce**
1. Open any compendium with an NPC in it.
2. Import/Export NPC to/from compendium/actor tab.

**Expected behavior**
The image persists between operation.

![image](https://github.com/Eranziel/foundryvtt-lancer/assets/69859977/6943c9e2-be4b-415f-88b1-2b5cd5bee7d1)

**Platform (please complete the following information):**
 - OS: Windows 10 (Forge VTT)
 - Browser: firefox
 - Foundry version 11.315
 - Lancer system version: 2.0.0

**Additional context**

**Note 1:** Removing and reapplying the NPC Class reapplies the image thumbnail.

**Note 2:** Only the thumbnail is missing, the token is fine.

**Discord contact info**
calicoskunk

**Comment by BoltsJ** [comment]
This also affects duplicating and I believe affects all document types. It's caused by the code that applies defaults being too aggressive.

**Comment by BoltsJ** [comment]
Related: #532
