### ISSUE TITLE
[BUG] Active Effects Three-Dot Menu Has Edit Twice

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#653]
**Describe the bug**
Effects listed under the EFFECTS//ACTIVE tab for mechs have "Edit" listed twice in their three-dot menu, but only the bottom one works.

**To Reproduce**
1. Create a new mech actor.
2. Drag the mech actor onto the active scene.
3. Add a status to the mech actor.
4. Open the mech's actor sheet and navigate to the EFFECTS//ACTIVE tab.
5. Click the 3-dot button for the status added to the actor.
6. Observe that Edit is listed twice.
7. Click on both the top and bottom Edit option. Observe that only the bottom option opens a dialogue box.

**Expected behavior**
Only one Edit button shows up in the 3-dot menu for an active effect. In addition, I would expect there to be a "delete" option for removing unwanted active effects.

**Screenshots**
Example of "two edits":
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/44978587/95d13989-32cf-46a6-acf6-3d63376a17c1)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Foundry version 11.315
 - Lancer system version 2.0.1

**Additional context**
Having the deletion of effects as an option would also be helpful when a random active effect gets "stuck" on an actor and I'm unable to remove it through the UI.

**Discord contact info**
_valkyrion

**Comment by BoltsJ** [comment]
The button also shows up for ephemeral effects even though they can't be edited.
