### ISSUE TITLE
[BUG] Heatfall Coolant System Doesn't Replace Overcharge Track

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#655]
**Describe the bug**
The mechs of pilots with the Heatfall Coolant System Core Bonus do not cap their Overcharge at 1d6 heat per use.

**To Reproduce**
1. Create a new pilot + their mech
2. Give the pilot Heatfall Coolant System
3. Assign the pilot to the mech
4. Click Overcharge 3 times
5. See that the overcharge heat value is 1d6+4 instead of 1d6

**Expected behavior**
The Overcharge track in "bonuses" like those that Heatfall Coolant System has should replace the default Overcharge track for a mech. This should work for any kind of Overcharge track using similar syntax, not just Heatfall's.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Foundry version 11.315
 - Lancer system version 2.0.1

**Additional context**
A warning about the bonus not being supported also pops up at some point during the steps to reproduce.

**Discord contact info**
_valkyrion

**Comment by BoltsJ** [comment]
Looks like there's no place that the overcharge sequence gets replaced. I don't have a v10 world to check, but this did work before, right?

**Comment by msprijatelj** [comment]
Yeah, this worked before, I remember it having used Heatfall a few times.
