### ISSUE TITLE
[BUG] Protocol actions have a Quick Action cost associated with them

### ISSUE THREAD

**Issue by artejas** [Eranziel/foundryvtt-lancer#657]
**Describe the bug**
Protocol actions cost a Quick Action in the Compendium

**To Reproduce**
In the Lancer compendium for Mech / Pilot items, check the following:
- Sekhmet-Class NHP (Mech System)
- Tlaloc-Class NHP (Mech System)
- Crack Shot (Pilot Talent)
- Drone Commander (Pilot Talent)

**Expected behavior**
The associated action cost for these items should be a Protocol.

**Screenshots**
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/138275449/8ce1d36a-7ee9-4c2d-a85c-8dfd5ad3685a)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/138275449/59b01d7d-b9b3-4b24-a5b9-5b9a071e1058)

**Platform (please complete the following information):**
 - Windows
 - Brave Browser
 - Foundry version 11 build 315
 - Lancer system version 2.0.1

**Additional context**
Everything migrated from the previous v10 build seems to work correctly.
New mechs/pilots imported via comp/con do have the incorrect associated cost.

**Discord contact info**
Disinteger

**Comment by artejas** [comment]
Items which should be full actions also appear to be quick actions:
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/138275449/2d4bd192-4484-4a8a-b1cd-f17d3561a767)

**Comment by Eranziel** [comment]
Thanks for pointing this out! It affected nearly all actions on LCP imports and core data build since 2.0.1. Fixed by ee31710795d7cd33d0d6373600f047df7479a393.
