### ISSUE TITLE
Add sprites for LEECH and TEMPEST from SSMR

### ISSUE THREAD

**Issue by tradiuz** [Eranziel/foundryvtt-lancer#658]
**Is your feature request related to a problem? Please describe.**
When importing SSMR, the Tempest and Leech show up as default NPCs.

**Describe the solution you'd like**
I'd like to have the Tempest and Leech sprites added from Retrograde.

**Describe alternatives you've considered**
Manually updating it every time you import.

**Additional context**
Retrograde added the tempest and leech back in December.

**Discord contact info**
tradiuz

**Comment by Eranziel** [comment]
Closed by #659.
