### ISSUE TITLE
[FEATURE] Increase contrast of text for purple (HA) + orange (Galsim) color themes

### ISSUE THREAD

**Issue by DirkMcThermot** [Eranziel/foundryvtt-lancer#665]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
The HA and Forecast/Galsim color themes have grayish text on darker backgrounds, which makes them slightly harder to read than the text of the other themes. I think these two would be improved by having white text similarly to the HORUS color theme. The background color for all three themes is nearly the same darkness, but the HORUS text is noticeably higher contrast.
Note that I do not have any sort of visual impairments, but I think this is a fairly universally agreed-upon principle of graphic design (higher contrast text = more readable = better).

**Describe alternatives you've considered**
The only alternative I can imagine for this would be to allow a more granular degree of customization for each theme but I imagine this is much less feasible and harder to achieve than simply changing the color.

**Additional context**
![screenshot_feature_request](https://github.com/Eranziel/foundryvtt-lancer/assets/113132716/f21e5d04-f75a-45f0-94cc-b315f7e7e868)

**Discord contact info**
If you are willing to answer questions regarding this feature request on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
Username: dirkmcthermot
Display name: GM Colton

**Comment by BoltsJ** [comment]
https://webaim.org/resources/contrastchecker/

These were adapted from the equivalent comp/con colorschemes, so it might be worth checking the contrast for those and raising an issue there as well (assuming this isn't a problem introduces by our adaptation)

**Comment by DirkMcThermot** [comment]
I'll look into submitting the same sort of feature enhancement for Comp/Con shortly. Meanwhile, I actually found that the color scheme text colors are slightly different in C/C vs. Foundry.

Here's the orange (Forecast/Galsim) theme. The flavor text is still gray - which is what I assume carried over into Foundry - but the descriptions of traits and features uses high contrasting white text. This is also what it's like for the purple (HA) theme.

![compconcolor](https://github.com/Eranziel/foundryvtt-lancer/assets/113132716/8e188550-1114-4530-9f18-0f3789a05934)

**Comment by BoltsJ** [comment]
Yeah, it's not a 1:1 translation, so it might not be a problem in C/C. Certainly we should go through and tweak it to improve the contrast.

**Comment by Eranziel** [comment]
Release 2.0.4 tweaks the background and text colours for those two themes a bit, let me know if that feels like enough. They both pass the webaim checks now, at least!

**Comment by DirkMcThermot** [comment]
That was fast! And it looks perfect, no notes. Consider this resolved.
