### ISSUE TITLE
[BUG] Deployable HP config always resets to 5 on page refresh

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#669]
**Describe the bug**
Deployables' max HP is reset to 5 whenever the page is refreshed. This seems to be regardless of whether they have a deployer, and also ignores any hp bonus conferred by the deployer.

**Comment by Eranziel** [comment]
Reproduction steps:
- Open a deployable actor sheet.
- Go to Config tab, edit Max HP.
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/ff71e4a1-6624-46b4-ab88-5b8f9565c25e)
- Max HP shows a matching value now. Closing and opening the sheet preserves the value. Editing other values (e.g. overshield or Config -> Armor) maintains the new config HP and max HP.
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/02d613aa-e2a1-461f-8cb1-541c52ea9e2d)
- Refresh the page
- Open that actor sheet again
- Max HP and Config -> Max HP are now both 5.
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/98c580a3-c12f-4175-aca8-4c48712b3ae3)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/e2308702-4fc1-4f2c-8b36-96bc33187c6b)


The Deployable shown above was created in Lancer 1.6.1/v10 and migrated to 2.0.X/v11, but the issue is also apparent on newly created deployables. having a deployer set also does not seem to affect this.

**Comment by BoltsJ** [comment]
There is a report on discord that this can also affect EDef and Size. Probably others.
