### ISSUE TITLE
[BUG] Grenade Systems no longer show their Mine counterparts

### ISSUE THREAD

**Issue by TheNittles** [Eranziel/foundryvtt-lancer#680]
**Describe the bug**
When you add a grenade system (HAVOK Charges were the one I noticed this with, but it's also at least happening with Hex charges) the entry on the character sheet no longer lists the effects of deploying the grenade as a mine. This appears to happen either when importing from CompCon or when manually adding a system.

**To Reproduce**
1. Add a grenade system to a player mech, either from the compendium or by importing a mech that has one.

**Expected behavior**
The grenade system will have a second half of its entry that lists the effects of deploying it as a mine.

**Screenshots**
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/137443034/77df44dd-7b12-451c-8e8a-7e79ce3cb82c)
How the system appears on V11
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/137443034/bcde69e3-1cea-4cac-b131-15181c1465ed)
How it looked back in V10

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Foundry version: v11.315
 - Lancer system version: 2.1.0

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
Nittles

**Comment by TheNittles** [comment]
Upon further investigation, it appears any system that uses the Deployables section of the system sheet isn't showing that section on the character sheet. I noticed this with Webjaw Snares. You can see the deployable and corresponding action if you look at it in the compendium, but on the character sheet, nothing.

**Comment by Eranziel** [comment]
I believe this happens when you manually add the system by drag and drop from the compendium. It should not happen when importing from Comp/Con, unless something broke recently. See #649.

The fix is to open the deployable actor sheets (in the same folder as your nech actor), and drag the mech onto the deployable sheet. After that, opening the mech sheet will show the correct deployable cards. The wrong deployed getting set is a bug, so that will get fixed eventually.

**Comment by Eranziel** [comment]
Marking this as duplicate for now, unless there is some behaviour not already covered by #649.

**Comment by TheNittles** [comment]
I can open a new issue if you need, but once the mech is set as a deployer, the deployable does appear correctly, however, the action button for deploying them appears to be broken. Clicking it doesn't post the deployable's description to chat or decrement one of the uses of the deployable.

**Comment by Eranziel** [comment]
Deployable action buttons aren't implemented yet. ;-)
