### ISSUE TITLE
[BUG] third-party LCPs containing new frames fail to re-import after the first import, if the frame or license IDs do not contain the substring "mf"

### ISSUE THREAD

**Issue by aWinglessMonkey** [Eranziel/foundryvtt-lancer#687]
### Platform

 - OS: both Windows 10 and Debian on WSL 2 (also Windows 10)
 - Browser: Vivaldi
 - Foundry version: 11.315
 - Lancer system version: 2.1.0

### Description of the bug

When one imports nearly any third-party LCP containing mech frames, and especially ones containing new licenses, any later attempt to re-import the same LCP (or one of a higher version) will silently fail, outputting the following error to the console only:
```
Error: undefined id [<the UUID of a license-item from the first import>] does not exist in the CompendiumCollection collection.
    at CompendiumCollection.get (foundry.js:15329:36)
    at CompendiumCollection.get (foundry.js:16181:18)
    at #preUpdateDocumentArray (foundry.js:13645:30)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:13449:22)
    at async LancerItem.updateDocuments (commons.js:8001:23)
    at async createOrUpdateDocs (comp-builder.ts:196:24)
    at async importCP (comp-builder.ts:201:5)
    at async _LCPManager._onImportButtonClick (lcp-manager.ts:225:11)
importCP @ comp-builder.ts:256
await in importCP (async)
_onImportButtonClick @ lcp-manager.ts:225
(anonymous) @ lcp-manager.ts:131
```
No items will be reimported. This can block updating an LCP to a higher version, while still changing the version number listed in the compendium manager. This can also block the manual repair of a faulty field in an LCP, or the replacement of an item deleted from the system compendia (perhaps to ensure it is replaced by a repaired file with the same version-number).

I've determined that this is caused by something involved in parsing the license associated with the frame, particularly any frame object that does not have a `"license_id"` value containing the substring "mf", or - if the `"license_id"` field is missing - does not have an `"id"` value containing the substring "mf". See the "Troubleshooting" section below for details.

### To Reproduce

1. create a new Lancer world in Foundry
2. open the compendium manager and build the core data
3. import nearly any third-party LCP that contains frames, from any manufacturer (for example: Field Guide to Suldan v2.2.6, or Field Guide to Iridia v1.2.0, among many others - but these two usually won't throw any warnings or lesser errors during the first import)
4. import it again, or even a higher version of it
5. the console will throw the above-cited error (not shown over the canvas), failing to (re)import any items but updating the version number in the compendium if applicable; the console will also display `Import of <package-name> v<version> complete.` for the respective package immediately following the error (see the following screenshot)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/13388802/78850cd0-5675-4452-afd3-c92bb13a1cc1)
6. clear the compendium and repeat from step 2, but delete a mech system from the compendium between steps 3 and 4, to observe that it is not re-imported when the error is thrown

### Expected Behavior

The items in the LCP should be imported or reimported as expected for any first-party LCP, or any third-party LCP not containing frames. If an error occurs that blocks this, it should be reported to the user, the import process should not report success, and the version number in the compendium should not be changed (if applicable).

### Troubleshooting

This got a little long and messy, but it might be useful context. Click to expand if you'd like.

<details>

Attempt 1:
- follow the reproduction steps with `Field_Guide_To_Suldan_2.2.6.lcp`, observing the error as above
- create a copy of the Suldan LCP above
- delete `frames.json` from the copied LCP archive (unpack and repack as needed - 7zip has made this easy for me)
- import the altered LCP without resetting the compendium - the error is not thrown
- create another copy of the LCP
- in this copy, replace the entire contents of `frames.json` with the contents of `long-rim-data-1.2.1.lcp|frames.json`
- clear the compendium and repeat the reproduction steps with the altered Suldan LCP - the error is not thrown
- replace the contents of `frames.json` with only the Atlas frame's JSON object, and repeat the process - the error is not thrown
- alter any property for the Atlas frame (except `"license_id"`) in the LCP to match that of the Charioteer from the unaltered Suldan LCP
- clear the compendium and repeat the reproduction steps with this LCP - the error is not thrown
- alter the `"license_id"` for the frame to `"fgtsf_Charioteer"` and repeat - the error is thrown

Attempt 2:
- create a copy of the unaltered Suldan LCP, and alter the contents of `frames.json` to contain only the Charioteer's object
- add the `"license_id"` property to the frame's object, with the same value as the object's `"id"` property (`"fgtsf_charioteer"`)
 - (note that Field Guide to Suldan and *so many* other third-party modules omit the `"license_id"` property throughout their LCPs; this doesn't seem to bother Comp/Con or prevent it from assembling licenses for these modules, but it appears to be why most third-party license-items are entirely unpopulated in Lancer for Foundry (understandably) - the license-items *are* still populated with their frames, though, which becomes important in attempt 4)
- starting from a cleared and rebuilt compendium, import the altered LCP twice - the error is thrown
- change the `"license_id"` value from `"fgtsf_charioteer"` to `"mf_charioteer"`, and repeat - the error is not thrown

Attempt 3:
- follow the reproduction steps with `Field Guide to Iridia 1.2.0.lcp`, observing the error as above
 - Iridia *does* use the `"license_id"` property, and so produces very nice license items in Foundry; this makes me happy
- create a copy of the Iridia LCP above
- as in attempt 1, deleting `frames.json` from the archive prevents the error from being thrown
- instead, alter the contents of `frames.json` such that the text `"license_id": "moff_`  is, everywhere, replaced by `"license_id": "mf_`
- clear the compendium and repeat the reproduction steps with the altered LCP - the error is not thrown

Attempt 4:
- make yet another copy of the unaltered Suldan 2.2.6 LCP
- replace the contents of `frames.json` with the contents of `grimm__sons_v2_1.0.3.lcp|frames.json`
 - (Grimm & Sons v1.0.3 does not use the `"license_id"` field, but does not throw the error on a second import - it uses "mf_gs_" to prefix its frames, which creates a license-item with a `lid` starting with "mf")
- repeat the process - the error is not thrown
- remove all frames except the first, the John Henry, and repeat - the error is not thrown
- replace `"id": "mf_gs_john_henry"` with `"id": "mf_john_henry"` and repeat - the error is not thrown
- replace `"id": "mf_john_henry"` with `"id": "fgtsf_john_henry"` and repeat - the error is thrown
- return to the LCP from attempt 2, with only the Charioteer, and remove the `"license_id": "mf_charioteer"` field - this would throw the error
- replace `"id": "fgtsf_charioteer"` with `"id": "mf_charioteer"`, and repeat - the error is not thrown

Attempt 5:
- replace with `"id": "fmf_charioteer"` and repeat - the error is not thrown
 - (I was trying to throw the error as lazily as possible mid-attempt-4, but failed - so I tried more things)
- `"mfmf_charioteer"`, `"mfmfmfmfmfmfmfmf_charioteer"`, `"mgmfmfmfmfmfmfmf_charioteer"` - no error
- `"_m_charioteer"`, `"m_charioteer"`, `"fm_charioteer"` - error
- `"fgtsfmf_charioteer"`, `"fgtsf_charioteer_mf"`, `"fgtsf_chariomfteer"` - no error
- (these values are all visible in the license-item generated, containing only the Charioteer frame)

The core data and first-party LCPs all use `"license_id"` values identical to their frames' `"id"` values, which all begin with "mf_", so they're immune to this bug. The location of the substring "mf" does not appear to be important, but it's uncommon in third-party modules, which largely prefer to diversify their prefixes.

With a single offending frame, the UUID in the error is the UUID of the frame's license-item, which is definitely in the compendium with that UUID both before and after the error is thrown.

![image](https://github.com/Eranziel/foundryvtt-lancer/assets/13388802/f85fe818-6623-49eb-8bb7-ab2c79192a18)

</details>

### Discord Contact Info
@apteropith

**Comment by aWinglessMonkey** [comment]
More context has been discovered:
- first-party mech-licenses have the initial "mf" substituted with "lic" on import 
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/13388802/d91e4514-9c9d-440d-95b6-ccb702d50c6c)
- third-party mech-licenses which lack this substring do not experience a substitution
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/13388802/128cb68b-6553-42ea-a872-0d1b6f416a62)
- but if I add the substring ...
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/13388802/d873f1a5-5c0e-4bb4-ae71-0bc2b44a1ac7)
These effects are visible both through console inspection and in the item sheets themselves (which were faster to screencap).

Suggestion: substring substitution is inadvisable - rather, "lic_" should be *prepended* to the frame's ID. Whatever other book-keeping is failing (and resulting in the later error), it might resolve just from that change alone.

**Comment by Eranziel** [comment]
Good find! That should be a fairly easy fix, to change substitution for prepending. I'll try to include that fix in the next release.

**Comment by msprijatelj** [comment]
@Eranziel if there’s concern over folks not using license_id (it’s not enforced yet) I rec using a fallback of using the combined Manufacturer + Frame License to match (this is what compcon does at the moment; not ideal if there’s 2 HA Solomons but it’ll prevent collision on HA Solomon & MOI Solomon if the creator hasn’t used LIDs yet)
