### ISSUE TITLE
[FEATURE] Show Integrated Weapon Preview on Frame Sheet

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#70]
Frame sheets currently do not indicate whether or not a frame comes with an integrated weapon, or what the stats of that weapon are.

Add a weapon preview for the frame's integrated weapon.

**Comment by Grygon** [comment]
This is probably a Machine-Mind fix, not seeing anywhere we could access that info, at least for my test care of Engineer's prototype weapon or the Lancaster's Latch Drone

**Comment by whitespine** [comment]
Frame.CoreSystem.Integrated

**Comment by Grygon** [comment]
Ah, forgot that was under core... so will just need to do a different catch for pilot-based integrated weapons too

**Comment by Grygon** [comment]
As a secondary note: Would be _really_ good to have a centralized reference for integrated weapons/systems/etc, since they can actually come from just about anywhere. Something like Mech.Derived.GetIntegratedWeapons/Systems for example.
    And if that could wrap them in Integrated slots automatically too, that'd be great.

I'll probably do a hardcoded implementation for Mech Integrated weapons and let people manually equip anything else for now until we have a centralized reference location to collect them from all sources.

**Comment by Grygon** [comment]
Looks like WHITESPINE addressed this already.

_But_ if a frame has an integrated weapon it isn't also allowing for a talent-based integrated weapon. I want all the weapons!

![image](https://user-images.githubusercontent.com/647846/125175488-278da080-e192-11eb-923c-4205ab97df2f.png)

![image](https://user-images.githubusercontent.com/647846/125175497-34aa8f80-e192-11eb-88ef-6bc86c17dbba.png)

**Comment by whitespine** [comment]
Yeah idk how fancy we wanna get. It feels like a lot, but really only talent/frame/core bonus can provide integrated weapons.

Also I'm pretty sure with the new inventory button, you should be able to see the Engineer weapon being added - it just won't be equipped? Not 1000% sure there but I thought that was how I had it working.

**Comment by Grygon** [comment]
Yeah, it's in the inventory and can just be manually equipped but I feel like that's a bit of a gap in auto-equipping the integrated weapons
![image](https://user-images.githubusercontent.com/647846/125207379-9b42b280-e251-11eb-88f1-c1933935e928.png)

Not critical or anything, could wait for v1.1, but we'll probably want to leave this open until the edge cases are handled.

**Comment by Eranziel** [comment]
Integrated gear previews have been added to frame and talent sheets in 3466ec25b8d26a658664d8f8f36b76f6770a16d0.
