### ISSUE TITLE
[BUG] GMs cannot cause the automatic structure popup for players.

### ISSUE THREAD

**Issue by Fayeble** [Eranziel/foundryvtt-lancer#707]
**Describe the bug**
If a GM and a Player are connected and a GM reduces a Player's mech to 0 HP, automation does not cause the structure popup for either the GM or the player. It does work however if the Player is not connected, if the Player reduces their own mech to 0 HP, or if it is anything other than a Player's tokens. It throws no errors in the console.

**To Reproduce**
1. Create a new LANCER world.
2. Create a dummy player and log onto that in the browser of your choice.
3. Import and attach any character and their mech to the dummy player, making them owner.
4. Place the mech and set its HP to 0 on the GM's screen. There will be no popup on the player's screen.

**Expected behavior**
When a GM reduces the HP of a Player's mech to 0, the structure popup should appear for a player automatically if automation is enabled.

**Screenshots**
https://github.com/Eranziel/foundryvtt-lancer/assets/35507599/cf2ebca1-5ce1-44bf-9595-be519db5957f

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Foundry App (GM) / Chrome (Player)
 - Foundry version: v11 build 315
 - Lancer system version: 2.1.4

**Additional context**
It also includes Stress checks in the same manner, partially shown in the video.

**Discord contact info**
fayeble/Fayeble

**Comment by BoltsJ** [comment]
In the meantime, players can click the structure button in the stats tab to manually trigger a structure check
