### ISSUE TITLE
[BUG] Can't create MAIN/AUX or AUX/AUX mounts

### ISSUE THREAD

**Issue by SneepSnoop** [Eranziel/foundryvtt-lancer#73]
**Describe the bug**
When you attempt to make either a main/aux or aux/aux mount it immediately resets back to a main mount.

**To Reproduce**
Create a new mount and attempt to set it to main/aux or aux/aux.

**Expected behavior**
To be able to create a main/aux or aux/aux mount via setting it from the dropdown list.

**Desktop (please complete the following information):**
Foundry 0.6.6
Lancer 0.1.7
No modules active

**Comment by Grygon** [comment]
Will be fixed in next release!
