### ISSUE TITLE
[BUG] - Attack modal checkboxes

### ISSUE THREAD

**Issue by tradiuz** [Eranziel/foundryvtt-lancer#740]
**Describe the bug**
The attack modal diaglog has the X marks for the checkbox mis-aligned.

**To Reproduce**
1. Select a target token
2. Use a weapon or tech attack

**Expected behavior**
Xs should be centered in the box.

**Screenshots**
![image](https://github.com/user-attachments/assets/72d7ee64-c135-45bc-9d78-34c20279563d)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome and Firefopx
 - Foundry version: 10.315 (installed as container)
 - Lancer system version: 2.2.0

**Additional context**
Tested with 0 modules, direct to container port to rule out modules and proxy.

**Discord contact info**
tradiuz

**Comment by Eranziel** [comment]
Closed by #742.
