### ISSUE TITLE
Dragging NPC features to their own class duplicates them[BUG]

### ISSUE THREAD

**Issue by tw-blob** [Eranziel/foundryvtt-lancer#747]
**Describe the bug**
A dragged feature from a NPC class can be dropped back onto the class itself. This results in duplicating the feature.

**To Reproduce**
1. Create a new NPC
2. Open the compendium and add a NPC class
3. Close the compendium and open the class on the NPC sheet
4. Drag a feature and drop back into the feature list

**Expected behavior**
If the feature already exists in a NPC class it should not be duplicated.

**Screenshots**
![image](https://github.com/user-attachments/assets/813eab0e-7db0-4599-b8da-a07133430315)

**Platform (please complete the following information):**
 - Foundry version v11.315
 - Lancer system version v2.2.3

**Discord contact info**
.lopeck.

**Comment by BoltsJ** [comment]
We should convert the fields that hold the features to SetField and probably also check to make sure it's not already on the sheet before trying to add it in the drop handler.
