### ISSUE TITLE
[BUG] Permanent SP usage after importing

### ISSUE THREAD

**Issue by Stormagheddon** [Eranziel/foundryvtt-lancer#75]
**Describe the bug**
When you import a pilot with a mech weapon that has a System Point requirement, the importer accounts for the System Point cost even though the importer doesn't import weapons yet. 

**To Reproduce**
1. Import a pilot with a weapon that costs SP.
2. Go to the Frame//Loadout tab
3. Scroll down to the "Frame SP Used" counter

**Expected behavior**
Since the importer doesn't yet include weapons, the associated weapon SP usage shouldn't be counted either. 

**Screenshots**
https://i.imgur.com/DXRSVXh.png A freshly imported Everest with a Terashima Blade in Comp/Con, but nothing equipped in Foundry. 

**Desktop (please complete the following information):**
Foundry 0.6.6
Lancer 0.1.7
No modules active

**Comment by Eranziel** [comment]
Fixed in #114.
