### ISSUE TITLE
[BUG] Action Tracker Bar not displaying and Action buttons in sheet not working

### ISSUE THREAD

**Issue by Keyaira14** [Eranziel/foundryvtt-lancer#751]
**Describe the bug**
While in an encounter, the action bar which should appear at the bottom showing actions available to players for their turn, does not appear. In addition, the buttons under the Actions header of the <MECH//STATS> page of the character sheet do not function, doing nothing when pressed, and the movement button showing 0 movement left regardless of amount of movement used.

**To Reproduce**
1. Create Mech
2. Add Mech to map
3. Toggle Combat State
4. Start Encounter
5. Take turn
6. See error

**Expected behavior**
When taking turn, action bar should display showing what actions are left available for the turn. action buttons in sheet should function, as well as display movement left over.

**Screenshots**
![image](https://github.com/user-attachments/assets/fa3b4dc1-faba-4d1e-a06a-6ae4edcda1f5)
![image](https://github.com/user-attachments/assets/63758ed0-a223-4808-b854-ebecf8f2117c)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Opera, Firefox and native Foundry app
 - Foundry version: 11 build 315
 - Lancer system version: 2.2.4

**Additional context**
This happens regardless of active Modules, and I admittedly have never seen the Action Tracker bar apart from screenshots, and do not know what is actually supposed to happen when pressing any of the buttons under the Action header of the character sheet (presumably show standard actions available to your character under that category) as this is my first time setting up a Lancer campaign using Foundry VTT.

A third party player also connected to the game, and encountered the same issues.

**Discord contact info**
keyaira

**Comment by Eranziel** [comment]
Huh, I thought there was already an issue for this, but apparently not! Thanks for opening one.

**Comment by Eranziel** [comment]
Closed by #757.
