### ISSUE TITLE
[FEATURE] - Add Status Effect Descriptions from the effects field of the items

### ISSUE THREAD

**Issue by tradiuz** [Eranziel/foundryvtt-lancer#765]
**Is your feature request related to a problem? Please describe.**
Multiple Active Effects modules will display the "description" for an active effect.

**Describe the solution you'd like**
When creating status effects, e.g. populating `[...CONFIG.statusEffects]` , if there's an item for that status effect, copy the `effects` content (which is labelled Description in the UI) to the description field of the world's `statusEffect`.

**Describe alternatives you've considered**
A really janky macro to do this is:

```
let statusEffects = [...CONFIG.statusEffects];
const itemStatusEffects = game.items.filter(x => x.type === 'status');
itemStatusEffects.forEach((itemEffect) => {
    const existingItemEffect = statusEffects.find(x => x.name === itemEffect.name || x.id === itemEffect.system.id);
    if (existingItemEffect) { existingItemEffect.description = itemEffect.system.effects }
});
```

**Additional context**
Example with DFred's Convenient Effects:
![image](https://github.com/user-attachments/assets/922c0a0d-b3b5-451a-9a29-534a459caa08)

**Discord contact info**
tradiuz

**Comment by Eranziel** [comment]
Closed by d6bb93bbf749acf11ad1795e0e5e507b0f5010ba
