### ISSUE TITLE
[DOCS] Make Development Setup easier to follow

### ISSUE THREAD

**Issue by nedredmond** [Eranziel/foundryvtt-lancer#766]
After a very demanding project at work this summer I'm finally getting around to [the task I signed up for](https://github.com/users/Eranziel/projects/3?pane=issue&itemId=34315681) back in June!

However, as a newer Foundry developer, I had some trouble understanding this reference [Link](https://github.com/users/Eranziel/projects/3?pane=issue&itemId=34315681):
> ...your Foundry data directory (the one containing Config, Data, and Logs)

I searched through the Foundry directory for quite a while trying to understand what this meant, then I turned to Google and found [this helpful official doc](https://foundryvtt.com/article/user-data/) that lists all of the exact directories for user data (it wasn't clear I was looking for a _user_ data folder) for every major OS.

Please add a link to that doc to help future developers!

**Comment by Eranziel** [comment]
Done!
