### ISSUE TITLE
[FEATURE] Collapsible Cards

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#77]
Implement generic collapse/expand functionality which can be re-used throughout the system.

This should feature a CSS class to be applied to the container to collapse, and a button which collapses and expands the container it resides in. Provide functionality to set whether a given container is collapsed or expanded when first rendered. The intent is to add these buttons to the headers of system cards etc..., and clicking the button will hide the body of the card while leaving the header visible.

Apply this functionality to:
- [ ] talents
- [ ] weapons
- [ ] systems
- [ ] NPC features
- [ ] effect blocks in chat

**Comment by Eranziel** [comment]
Expanding this issue to implement a general collapse/expand div and button that can be used anywhere.

**Comment by ScyllPoesis** [comment]
Can take a look at this, should be pretty easy to generalize.

**Comment by ScyllPoesis** [comment]
Yep, was easy. The sheets seem to rerender quite a bit so I'll have to sessionstore a map to keep the state, but shouldn't be hard. Can wrap up in the afternoon and will document the process of adding this to any elements.

**Comment by ScyllPoesis** [comment]
So, system is pretty straightforward. From within `lancer-actor-sheet.ts` a new internal listener block called `_activateCollapses` will search the document for any DOMElements with class `collapse-trigger`. These elements should have a data attribute with key `data-collapse-id`, and anywhere else (usually sibling or child body div) you can place an element with class `collapse` and the same data attribute. Then whenever the trigger element gets clicked, collapse toggles. Presto boingo.

Additionally, the state of each element is saved with Foundry registry ID of the actor to sessionStorage, so users won't see constant resetting when the sheet gets redrawn, and having elements start collapsed is as simple as adding static `collapsed` class to the `collapse` div.

Ex:
```
    <span class="lancer-header loadout-category submajor">
        <i class="mdi mdi-unfold-less-horizontal collapse-trigger collapse-icon" data-collapse-id="weapons"></i>   
        <span>MOUNTED WEAPONS</span>
        <a class="gen-control fas fa-plus" data-action="append" data-path="${loadout_path}.WepMounts" data-action-value="(struct)wep_mount"></a>
        <a class="reset-all-weapon-mounts-button fas fa-redo" data-path="${loadout_path}.WepMounts"></a>
    </span>
    <div class="wraprow double collapse" data-collapse-id="weapons">
    ...
```

**Comment by ScyllPoesis** [comment]
System was updated a bit more to handle elements outside the actor sheets. Now lives in `collapse.ts` and has an additional data attribute you can use `data-collapse-store`, which will persist the state of the collapse into browser sessionStorage. 

Additionally, you will need to reapply triggers upon creating or modifying trigger elements, using the exported `applyCollapseListeners()` function.

**Comment by Grygon** [comment]
Given Scyll's work, I'm going to call this fixed. If we missed anything that should be collapsible we can re-visit those specific instances
