### ISSUE TITLE
[BUG] no npc mechs 

### ISSUE THREAD

**Issue by dpsdct** [Eranziel/foundryvtt-lancer#774]
when going through the compendiums there is no npc mech stats or anything is this normal or did my core download mess up
i am new to this system so sorry if there not there and i am dumb

**Platform (please complete the following information):**
 Windows

 - Foundry version 11.315
 - Lancer system version 2.2.6

**Additional context**

**Discord contact info**
dpsdct

**Comment by msprijatelj** [comment]
You need to import the NPC LCP using the Lancer Compendium Manager first. Please check the Wiki tab on this GitHub for info on how to import LCPs and build NPCs.

**Comment by dpsdct** [comment]
within the wiki i am unable to find anything on where the LCPs are or how to use them it just says to import them but i can not find them at all

**Comment by Eranziel** [comment]
@dpsdct looks like you deleted your latest post, but I'll answer anyway. LCPs are files with data for Lancer content that isn't in the free core rules. You can find the LCPs for all official content on Massif's itch page. The core NPCs in particular are here: https://massif-press.itch.io/corebook-pdf

If you bought a physical copy of the core rulebook, it should have a QR code inside the front cover to give you access to the digital content. If it does not, send an email to Massif with proof of purchase. 

Let me know if that resolves your questions!

**Comment by Eranziel** [comment]
Going to close this issue now, but if that didn't solve your problem please do let us know.
