### ISSUE TITLE
[BUG] Status effects show empty icons

### ISSUE THREAD

**Issue by AqueonTheConjurer** [Eranziel/foundryvtt-lancer#775]
**Describe the bug**
From the "Apply Status Effects" option in the right click menu, only a few of the icons are visible. Most show as a broken image link.

**To Reproduce**
1. Go to any scene containing Actors.
2. Right click on an actor.
3. Select Apply Status Effects.

**Screenshots**
![image_2024-11-09_191743897](https://github.com/user-attachments/assets/6edc9b59-21e0-458a-9aec-c27ad040b011)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Foundry version 11.315
 - Lancer system version 2.3.0

**Discord contact info**
Aqueon#5874

**Comment by Eranziel** [comment]
I'm not able to reproduce this. Can you check the following things and report back?
- What errors are there in the console? (F12 or Ctrl+I on most browsers.) There should be errors for the missing images.
- Which status icon set(s) do you have selected in the Lancer settings?
- Do you have any custom status items in your world or compendiums?

**Comment by AqueonTheConjurer** [comment]
Wow, thanks for the quick response! Glad to hear it might just be me.

Console errors below: 
![image](https://github.com/user-attachments/assets/bff41b7f-9d2d-4260-9a2d-357fa7d8bf5e)

I have tried with all the available sets, but it's currently on Default.

No, I haven't tried adding any additional statuses.

I did confirm that the "broken" files do not exist in /systems/lancer/data/assets/icons/white
![image](https://github.com/user-attachments/assets/494d2e8a-7881-4c46-a45b-74d23286e761)

**Comment by Eranziel** [comment]
Is that the entire contents of the `.../icons/white` folder? There should be all of these: https://github.com/Eranziel/foundryvtt-lancer/tree/master/public%2Fassets%2Ficons%2Fwhite

Sounds to me like the install might have gotten corrupted. Can you try uninstalling and reinstalling Lancer?

**Comment by AqueonTheConjurer** [comment]
It was, yes. Reinstalling did not work, but manually pasting the information (copying the icon folder from the master branch to local) did! I'm willing to call it solved for now.
