### ISSUE TITLE
[BUG] Undo Damage Application on End-of-Turn Burn also reduces Burn

### ISSUE THREAD

**Issue by msprijatelj** [Eranziel/foundryvtt-lancer#779]
**Describe the bug**
Clicking the "undo damage" button on damage inflicted by Burn at the end of the turn also reduces Burn by same amount.

**To Reproduce**
1. Create a new PC Pilot + mech actor with a frame.
2. Create a token of the mech on the current scene. Give it X Burn, where X greater than 0.
3. Enter the token of the mech into combat. Start a combat round.
4. Start the mech's turn, then end the round. Click on the Burn damage check prompt. Repeat this step until the mech fails the Burn check.
5. Click on the damage application button for the Burn damage.
6. On the chat message that says "Mech took X Burn damage!" click the Undo button.
7. Observe that the damage was undone, but the Burn was also cleared.
8. Set the mech's Burn to a value Y, which is greater than X.
9. Repeat steps 5 and 6 using the Burn damage chat message from earlier.
10. Observe that the Mech's burn is now also equal to Y - X.

**Expected behavior**
The Undo Damage for End-of-Turn Burn does not reduce the amount of Burn on a character.

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Foundry version 11.315
 - Lancer system version 2.4.0

**Additional context**
Edge case, I know. That said, if it's possible to *not* apply extra Burn on the end-of-turn burn damage application, I hope it isn't a stretch to not reduce the damage on the Undo button?

**Discord contact info**
_valkyrion

**Comment by Eranziel** [comment]
Closed by e8faf446781cd499429a69d4fd4b484573182c53
