### ISSUE TITLE
[BUG] Importing from COMP/CON pulling from non-exiting compendiums

### ISSUE THREAD

**Issue by MrVauxs** [Eranziel/foundryvtt-lancer#80]
**Describe the bug**
As the title says, the COMP/CON import tries to import from packs that do not exist.

**To Reproduce**
1. Go to any character sheet
2. Use the Download button
3. Watch cascade of errors

**Expected behavior**
The character sheet from COMP/CON is imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/32039708/95020027-ffa06800-0668-11eb-8f87-38a18336f3f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 84.0.4147.135

**Foundry**
 - Foundry 0.6.6
 - LANCER 0.1.7
 - Core Data 2.0.35

**Comment by Eranziel** [comment]
This is an issue with the "create system-wide Compendiums" option, which will be removed in the next release for this reason. For now, switch the setting off and the importer should then find the Compendiums made by the Lancer Compendium Manager.
