### ISSUE TITLE
[BUG] Character sheet not displaying for one player

### ISSUE THREAD

**Issue by mateoinc** [Eranziel/foundryvtt-lancer#84]
The character sheet for one player (me) displays as a list of items and nothing else. This doesn't happen for other players or the GM. Happens in different browsers and in incognito mode. Happens with Foundry Version 0.6.6 and Lancer System 0.1.8 (problem started on 0.1.7). The character was imported from comp/con, and I think it's the only one with custom skills...?

**Comment by Grygon** [comment]
First off, are you getting any console errors (From F12)? If so, could you post it here?

After that, as a temporary solution, does a hard refresh (Ctrl+F5) solve it? That'll clear your cache, which should help if it's specific to one person.

**Comment by mateoinc** [comment]
Only error I see is:

```
Uncaught (in promise) TypeError: itemData.tags.find is not a function
    MechEquipment MechEquipment.js:18
    MechWeapon MechWeapon.js:9
    _MechWeapons ContentPack.js:16
    ContentPack ContentPack.js:16
    reload_store util.ts:544
```

But that's before checking the character. After opening a sheet it only says:

```
Foundry VTT | Rendering ActorSheet foundry.js:3970:15
Foundry VTT | Retrieved and compiled template templates/sheets/actor-sheet.html foundry.js:5339:16
Foundry VTT | Retrieved and compiled template templates/app-window.html foundry.js:5339:16
```

I tried on different browsers (Explorer, Edge, Firefox, and Chrome, which is what I usually use) so it shouldn't be a cache thing. Ctrl + F5 doesn't fix it.

**Comment by Grygon** [comment]
Hm, okay.

I have some stuff that I _think_ will be in the next release (from #85) which will make this a less fatal error, but we'll see about solving the underlying problem

**Comment by Eranziel** [comment]
The really strange part is that it doesn't affect the others in your game. That error should break things for everyone. The upside is that it isn't related to your custom skill.

Can you ask your GM:
1. Have they manually added any items to the Weapons Compendium? (i.e not using the Compendium Manager window.)
2. If not, ask them to try clearing Compendium data and re-building. That should fix the issue for now.

**Comment by sirbayer** [comment]
I've been experiencing this issue with Foundry 0.7.5 and LANCER 0.1.11. Rebuilding the compendium has fixed the issue, but it has happened to new players as they've joined. I haven't added anything to the Weapons Compendium, though I've built a custom compendium of NPC features.

**Comment by drukutulas** [comment]
I think this is part of the same issue, but ALL of my character sheets are displaying as Item lists, and the compendium assets are all empty. I've attached a screenshot of what it looks like. I just updated Foundry to version 0.7.5 and am on Lancer system version 0.1.12 when this happened. 
![oh no sheets and compendium](https://user-images.githubusercontent.com/56655538/97215571-d95e7b80-1781-11eb-9906-7dd5c45126d8.JPG)

**Comment by drukutulas** [comment]
Also, here are two screen shots of the errors I received when trying to open a character sheet:
![cannot read](https://user-images.githubusercontent.com/56655538/97216592-50e0da80-1783-11eb-945e-6e0ab329a883.JPG)
![caught in promise](https://user-images.githubusercontent.com/56655538/97216599-52aa9e00-1783-11eb-85bd-2c8732871a35.JPG)

**Comment by Grygon** [comment]
From those errors it looks like [this module](https://foundryvtt.com/packages/me5e/) is installed, which isn't compatible.

**Comment by drukutulas** [comment]
> From those errors it looks like [this module](https://foundryvtt.com/packages/me5e/) is installed, which isn't compatible.

That fixed it! I had unallowed the module, (or didn't allow it in game?) but uninstalling it fixed everything it seems. Thank You!!

**Comment by Eranziel** [comment]
Leaving this open for now, but if we don't get any more reports of this issue by the 0.1.14 release I'll close it then.

**Comment by Grygon** [comment]
I'm going to close this, I think we have enough catching logic where it shouldn't happen anymore
