### ISSUE TITLE
[BUG] Editing an equipped weapon makes it impossible to roll said weapon

### ISSUE THREAD

**Issue by Stormagheddon** [Eranziel/foundryvtt-lancer#86]
**Describe the bug**
When you edit a weapon equipped to a mount by clicking it's name, the weapon immediately becomes unusable, even if you don't actually change any of the stats of the weapon. 

**To Reproduce**
1. Add a weapon to a mount
2. Click on the weapon header
3. Try to roll the weapon 

**Expected behavior**
After editing a weapon (or just viewing the edit screen to see the tag) you should be able to roll by clicking the dice icon to the left. 

**Desktop (please complete the following information):**
Foundry 0.6.6
Lancer 0.1.8
No modules active

**Additional context**
I've noticed that when you try to edit a weapon, it adds a blank Kinetic damage type, but changing it to none or adding a damage number still breaks the roll button. This also only started happening after the 0.1.8 update, as I have a player who edited their weapon prior to the update, and it still works now.

**Comment by Grygon** [comment]
Able to replicate--looks like another instance of dict -> array conversion:
![image](https://user-images.githubusercontent.com/647846/95486323-7b93fc00-0958-11eb-9b7d-81b3e50e0e2c.png)

I'll take a look at it.
