### ISSUE TITLE
[FEATURE] Targeted Attack Macros

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#9]
Make attack macros responsive to targeting on the canvas. Compare attack rolls to target's evasion/e-defense, damage to target's armor, and preview damage done.

Optional: add a system setting which automatically subtracts damage dealt from recipient's HP? Creates issues around overshield, resistance, damage mitigation reactions, etc...

**Comment by BoltsJ** [comment]
Fixed in #295
