### ISSUE TITLE
Superfluous Underlines between Condition Icons in Combat Tracker 

### ISSUE THREAD

**Issue by trfunk** [Eranziel/foundryvtt-lancer#90]
**Describe the bug**
If an actor has already taken their turn in a round the system adds additional superfluous underlines between condition icons.

**To reproduce**
1. Add a few tokens to the combat tracker
2. Add conditions to an actor
3. Let actor take their turn

**Expected behavior**
No underlines

**Screenshots**

![image](https://user-images.githubusercontent.com/4313364/96272665-b5a37480-0fce-11eb-8c4d-bfbaa0173208.png)
![image](https://user-images.githubusercontent.com/4313364/96272770-d8ce2400-0fce-11eb-9dc8-1317793da599.png)

**Desktop**
 - OS: Win 10 x64
 - Browser Firefox (83.0a1)
 - Foundryvtt 0.6.6 (hosted on linux)
 - Lancer 0.1.10

**Comment by Eranziel** [comment]
Do you have the Furnace module installed? Lancer does not customize the behaviour of the combat tracker yet, and I was only able to reproduce on worlds with Furnace active.

If you are not able to reproduce with Furnace turned off, I recommend you create a bug report on their GitHub here: https://github.com/kakaroto/fvtt-module-furnace

**Comment by trfunk** [comment]
This seems indeed furnace related - it works properly without Furnace. I'll open an issue over at their repo, thanks!

**Comment by Eranziel** [comment]
If you want to give them more detail, it's the strikeout styling that they apply to the Actor's name that is also getting applied to the status icons.
