### ISSUE TITLE
[FEATURE] Token NPC Designation Icons.

### ISSUE THREAD

**Issue by Flintwyrm** [Eranziel/foundryvtt-lancer#92]
I have another Suggestion to add. What if you could add the Tier Icons to the conditions list as well as add the letters "V" "U" "G" "E" To designate Templates? This could be a good way of tagging tokens to let players know their tiers and templates with a simple look at the token.

Honestly something that allows the players to hover above the token which could say its template and class would be dope
Keeps the token name free for other stuff.

**Comment by msprijatelj** [comment]
NPC Tier icons were added; do we still feel the need for the VUEG letters too, or do we feel that modules (e.g. Token Tooltip Alt) are a better solution for this use case?

**Comment by dodgepong** [comment]
Personally I feel like using conditions for this is a hack, and feel as though the existing tier icons aren't super useful (though, granted, this is someone who would much sooner use Token Tooltip Alt).

**Comment by Eranziel** [comment]
I agree that using TTA or just putting templates in the token's name are better solutions here. People can always add their own status icons using CUB if they really want to go this route.
